import crypto from 'crypto';
import fs from 'fs';
import path from 'path';

import {
  Ajv2020,
  type AnySchema,
  type ValidateFunction,
} from 'ajv/dist/2020.js';

import { parseContractArtifactEnvelope } from './artifact.js';
import {
  buildCapacityCatalogArtifacts,
  buildCapacityControlPlaneArtifact,
  buildCapacityControlPlaneSchemaArtifacts,
  buildCapacityDynamicArtifact,
  buildCapacityFixtureArtifacts,
  buildCapacityLogicalDeltaArtifact,
  buildCapacityProtocolArtifact,
  CAPACITY_CONTROL_PLANE_ARTIFACT_DESCRIPTORS,
  CAPACITY_CONTROL_PLANE_SCHEMA_FORMAT_BY_TARGET,
} from './capacity-control-plane-artifacts.js';
import {
  CAPACITY_CONTROL_PLANE_FAULT_CASES,
  CAPACITY_CONTROL_PLANE_NEGATIVE_CASES,
  CAPACITY_CONTROL_PLANE_POSITIVE_CASES,
  evaluateCapacityControlPlaneCase,
} from './capacity-control-plane-fixtures.js';
import {
  buildCapacityLogicalSchemaDelta,
  CAPACITY_BASE_LOGICAL_SCHEMA_MANIFEST_HASH,
} from './capacity-control-plane-logical-source.js';
import {
  assertHistoricalG0_9Conformance,
  buildCapacityArtifactInventory,
  buildCapacityGateReview,
  buildCapacityMarkdownDeltaCoverage,
  buildCapacityProtocolCatalog,
  buildDeploymentCapacityPublication,
  calculateCapacityAdminRequestHash,
  capacityControlPlaneToolHash,
  CAPACITY_DENIAL_CATALOG_ENTRIES,
  CAPACITY_MARKDOWN_DELTA_SEEDS,
  CAPACITY_PERMISSION_CATALOG_ENTRIES,
  CAPACITY_REASON_CATALOG_ENTRIES,
  CAPACITY_SCHEMA_HISTORICAL_HASH,
  CAPACITY_BASELINE_HISTORICAL_HASH,
  G0_10_HISTORICAL_IDENTITIES,
  G0_9_HISTORICAL_ROOT_HASH,
  validateCapacityPublication,
} from './capacity-control-plane-source.js';
import {
  CAPACITY_ADMIN_COMMAND_TYPES,
  CAPACITY_ADMIN_DENIAL_CODES,
  CAPACITY_ADMIN_HUMAN_ENTRYPOINTS,
  CAPACITY_ADMIN_PERMISSION_CODES,
  CAPACITY_CHANGE_REASON_CODES,
  CAPACITY_INVENTORY_CLASSES,
  CAPACITY_MARKDOWN_DELTA_CATEGORIES,
  CAPACITY_PROTOCOL_IDS,
  type CapacityAdminCommand,
  type CapacityArtifactInventory,
  type CapacityConformanceCaseArtifact,
  type CapacityGateReview,
  type CapacityLogicalSchemaDelta,
  type CapacityMarkdownDeltaCoverage,
  type CapacityProtocolCatalog,
  type DeploymentRuntimeCapacitySnapshot,
} from './capacity-control-plane-types.js';
import { canonicalJson, domainSeparatedSha256 } from './hash.js';
import {
  LOGICAL_CHECK_KEYS,
  LOGICAL_COLUMN_KEYS,
  LOGICAL_FOREIGN_KEY_KEYS,
  LOGICAL_INDEX_KEYS,
  LOGICAL_PRIMARY_KEY_KEYS,
  LOGICAL_QUERY_KEYS,
  LOGICAL_TABLE_KEYS,
  LOGICAL_UNIQUE_KEY_KEYS,
} from './logical-schema-types.js';
import { buildDeploymentRuntimeCapacityBaseline } from './safety-sqlite-artifacts.js';
import { assertJsonObject, strictParseJsonBytes } from './strict-json.js';
import type {
  ContractArtifactEnvelope,
  JsonObject,
  JsonValue,
  Sha256Hash,
} from './types.js';

const contractsRoot = import.meta.dirname;
const repoRoot = path.resolve(contractsRoot, '../../..');
const workflowRuntimeRoot = path.resolve(contractsRoot, '..');
const addendumRoot = 'conformance/capacity-control-plane-addendum';
const manifestPath = `${addendumRoot}/contract-pack-capacity-control-plane-addendum.json`;
const domainCatalogPath = `${addendumRoot}/catalogs/capacity-control-plane-domain-separators.json`;

export class CapacityControlPlaneContractError extends Error {
  readonly code = 'capacity_control_plane_contract_drift';

  constructor(message: string) {
    super(message);
    this.name = 'CapacityControlPlaneContractError';
  }
}

function absoluteContractPath(relativePath: string): string {
  const absolute = path.resolve(contractsRoot, relativePath);
  if (!absolute.startsWith(`${contractsRoot}${path.sep}`))
    throw new CapacityControlPlaneContractError(
      `Contract path escapes root: ${relativePath}`,
    );
  return absolute;
}

function renderJson(value: JsonValue): string {
  return `${JSON.stringify(value, null, 2)}\n`;
}

function writeAtomic(relativePath: string, contents: string): void {
  const absolute = absoluteContractPath(relativePath);
  fs.mkdirSync(path.dirname(absolute), { recursive: true });
  const temporary = `${absolute}.tmp-${process.pid}`;
  fs.writeFileSync(temporary, contents, { encoding: 'utf8', mode: 0o644 });
  fs.renameSync(temporary, absolute);
}

function assertExpectedBytes(relativePath: string, expected: string): void {
  const actual = fs.readFileSync(absoluteContractPath(relativePath), 'utf8');
  if (actual !== expected)
    throw new CapacityControlPlaneContractError(
      `${relativePath} is not generated byte-for-byte; run npm run contracts:generate`,
    );
}

function descriptor(relativePath: string, artifact: ContractArtifactEnvelope) {
  return {
    path: relativePath,
    format: artifact.format,
    ref: artifact.ref,
    version: artifact.version,
    domain_separator: artifact.domain_separator,
    hash: artifact.hash,
  };
}

function fixturePayload(
  format: CapacityConformanceCaseArtifact['format'],
  cases: CapacityConformanceCaseArtifact['cases'],
): CapacityConformanceCaseArtifact {
  return { format, cases, case_count: cases.length };
}

function buildLeafArtifacts(): Array<[string, ContractArtifactEnvelope]> {
  const schemas = buildCapacityControlPlaneSchemaArtifacts();
  const catalogs = buildCapacityCatalogArtifacts(
    CAPACITY_PERMISSION_CATALOG_ENTRIES,
    CAPACITY_REASON_CATALOG_ENTRIES,
    CAPACITY_DENIAL_CATALOG_ENTRIES,
  );
  const protocol = buildCapacityProtocolArtifact(
    buildCapacityProtocolCatalog(),
  );
  const logicalDelta = buildCapacityLogicalDeltaArtifact(
    buildCapacityLogicalSchemaDelta(),
  );
  const fixtures = buildCapacityFixtureArtifacts(
    fixturePayload(
      'icarus.workflow-capacity-control-plane-positive-cases/1',
      CAPACITY_CONTROL_PLANE_POSITIVE_CASES.map((entry) => ({ ...entry })),
    ),
    fixturePayload(
      'icarus.workflow-capacity-control-plane-negative-cases/1',
      CAPACITY_CONTROL_PLANE_NEGATIVE_CASES.map((entry) => ({ ...entry })),
    ),
    fixturePayload(
      'icarus.workflow-capacity-control-plane-fault-cases/1',
      CAPACITY_CONTROL_PLANE_FAULT_CASES.map((entry) => ({ ...entry })),
    ),
  );
  const coverage = buildCapacityDynamicArtifact(
    'coverage',
    buildCapacityMarkdownDeltaCoverage(),
  );
  return [
    ...schemas,
    ...catalogs,
    protocol,
    logicalDelta,
    ...fixtures,
    coverage,
  ].sort(([left], [right]) => (left < right ? -1 : left > right ? 1 : 0));
}

function artifactByFormat(
  artifacts: Array<[string, ContractArtifactEnvelope]>,
  format: string,
): ContractArtifactEnvelope {
  const artifact = artifacts.find(
    ([, candidate]) => candidate.format === format,
  )?.[1];
  if (!artifact)
    throw new CapacityControlPlaneContractError(
      `Missing G0.10 artifact: ${format}`,
    );
  return artifact;
}

function payloadByFormat<T>(
  artifacts: Array<[string, ContractArtifactEnvelope]>,
  format: string,
): T {
  return artifactByFormat(artifacts, format).payload as unknown as T;
}

function buildDomainCatalogArtifact(
  artifacts: Array<[string, ContractArtifactEnvelope]>,
): ContractArtifactEnvelope {
  const entries = [
    ...artifacts.map(([relativePath, artifact]) => ({
      format: artifact.format,
      domain_separator: artifact.domain_separator,
      artifact_path: relativePath,
    })),
    {
      format: 'icarus.workflow-contract-pack-capacity-control-plane-addendum/1',
      domain_separator:
        'icarus:workflow-contract-pack-capacity-control-plane-addendum:1\n',
      artifact_path: manifestPath,
    },
    {
      format: 'icarus.workflow-capacity-control-plane-domain-separators/1',
      domain_separator:
        'icarus:workflow-capacity-control-plane-domain-separators:1\n',
      artifact_path: domainCatalogPath,
    },
    {
      format: 'icarus.deployment-runtime-capacity-publication/1',
      domain_separator: 'icarus:deployment-runtime-capacity-publication:1\n',
      artifact_path: `${addendumRoot}/schemas/deployment-runtime-capacity-publication-schema.json`,
    },
    {
      format: 'icarus.capacity-admin-command-request/1',
      domain_separator: 'icarus:capacity-admin-command-request:1\n',
      artifact_path: `${addendumRoot}/schemas/capacity-admin-command-schema.json`,
    },
  ].sort((left, right) =>
    left.format < right.format ? -1 : left.format > right.format ? 1 : 0,
  );
  return buildCapacityControlPlaneArtifact(
    'icarus.workflow-capacity-control-plane-domain-separators/1',
    'icarus.workflow-capacity-control-plane-domain-separators',
    'icarus:workflow-capacity-control-plane-domain-separators:1\n',
    { registry_version: 1, entries },
  );
}

function expectedArtifacts(): Array<[string, ContractArtifactEnvelope]> {
  const leafArtifacts = buildLeafArtifacts();
  const inventoryPayload = buildCapacityArtifactInventory(leafArtifacts);
  const inventory = buildCapacityDynamicArtifact('inventory', inventoryPayload);
  const evidenceHashes = [
    ...leafArtifacts.map(([, artifact]) => artifact.hash),
    inventory[1].hash,
  ];
  const gate = buildCapacityDynamicArtifact(
    'gate_review',
    buildCapacityGateReview(
      payloadByFormat<CapacityMarkdownDeltaCoverage>(
        leafArtifacts,
        'icarus.workflow-capacity-control-plane-markdown-delta-coverage/1',
      ),
      inventoryPayload,
      evidenceHashes,
    ),
  );
  const withoutDomain = [...leafArtifacts, inventory, gate].sort(
    ([left], [right]) => (left < right ? -1 : left > right ? 1 : 0),
  );
  const domain = buildDomainCatalogArtifact(withoutDomain);
  return [...withoutDomain, [domainCatalogPath, domain] as const].sort(
    ([left], [right]) => (left < right ? -1 : left > right ? 1 : 0),
  ) as Array<[string, ContractArtifactEnvelope]>;
}

function buildManifest(
  artifacts: Array<[string, ContractArtifactEnvelope]>,
): ContractArtifactEnvelope {
  const coverage = payloadByFormat<CapacityMarkdownDeltaCoverage>(
    artifacts,
    'icarus.workflow-capacity-control-plane-markdown-delta-coverage/1',
  );
  const inventory = payloadByFormat<CapacityArtifactInventory>(
    artifacts,
    'icarus.workflow-capacity-control-plane-artifact-inventory/1',
  );
  const review = payloadByFormat<CapacityGateReview>(
    artifacts,
    'icarus.workflow-capacity-control-plane-gate-review/1',
  );
  const protocol = payloadByFormat<CapacityProtocolCatalog>(
    artifacts,
    'icarus.workflow-capacity-control-plane-protocol/1',
  );
  const logicalDelta = payloadByFormat<CapacityLogicalSchemaDelta>(
    artifacts,
    'icarus.workflow-capacity-control-plane-logical-schema-delta/1',
  );
  return buildCapacityControlPlaneArtifact(
    'icarus.workflow-contract-pack-capacity-control-plane-addendum/1',
    'icarus.workflow-contract-pack-capacity-control-plane-addendum',
    'icarus:workflow-contract-pack-capacity-control-plane-addendum:1\n',
    {
      gate: 'G0.10',
      status: 'capacity_control_plane_addendum',
      gate_decision: 'pass',
      prior_g0_9_root_hash: G0_9_HISTORICAL_ROOT_HASH,
      historical_identity_hashes: { ...G0_10_HISTORICAL_IDENTITIES },
      capacity_schema_hash: CAPACITY_SCHEMA_HISTORICAL_HASH,
      capacity_baseline_hash: CAPACITY_BASELINE_HISTORICAL_HASH,
      generated_by_tool_hash: capacityControlPlaneToolHash(),
      markdown_delta_coverage_hash: coverage.coverage_hash,
      markdown_delta_coverage_entry_count: coverage.entries.length,
      artifact_inventory_hash: inventory.inventory_hash,
      artifact_inventory_entry_count: inventory.entry_count,
      gate_review_hash: review.review_hash,
      exit_criterion_count: review.exit_criteria.length,
      protocol_hash: protocol.protocol_hash,
      protocol_step_count: protocol.steps.length,
      crash_boundary_count: protocol.crash_boundaries.length,
      logical_schema_delta_hash: logicalDelta.delta_hash,
      logical_added_table_count: logicalDelta.added_tables.length,
      logical_extended_table_count: logicalDelta.extended_tables.length,
      permission_count: CAPACITY_ADMIN_PERMISSION_CODES.length,
      reason_count: CAPACITY_CHANGE_REASON_CODES.length,
      denial_count: CAPACITY_ADMIN_DENIAL_CODES.length,
      command_type_count: CAPACITY_ADMIN_COMMAND_TYPES.length,
      positive_case_count: CAPACITY_CONTROL_PLANE_POSITIVE_CASES.length,
      negative_case_count: CAPACITY_CONTROL_PLANE_NEGATIVE_CASES.length,
      fault_case_count: CAPACITY_CONTROL_PLANE_FAULT_CASES.length,
      g0_status: 'DONE',
      i11_status: 'DONE',
      g1_status: 'READY',
      g2_status: 'READY',
      g3_through_g9_status: 'NOT_READY',
      r014_status: 'CLOSED',
      executable_ddl_status: 'absent',
      workflow_runtime_store_status: 'absent',
      capacity_gateway_status: 'absent',
      capacity_publisher_status: 'absent',
      capacity_watcher_status: 'absent',
      scheduler_status: 'absent',
      runtime_center_ui_status: 'absent',
      golden_semantic_review_status: 'absent',
      golden_seal_status: 'not_run',
      conformance_entrypoint: 'npm run test:g0',
      artifacts: artifacts.map(([relativePath, artifact]) =>
        descriptor(relativePath, artifact),
      ),
    },
  );
}

function keyset(
  actual: string[],
  expected: readonly string[],
  label: string,
): void {
  if (canonicalJson(actual.sort()) !== canonicalJson([...expected].sort()))
    throw new CapacityControlPlaneContractError(
      `${label} TypeScript keyset drift`,
    );
}

function compileSchemas(
  artifacts: Array<[string, ContractArtifactEnvelope]>,
): Map<string, ValidateFunction> {
  const ajv = new Ajv2020({
    strict: true,
    allErrors: true,
    coerceTypes: false,
    useDefaults: false,
    removeAdditional: false,
  });
  const result = new Map<string, ValidateFunction>();
  for (const [targetFormat, schemaFormat] of Object.entries(
    CAPACITY_CONTROL_PLANE_SCHEMA_FORMAT_BY_TARGET,
  )) {
    const schema = artifactByFormat(artifacts, schemaFormat);
    result.set(targetFormat, ajv.compile(schema.payload as AnySchema));
  }
  return result;
}

function sampleCommands(
  capacity: DeploymentRuntimeCapacitySnapshot,
): CapacityAdminCommand[] {
  const releaseHash = `sha256:${'c'.repeat(64)}` as Sha256Hash;
  return [
    {
      command_type: 'initialize_deployment_capacity',
      command_id: 'capacity-command:initialize',
      idempotency_key: 'capacity-key:initialize',
      proposed_capacity: capacity,
      reason_code: 'initial_provisioning',
      core_release_hash: releaseHash,
      evidence_refs: ['core-release:evidence', 'baseline:evidence'],
    },
    {
      command_type: 'replace_deployment_capacity',
      command_id: 'capacity-command:replace',
      idempotency_key: 'capacity-key:replace',
      expected_capacity_revision: 1,
      expected_config_hash: capacity.config_hash,
      proposed_capacity: capacity,
      reason_code: 'planned_tuning',
      reason_text: 'Re-enable the audited snapshot under a new revision.',
      evidence_refs: [],
    },
  ];
}

function validateSchemas(
  artifacts: Array<[string, ContractArtifactEnvelope]>,
): void {
  const validators = compileSchemas(artifacts);
  for (const [relativePath, artifact] of artifacts) {
    const validate = validators.get(artifact.format);
    if (validate && !validate(artifact.payload))
      throw new CapacityControlPlaneContractError(
        `${relativePath} failed closed schema: ${JSON.stringify(validate.errors)}`,
      );
  }
  const capacity =
    buildDeploymentRuntimeCapacityBaseline() as DeploymentRuntimeCapacitySnapshot;
  const publication = buildDeploymentCapacityPublication(
    1,
    'capacity-change:genesis',
    null,
    capacity,
  );
  const publicationValidator = validators.get(
    'icarus.deployment-runtime-capacity-publication/1',
  )!;
  if (
    !publicationValidator(publication) ||
    validateCapacityPublication(publication)
  )
    throw new CapacityControlPlaneContractError(
      `Publication schema/type/hash conformance failed: ${JSON.stringify(publicationValidator.errors)}`,
    );
  const historicalCapacitySchema = parseContractArtifactEnvelope(
    strictParseJsonBytes(
      fs.readFileSync(
        absoluteContractPath('safety/deployment-runtime-capacity-schema.json'),
      ),
    ),
  );
  const {
    $schema: _historicalDialect,
    $id: _historicalId,
    title: _historicalTitle,
    ...historicalCapacityObjectSchema
  } = historicalCapacitySchema.payload;
  const publicationSchemaArtifact = artifactByFormat(
    artifacts,
    'icarus.deployment-runtime-capacity-publication-schema/1',
  );
  assertJsonObject(publicationSchemaArtifact.payload.properties);
  const publicationProperties = publicationSchemaArtifact.payload.properties;
  assertJsonObject(publicationProperties.capacity);
  if (
    canonicalJson(publicationProperties.capacity) !==
    canonicalJson(historicalCapacityObjectSchema)
  )
    throw new CapacityControlPlaneContractError(
      'Publication embedded Capacity schema drifted from the historical G0.5 closed schema',
    );
  const commandSchemaArtifact = artifactByFormat(
    artifacts,
    'icarus.capacity-admin-command-schema/1',
  );
  if (!Array.isArray(commandSchemaArtifact.payload.oneOf))
    throw new CapacityControlPlaneContractError(
      'Capacity command schema union is missing',
    );
  for (const branch of commandSchemaArtifact.payload.oneOf) {
    assertJsonObject(branch);
    assertJsonObject(branch.properties);
    const branchProperties = branch.properties;
    assertJsonObject(branchProperties.proposed_capacity);
    if (
      canonicalJson(branchProperties.proposed_capacity) !==
      canonicalJson(historicalCapacityObjectSchema)
    )
      throw new CapacityControlPlaneContractError(
        'Command embedded Capacity schema drifted from the historical G0.5 closed schema',
      );
  }
  const commandValidator = validators.get('icarus.capacity-admin-command/1')!;
  for (const command of sampleCommands(capacity)) {
    if (!commandValidator(command))
      throw new CapacityControlPlaneContractError(
        `Capacity command union conformance failed: ${JSON.stringify(commandValidator.errors)}`,
      );
    calculateCapacityAdminRequestHash(command);
  }
  const forged = {
    ...sampleCommands(capacity)[1],
    actor_ref: 'human:local-owner',
  };
  if (commandValidator(forged))
    throw new CapacityControlPlaneContractError(
      'Capacity command schema accepted forged Actor field',
    );
}

function validateCatalogs(
  artifacts: Array<[string, ContractArtifactEnvelope]>,
): void {
  const permission = artifactByFormat(
    artifacts,
    'icarus.workflow-capacity-permission-catalog/1',
  ).payload;
  const reason = artifactByFormat(
    artifacts,
    'icarus.workflow-capacity-reason-catalog/1',
  ).payload;
  const denial = artifactByFormat(
    artifacts,
    'icarus.workflow-capacity-denial-catalog/1',
  ).payload;
  if (
    canonicalJson(permission.permission_codes) !==
      canonicalJson([...CAPACITY_ADMIN_PERMISSION_CODES]) ||
    canonicalJson(reason.reason_codes) !==
      canonicalJson([...CAPACITY_CHANGE_REASON_CODES]) ||
    canonicalJson(denial.denial_codes) !==
      canonicalJson([...CAPACITY_ADMIN_DENIAL_CODES])
  )
    throw new CapacityControlPlaneContractError('Capacity catalog union drift');
  const catalogChecks: Array<{
    payload: JsonObject;
    entries: unknown;
    expectedEntries: unknown;
    hashDomain: string;
    label: string;
  }> = [
    {
      payload: permission,
      entries: permission.entries,
      expectedEntries: CAPACITY_PERMISSION_CATALOG_ENTRIES,
      hashDomain: 'icarus:workflow-capacity-permission-catalog-payload:1\n',
      label: 'permission',
    },
    {
      payload: reason,
      entries: reason.entries,
      expectedEntries: CAPACITY_REASON_CATALOG_ENTRIES,
      hashDomain: 'icarus:workflow-capacity-reason-catalog-payload:1\n',
      label: 'reason',
    },
    {
      payload: denial,
      entries: denial.entries,
      expectedEntries: CAPACITY_DENIAL_CATALOG_ENTRIES,
      hashDomain: 'icarus:workflow-capacity-denial-catalog-payload:1\n',
      label: 'denial',
    },
  ];
  for (const check of catalogChecks) {
    const { catalog_hash: catalogHash, ...withoutHash } = check.payload;
    if (
      canonicalJson(check.entries as JsonValue) !==
        canonicalJson(
          JSON.parse(JSON.stringify(check.expectedEntries)) as JsonValue,
        ) ||
      catalogHash !== domainSeparatedSha256(check.hashDomain, withoutHash)
    )
      throw new CapacityControlPlaneContractError(
        `Capacity ${check.label} catalog entries or hash drift`,
      );
  }
  const permissionEntries = permission.entries;
  if (
    !Array.isArray(permissionEntries) ||
    permissionEntries.length !== 1 ||
    (permissionEntries[0] as JsonObject).permission !==
      'runtime.capacity.manage' ||
    canonicalJson((permissionEntries[0] as JsonObject).allowed_entrypoints) !==
      canonicalJson([...CAPACITY_ADMIN_HUMAN_ENTRYPOINTS])
  )
    throw new CapacityControlPlaneContractError(
      'Capacity permission is not independent and closed',
    );
}

function validateProtocol(
  artifacts: Array<[string, ContractArtifactEnvelope]>,
): void {
  const protocol = payloadByFormat<CapacityProtocolCatalog>(
    artifacts,
    'icarus.workflow-capacity-control-plane-protocol/1',
  );
  const { protocol_hash: protocolHash, ...protocolWithoutHash } = protocol;
  if (
    canonicalJson(protocol.protocol_ids) !==
      canonicalJson([...CAPACITY_PROTOCOL_IDS]) ||
    canonicalJson(protocol.steps.map((step) => step.protocol_id)) !==
      canonicalJson([...CAPACITY_PROTOCOL_IDS]) ||
    protocol.crash_boundaries.length < 8 ||
    protocol.crash_boundaries.some(
      (boundary) => boundary.protocol_id === 'CAP0',
    ) ||
    !CAPACITY_PROTOCOL_IDS.filter((protocolId) => protocolId !== 'CAP0').every(
      (protocolId) =>
        protocol.crash_boundaries.some(
          (boundary) => boundary.protocol_id === protocolId,
        ),
    ) ||
    new Set(protocol.crash_boundaries.map((boundary) => boundary.boundary_id))
      .size !== protocol.crash_boundaries.length ||
    protocolHash !==
      domainSeparatedSha256(
        'icarus:workflow-capacity-control-plane-protocol:1\n',
        protocolWithoutHash as unknown as JsonValue,
      )
  )
    throw new CapacityControlPlaneContractError(
      'CAP0-CAP4 protocol or crash coverage drift',
    );
}

function validateLogicalDelta(
  artifacts: Array<[string, ContractArtifactEnvelope]>,
): void {
  const delta = payloadByFormat<CapacityLogicalSchemaDelta>(
    artifacts,
    'icarus.workflow-capacity-control-plane-logical-schema-delta/1',
  );
  const expectedTables = [
    'runtime_capacity_head',
    'runtime_capacity_admin_commands',
    'runtime_capacity_admin_invocations',
    'runtime_capacity_change_events',
  ];
  const { delta_hash: deltaHash, ...deltaWithoutHash } = delta;
  if (
    delta.base_logical_schema_manifest_hash !==
      CAPACITY_BASE_LOGICAL_SCHEMA_MANIFEST_HASH ||
    delta.delta_mode !== 'additive_only' ||
    delta.executable_status !== 'non_executable' ||
    canonicalJson(delta.added_tables.map((table) => table.name)) !==
      canonicalJson(expectedTables) ||
    delta.extended_tables.length !== 1 ||
    canonicalJson(
      delta.extended_tables[0]!.added_columns.map((column) => column.name),
    ) !== canonicalJson(['capacity_revision', 'capacity_change_id']) ||
    !delta.extended_tables[0]!.added_checks[0]!.columns.includes(
      'capacity_config_hash',
    ) ||
    deltaHash !==
      domainSeparatedSha256(
        'icarus:workflow-capacity-control-plane-logical-schema-delta:1\n',
        deltaWithoutHash as unknown as JsonValue,
      )
  )
    throw new CapacityControlPlaneContractError(
      'Capacity Logical Schema additive delta drift',
    );
  for (const table of delta.added_tables) {
    keyset(
      Object.keys(table),
      LOGICAL_TABLE_KEYS,
      `logical table ${table.name}`,
    );
    for (const column of table.columns)
      keyset(
        Object.keys(column),
        LOGICAL_COLUMN_KEYS,
        `logical column ${table.name}.${column.name}`,
      );
    keyset(
      Object.keys(table.primary_key),
      LOGICAL_PRIMARY_KEY_KEYS,
      `logical primary key ${table.name}`,
    );
    for (const foreignKey of table.foreign_keys)
      keyset(
        Object.keys(foreignKey),
        LOGICAL_FOREIGN_KEY_KEYS,
        `logical foreign key ${foreignKey.relation_id}`,
      );
    for (const uniqueKey of table.unique_keys)
      keyset(
        Object.keys(uniqueKey),
        LOGICAL_UNIQUE_KEY_KEYS,
        `logical unique key ${uniqueKey.key_id}`,
      );
    for (const check of table.checks)
      keyset(
        Object.keys(check),
        LOGICAL_CHECK_KEYS,
        `logical check ${check.check_id}`,
      );
    for (const index of table.indexes)
      keyset(
        Object.keys(index),
        LOGICAL_INDEX_KEYS,
        `logical index ${index.index_id}`,
      );
  }
  for (const query of delta.query_intents)
    keyset(
      Object.keys(query),
      LOGICAL_QUERY_KEYS,
      `capacity query ${query.query_id}`,
    );
  const queryIds = new Set(delta.query_intents.map((query) => query.query_id));
  const indexIds = new Set(
    delta.added_tables.flatMap((table) =>
      table.indexes.map((index) => index.index_id),
    ),
  );
  for (const query of delta.query_intents)
    if (!indexIds.has(query.required_index_id))
      throw new CapacityControlPlaneContractError(
        `Capacity query lacks additive index intent: ${query.query_id}`,
      );
  for (const table of delta.added_tables)
    for (const index of table.indexes)
      for (const queryId of index.supports_query_ids)
        if (!queryIds.has(queryId))
          throw new CapacityControlPlaneContractError(
            `Capacity index references unknown query: ${queryId}`,
          );
}

function validateCoverage(
  artifacts: Array<[string, ContractArtifactEnvelope]>,
): void {
  const coverage = payloadByFormat<CapacityMarkdownDeltaCoverage>(
    artifacts,
    'icarus.workflow-capacity-control-plane-markdown-delta-coverage/1',
  );
  const expectedCounts = {
    semantic_format: 1,
    command_type: 2,
    permission: 1,
    reason_code: 6,
    denial_code: 11,
    protocol_id: 5,
    logical_table: 4,
    admission_lineage_field: 3,
  };
  for (const entry of coverage.entries) {
    const { entry_hash: entryHash, ...entryWithoutHash } = entry;
    if (
      entryHash !==
      domainSeparatedSha256(
        'icarus:workflow-capacity-markdown-delta-coverage-entry:1\n',
        entryWithoutHash as unknown as JsonValue,
      )
    )
      throw new CapacityControlPlaneContractError(
        `Capacity Markdown delta entry hash drift: ${entry.coverage_id}`,
      );
  }
  const { coverage_hash: coverageHash, ...coverageWithoutHash } = coverage;
  if (
    coverage.prior_g0_9_root_hash !== G0_9_HISTORICAL_ROOT_HASH ||
    coverage.contract_values_without_markdown.length !== 0 ||
    coverage.markdown_values_without_contract.length !== 0 ||
    coverage.contract_value_count !== CAPACITY_MARKDOWN_DELTA_SEEDS.length ||
    coverage.markdown_value_count !== coverage.contract_value_count ||
    canonicalJson(coverage.category_counts) !== canonicalJson(expectedCounts) ||
    coverageHash !==
      domainSeparatedSha256(
        'icarus:workflow-capacity-markdown-delta-coverage:1\n',
        coverageWithoutHash as unknown as JsonValue,
      )
  )
    throw new CapacityControlPlaneContractError(
      'Capacity Markdown delta coverage is incomplete',
    );
}

function rawSha256(bytes: Buffer): Sha256Hash {
  return `sha256:${crypto.createHash('sha256').update(bytes).digest('hex')}`;
}

function validateInventory(
  artifacts: Array<[string, ContractArtifactEnvelope]>,
  checkTree: boolean,
): void {
  const inventory = payloadByFormat<CapacityArtifactInventory>(
    artifacts,
    'icarus.workflow-capacity-control-plane-artifact-inventory/1',
  );
  const expectedClassCounts = {
    historical_root: 1,
    schema: 13,
    catalog: 3,
    protocol: 1,
    logical_schema_delta: 1,
    coverage: 1,
    fixture: 3,
  };
  if (
    inventory.entry_count !== 23 ||
    inventory.entries.length !== inventory.entry_count ||
    inventory.duplicate_paths.length !== 0 ||
    inventory.missing_paths.length !== 0 ||
    canonicalJson(inventory.class_counts) !== canonicalJson(expectedClassCounts)
  )
    throw new CapacityControlPlaneContractError(
      'Capacity artifact inventory is incomplete',
    );
  const { inventory_hash: inventoryHash, ...inventoryWithoutHash } = inventory;
  if (
    inventoryHash !==
    domainSeparatedSha256(
      'icarus:workflow-capacity-control-plane-artifact-inventory:1\n',
      inventoryWithoutHash as unknown as JsonValue,
    )
  )
    throw new CapacityControlPlaneContractError(
      'Capacity artifact inventory semantic hash drift',
    );
  if (checkTree) {
    for (const entry of inventory.entries) {
      const bytes = fs.readFileSync(path.resolve(repoRoot, entry.path));
      if (rawSha256(bytes) !== entry.raw_sha256)
        throw new CapacityControlPlaneContractError(
          `Capacity inventory raw hash mismatch: ${entry.path}`,
        );
      if (
        parseContractArtifactEnvelope(strictParseJsonBytes(bytes)).hash !==
        entry.semantic_hash
      )
        throw new CapacityControlPlaneContractError(
          `Capacity inventory semantic hash mismatch: ${entry.path}`,
        );
    }
  }
}

function validateFixtures(): void {
  if (
    CAPACITY_CONTROL_PLANE_POSITIVE_CASES.length !== 7 ||
    CAPACITY_CONTROL_PLANE_NEGATIVE_CASES.length !== 23 ||
    CAPACITY_CONTROL_PLANE_FAULT_CASES.length !== 13
  )
    throw new CapacityControlPlaneContractError(
      'Capacity fixture coverage count drift',
    );
  const cases = [
    ...CAPACITY_CONTROL_PLANE_POSITIVE_CASES,
    ...CAPACITY_CONTROL_PLANE_NEGATIVE_CASES,
    ...CAPACITY_CONTROL_PLANE_FAULT_CASES,
  ];
  if (
    new Set(cases.map((candidate) => candidate.case_id)).size !== cases.length
  )
    throw new CapacityControlPlaneContractError(
      'Duplicate Capacity fixture id',
    );
  for (const candidate of cases) {
    const actual = evaluateCapacityControlPlaneCase(candidate);
    if (actual !== candidate.expected_result)
      throw new CapacityControlPlaneContractError(
        `Capacity fixture oracle drift: ${candidate.case_id}: ${actual}`,
      );
  }
}

function validateGateReview(
  artifacts: Array<[string, ContractArtifactEnvelope]>,
): void {
  const review = payloadByFormat<CapacityGateReview>(
    artifacts,
    'icarus.workflow-capacity-control-plane-gate-review/1',
  );
  const coverage = payloadByFormat<CapacityMarkdownDeltaCoverage>(
    artifacts,
    'icarus.workflow-capacity-control-plane-markdown-delta-coverage/1',
  );
  const inventory = payloadByFormat<CapacityArtifactInventory>(
    artifacts,
    'icarus.workflow-capacity-control-plane-artifact-inventory/1',
  );
  const evidenceHashes = [
    ...CAPACITY_CONTROL_PLANE_ARTIFACT_DESCRIPTORS.filter(
      (descriptor) =>
        descriptor.artifact_kind !== 'inventory' &&
        descriptor.artifact_kind !== 'gate_review',
    )
      .sort((left, right) =>
        left.artifact_path < right.artifact_path
          ? -1
          : left.artifact_path > right.artifact_path
            ? 1
            : 0,
      )
      .map(
        (descriptor) =>
          artifactByFormat(artifacts, descriptor.artifact_format).hash,
      ),
    artifactByFormat(
      artifacts,
      'icarus.workflow-capacity-control-plane-artifact-inventory/1',
    ).hash,
  ];
  const expectedReview = buildCapacityGateReview(
    coverage,
    inventory,
    evidenceHashes,
  );
  if (
    review.decision !== 'pass' ||
    review.prior_g0_9_root_hash !== G0_9_HISTORICAL_ROOT_HASH ||
    review.exit_criteria.length !== 10 ||
    canonicalJson(review.historical_identity_hashes as JsonValue) !==
      canonicalJson({ ...G0_10_HISTORICAL_IDENTITIES }) ||
    review.status_proof.g0_status !== 'DONE' ||
    review.status_proof.i11_status !== 'DONE' ||
    review.status_proof.g1_status !== 'READY' ||
    review.status_proof.g2_status !== 'READY' ||
    review.status_proof.r014_status !== 'CLOSED' ||
    review.status_proof.executable_ddl_status !== 'absent' ||
    review.status_proof.golden_semantic_review_status !== 'absent' ||
    review.status_proof.golden_seal_status !== 'not_run' ||
    canonicalJson(review as unknown as JsonValue) !==
      canonicalJson(expectedReview as unknown as JsonValue)
  )
    throw new CapacityControlPlaneContractError('G0.10 Gate review drift');
}

function validateDomainCatalog(
  artifacts: Array<[string, ContractArtifactEnvelope]>,
  manifest: ContractArtifactEnvelope,
): void {
  const domain = artifactByFormat(
    artifacts,
    'icarus.workflow-capacity-control-plane-domain-separators/1',
  );
  const entries = domain.payload.entries;
  if (!Array.isArray(entries))
    throw new CapacityControlPlaneContractError(
      'Capacity domain registry missing',
    );
  const actual = new Map<string, string>();
  for (const entry of entries) {
    assertJsonObject(entry);
    if (actual.has(String(entry.format)))
      throw new CapacityControlPlaneContractError(
        `Duplicate Capacity domain format: ${entry.format}`,
      );
    actual.set(String(entry.format), String(entry.domain_separator));
  }
  const expected = new Map([
    ...artifacts.map(
      ([, artifact]) => [artifact.format, artifact.domain_separator] as const,
    ),
    [manifest.format, manifest.domain_separator] as const,
    [
      'icarus.deployment-runtime-capacity-publication/1',
      'icarus:deployment-runtime-capacity-publication:1\n',
    ] as const,
    [
      'icarus.capacity-admin-command-request/1',
      'icarus:capacity-admin-command-request:1\n',
    ] as const,
  ]);
  if (
    actual.size !== expected.size ||
    [...expected].some(
      ([format, domainValue]) => actual.get(format) !== domainValue,
    )
  )
    throw new CapacityControlPlaneContractError(
      'Capacity domain coverage drift',
    );
}

function listAddendumFiles(): string[] {
  const root = absoluteContractPath(addendumRoot);
  if (!fs.existsSync(root)) return [];
  const files: string[] = [];
  const visit = (directory: string): void => {
    for (const name of fs.readdirSync(directory).sort()) {
      const absolute = path.join(directory, name);
      const stat = fs.lstatSync(absolute);
      if (stat.isSymbolicLink())
        throw new CapacityControlPlaneContractError(
          `Capacity addendum contains symlink: ${absolute}`,
        );
      if (stat.isDirectory()) visit(absolute);
      else if (stat.isFile())
        files.push(
          path.relative(contractsRoot, absolute).split(path.sep).join('/'),
        );
      else
        throw new CapacityControlPlaneContractError(
          `Capacity addendum contains unsupported entry: ${absolute}`,
        );
    }
  };
  visit(root);
  return files.sort();
}

function validateBoundaries(
  artifacts: Array<[string, ContractArtifactEnvelope]>,
  checkTree: boolean,
): void {
  assertHistoricalG0_9Conformance();
  if (checkTree) {
    const expected = artifacts
      .map(([relativePath]) => relativePath)
      .filter((relativePath) => relativePath.startsWith(`${addendumRoot}/`))
      .concat(manifestPath)
      .sort();
    if (canonicalJson(listAddendumFiles()) !== canonicalJson(expected))
      throw new CapacityControlPlaneContractError(
        'Capacity addendum generated tree drift',
      );
  }
  const sealed = fs.readdirSync(absoluteContractPath('conformance/sealed'));
  const forbiddenPaths = [
    'store/runtime-store.ts',
    'store/schema/workflow-runtime-schema-v1.sql',
    'runtime/capacity-admin.ts',
    'runtime/capacity-publication.ts',
    'runtime/scheduler.ts',
    'projection/runtime-center-api.ts',
    'projection/runtime-center-renderer',
  ];
  if (
    sealed.length !== 1 ||
    sealed[0] !== '.gitkeep' ||
    forbiddenPaths.some((relativePath) =>
      fs.existsSync(path.join(workflowRuntimeRoot, relativePath)),
    ) ||
    fs.existsSync(
      path.join(
        repoRoot,
        'data/workflow-runtime/workflow-runtime-capacity.json',
      ),
    )
  )
    throw new CapacityControlPlaneContractError(
      'G0.10 forbidden implementation boundary crossed',
    );
  const packageJson = strictParseJsonBytes(
    fs.readFileSync(path.join(repoRoot, 'package.json')),
  );
  assertJsonObject(packageJson);
  const scripts = packageJson.scripts;
  assertJsonObject(scripts);
  if (
    scripts['test:g0.9'] !==
      'vitest run src/workflow-runtime/contracts/g0-conformance.test.ts' ||
    scripts['test:g0.10'] !==
      'vitest run src/workflow-runtime/contracts/capacity-control-plane.test.ts' ||
    typeof scripts['test:g0'] !== 'string' ||
    !scripts['test:g0'].includes('capacity-control-plane.test.ts')
  )
    throw new CapacityControlPlaneContractError(
      'Current G0.10 conformance entrypoint missing',
    );
}

function validateManifest(
  artifacts: Array<[string, ContractArtifactEnvelope]>,
  manifest: ContractArtifactEnvelope,
): void {
  if (
    manifest.payload.prior_g0_9_root_hash !== G0_9_HISTORICAL_ROOT_HASH ||
    manifest.payload.capacity_schema_hash !== CAPACITY_SCHEMA_HISTORICAL_HASH ||
    manifest.payload.capacity_baseline_hash !==
      CAPACITY_BASELINE_HISTORICAL_HASH ||
    canonicalJson(manifest.payload.historical_identity_hashes) !==
      canonicalJson({ ...G0_10_HISTORICAL_IDENTITIES }) ||
    manifest.payload.g0_status !== 'DONE' ||
    manifest.payload.g1_status !== 'READY' ||
    manifest.payload.g2_status !== 'READY' ||
    manifest.payload.r014_status !== 'CLOSED'
  )
    throw new CapacityControlPlaneContractError('G0.10 manifest status drift');
  const regenerated = buildManifest(artifacts);
  if (canonicalJson(regenerated) !== canonicalJson(manifest))
    throw new CapacityControlPlaneContractError(
      'G0.10 manifest is not deterministic',
    );
}

function validatePack(
  artifacts: Array<[string, ContractArtifactEnvelope]>,
  manifest: ContractArtifactEnvelope,
  checkTree: boolean,
): void {
  for (const [, artifact] of artifacts) parseContractArtifactEnvelope(artifact);
  validateSchemas(artifacts);
  validateCatalogs(artifacts);
  validateProtocol(artifacts);
  validateLogicalDelta(artifacts);
  validateCoverage(artifacts);
  validateInventory(artifacts, checkTree);
  validateFixtures();
  validateGateReview(artifacts);
  validateDomainCatalog(artifacts, manifest);
  validateBoundaries(artifacts, checkTree);
  validateManifest(artifacts, manifest);
}

export function checkHistoricalG0_9Conformance(): ContractArtifactEnvelope {
  return assertHistoricalG0_9Conformance();
}

export function generateContractPackCapacityControlPlane(): ContractArtifactEnvelope {
  const artifacts = expectedArtifacts();
  const manifest = buildManifest(artifacts);
  validatePack(artifacts, manifest, false);
  for (const [relativePath, artifact] of artifacts)
    writeAtomic(relativePath, renderJson(artifact));
  writeAtomic(manifestPath, renderJson(manifest));
  validatePack(artifacts, manifest, true);
  return manifest;
}

export function checkContractPackCapacityControlPlane(): ContractArtifactEnvelope {
  const artifacts = expectedArtifacts();
  const manifest = buildManifest(artifacts);
  validatePack(artifacts, manifest, true);
  for (const [relativePath, artifact] of artifacts)
    assertExpectedBytes(relativePath, renderJson(artifact));
  assertExpectedBytes(manifestPath, renderJson(manifest));
  return manifest;
}

export function buildCapacityControlPlaneExpectedArtifactsForTest(): Array<
  [string, ContractArtifactEnvelope]
> {
  return expectedArtifacts();
}

export function evaluateCapacityControlPlaneFixtureForTest(
  candidate:
    | (typeof CAPACITY_CONTROL_PLANE_POSITIVE_CASES)[number]
    | {
        case_id: string;
        area: (typeof CAPACITY_CONTROL_PLANE_NEGATIVE_CASES)[number]['area'];
        scenario: string;
        expected_result: string;
        expected_head_effect: 'unchanged' | 'pending_prepared' | 'committed';
        assertion: string;
      },
): string {
  return evaluateCapacityControlPlaneCase(candidate);
}

export const CAPACITY_CONTROL_PLANE_MANIFEST_PATH = manifestPath;
export const CAPACITY_CONTROL_PLANE_ADDENDUM_ROOT = addendumRoot;
export const CAPACITY_CONTROL_PLANE_INVENTORY_CLASSES =
  CAPACITY_INVENTORY_CLASSES;
export const CAPACITY_CONTROL_PLANE_MARKDOWN_CATEGORIES =
  CAPACITY_MARKDOWN_DELTA_CATEGORIES;
export const CAPACITY_CONTROL_PLANE_ARTIFACT_COUNT =
  CAPACITY_CONTROL_PLANE_ARTIFACT_DESCRIPTORS.length + 2;
