import fs from 'fs';
import path from 'path';

import {
  CATALOG_PROTOCOL_ARTIFACT_DESCRIPTORS,
  buildCatalogProtocolArtifact,
  buildCatalogProtocolSemanticArtifacts,
} from './catalog-protocol-artifacts.js';
import {
  CATALOG_PROTOCOL_NEGATIVE_CASES,
  CATALOG_PROTOCOL_POSITIVE_CASES,
  type CatalogProtocolMutation,
} from './catalog-protocol-fixtures.js';
import {
  CATALOG_PROTOCOL_CLOSED_UNIONS,
  RUNTIME_COMMAND_DENIAL_CODES,
  RUNTIME_FACT_KINDS,
  RUNTIME_PERMISSION_CODES,
  WORKFLOW_COMPILER_ERROR_CODES,
} from './catalog-protocol-types.js';
import {
  PROTOCOL_TABLE_CLOSED_UNIONS,
  RUNTIME_COMMAND_PROTOCOL_ENTRIES,
  RUNTIME_STATE_MACHINES,
  RUN_TRANSACTION_PROTOCOL_ENTRIES,
} from './protocol-table-types.js';
import { calculateArtifactHash, canonicalJson } from './hash.js';
import { parseContractArtifactEnvelope } from './artifact.js';
import {
  assertJsonObject,
  strictParseJson,
  strictParseJsonBytes,
} from './strict-json.js';
import type {
  ContractArtifactEnvelope,
  JsonObject,
  JsonValue,
} from './types.js';

const contractsRoot = import.meta.dirname;
const foundationManifestHash =
  'sha256:e85b654581c036f8129677d7443a0704ebc8b8fbe87907b842aaefe1501e637d';
const closedSchemaManifestHash =
  'sha256:c5ea281d64480787322e8b6ef619b2f90784084d87ba4373c94288ed5e7aa3a8';
const manifestPath = 'contract-pack-catalog-protocols.json';
const positiveCasesPath = 'conformance/catalog-protocols/positive-cases.json';
const negativeCasesPath = 'conformance/catalog-protocols/negative-cases.json';
const domainCatalogPath = 'catalogs/catalog-protocol-domain-separators.json';

const futureReservedDirectories = [
  'safety',
  'sqlite',
  'conformance/draft',
  'conformance/sealed',
] as const;

export class CatalogProtocolContractError extends Error {
  readonly code = 'catalog_protocol_contract_drift';

  constructor(message: string) {
    super(message);
    this.name = 'CatalogProtocolContractError';
  }
}

function asciiCompare(left: string, right: string): number {
  return left < right ? -1 : left > right ? 1 : 0;
}

function absoluteContractPath(relativePath: string): string {
  const absolute = path.resolve(contractsRoot, relativePath);
  if (!absolute.startsWith(`${contractsRoot}${path.sep}`)) {
    throw new Error(`Contract path escapes root: ${relativePath}`);
  }
  return absolute;
}

function renderJson(value: JsonValue): string {
  return `${JSON.stringify(value, null, 2)}\n`;
}

function writeAtomic(relativePath: string, value: JsonValue): void {
  const file = absoluteContractPath(relativePath);
  fs.mkdirSync(path.dirname(file), { recursive: true });
  const temporary = `${file}.tmp-${process.pid}`;
  fs.writeFileSync(temporary, renderJson(value), {
    encoding: 'utf8',
    mode: 0o644,
  });
  fs.renameSync(temporary, file);
}

function readArtifact(relativePath: string): ContractArtifactEnvelope {
  const absolute = absoluteContractPath(relativePath);
  if (!fs.lstatSync(absolute).isFile()) {
    throw new Error(`Contract path is not a regular file: ${relativePath}`);
  }
  return parseContractArtifactEnvelope(
    strictParseJsonBytes(fs.readFileSync(absolute)),
  );
}

function assertExpectedBytes(
  relativePath: string,
  expected: ContractArtifactEnvelope,
): void {
  const actual = fs.readFileSync(absoluteContractPath(relativePath), 'utf8');
  if (actual !== renderJson(expected)) {
    throw new Error(
      `${relativePath} is not generated byte-for-byte; run npm run contracts:generate`,
    );
  }
}

function artifactDescriptor(
  artifactPath: string,
  artifact: ContractArtifactEnvelope,
): JsonObject {
  return {
    path: artifactPath,
    format: artifact.format,
    ref: artifact.ref,
    version: artifact.version,
    domain_separator: artifact.domain_separator,
    hash: artifact.hash,
  };
}

function buildFixtureArtifacts(
  semanticArtifacts: Array<[string, ContractArtifactEnvelope]>,
): Array<[string, ContractArtifactEnvelope]> {
  const hashes = new Map(
    semanticArtifacts.map(([, artifact]) => [artifact.format, artifact.hash]),
  );
  return [
    [
      positiveCasesPath,
      buildCatalogProtocolArtifact(
        'icarus.workflow-catalog-protocol-positive-cases/1',
        'icarus.workflow-catalog-protocol-positive-cases',
        'icarus:workflow-catalog-protocol-positive-cases:1\n',
        {
          cases: CATALOG_PROTOCOL_POSITIVE_CASES.map((testCase) => ({
            ...testCase,
            expected_artifact_hash: hashes.get(testCase.artifact_format),
          })),
        },
      ),
    ],
    [
      negativeCasesPath,
      buildCatalogProtocolArtifact(
        'icarus.workflow-catalog-protocol-negative-cases/1',
        'icarus.workflow-catalog-protocol-negative-cases',
        'icarus:workflow-catalog-protocol-negative-cases:1\n',
        { cases: CATALOG_PROTOCOL_NEGATIVE_CASES },
      ),
    ],
  ];
}

function buildDomainCatalog(
  priorArtifacts: Array<[string, ContractArtifactEnvelope]>,
): ContractArtifactEnvelope {
  const entries = [
    ...priorArtifacts.map(([, artifact]) => ({
      format: artifact.format,
      domain_separator: artifact.domain_separator,
    })),
    {
      format: 'icarus.workflow-catalog-protocol-domain-separators/1',
      domain_separator:
        'icarus:workflow-catalog-protocol-domain-separators:1\n',
    },
    {
      format: 'icarus.workflow-contract-pack-catalog-protocols/1',
      domain_separator: 'icarus:workflow-contract-pack-catalog-protocols:1\n',
    },
  ].sort((left, right) => asciiCompare(left.format, right.format));
  return buildCatalogProtocolArtifact(
    'icarus.workflow-catalog-protocol-domain-separators/1',
    'icarus.workflow-catalog-protocol-domain-separators',
    'icarus:workflow-catalog-protocol-domain-separators:1\n',
    { entries },
  );
}

function buildManifest(
  artifacts: Array<[string, ContractArtifactEnvelope]>,
): ContractArtifactEnvelope {
  return buildCatalogProtocolArtifact(
    'icarus.workflow-contract-pack-catalog-protocols/1',
    'icarus.workflow-contract-pack-catalog-protocols',
    'icarus:workflow-contract-pack-catalog-protocols:1\n',
    {
      gate: 'G0.4',
      status: 'catalogs_and_protocol_tables',
      run_protocol_major: 1,
      foundation_manifest_hash: foundationManifestHash,
      closed_schema_manifest_hash: closedSchemaManifestHash,
      compiler_error_code_count: WORKFLOW_COMPILER_ERROR_CODES.length,
      fact_kind_count: RUNTIME_FACT_KINDS.length,
      event_type_count:
        RUNTIME_FACT_KINDS.length +
        CATALOG_PROTOCOL_CLOSED_UNIONS.audit_event_types.length,
      permission_count: RUNTIME_PERMISSION_CODES.length,
      command_reason_count:
        CATALOG_PROTOCOL_CLOSED_UNIONS.command_reason_codes.length,
      command_denial_count: RUNTIME_COMMAND_DENIAL_CODES.length,
      command_count: RUNTIME_COMMAND_PROTOCOL_ENTRIES.length,
      state_machine_count: RUNTIME_STATE_MACHINES.length,
      transaction_protocol_count: RUN_TRANSACTION_PROTOCOL_ENTRIES.length,
      positive_case_count: CATALOG_PROTOCOL_POSITIVE_CASES.length,
      negative_case_count: CATALOG_PROTOCOL_NEGATIVE_CASES.length,
      artifacts: artifacts
        .map(([artifactPath, artifact]) =>
          artifactDescriptor(artifactPath, artifact),
        )
        .sort((left, right) =>
          asciiCompare(String(left.path), String(right.path)),
        ),
      future_reserved_directories: [...futureReservedDirectories],
    },
  );
}

function expectedArtifacts(): Array<[string, ContractArtifactEnvelope]> {
  const semanticArtifacts = buildCatalogProtocolSemanticArtifacts();
  const fixtures = buildFixtureArtifacts(semanticArtifacts);
  const prior = [...semanticArtifacts, ...fixtures];
  return [...prior, [domainCatalogPath, buildDomainCatalog(prior)]];
}

function sameValues(
  actual: readonly string[],
  expected: readonly string[],
): boolean {
  return (
    [...actual].sort(asciiCompare).join('\n') ===
    [...expected].sort(asciiCompare).join('\n')
  );
}

function stringValues(value: JsonValue): string[] {
  if (
    !Array.isArray(value) ||
    value.some((entry) => typeof entry !== 'string')
  ) {
    throw new CatalogProtocolContractError('Expected a closed string array');
  }
  return value as string[];
}

function entriesFrom(artifact: ContractArtifactEnvelope): JsonObject[] {
  const entries = artifact.payload.entries;
  if (!Array.isArray(entries)) {
    throw new CatalogProtocolContractError(
      `${artifact.format} entries must be an array`,
    );
  }
  return entries.map((entry) => {
    assertJsonObject(entry);
    return entry;
  });
}

function validateCrossCatalogConformance(
  byFormat: Map<string, ContractArtifactEnvelope>,
): void {
  const errorCatalog = byFormat.get('icarus.workflow-compiler-error-catalog/1');
  const factCatalog = byFormat.get('icarus.workflow-runtime-fact-catalog/1');
  const eventCatalog = byFormat.get('icarus.workflow-runtime-event-catalog/1');
  const permissionCatalog = byFormat.get(
    'icarus.workflow-runtime-permission-catalog/1',
  );
  const reasonCatalog = byFormat.get(
    'icarus.workflow-runtime-command-reason-catalog/1',
  );
  const denialCatalog = byFormat.get(
    'icarus.workflow-runtime-command-denial-catalog/1',
  );
  const stateTables = byFormat.get(
    'icarus.workflow-runtime-state-transition-tables/1',
  );
  const commandTable = byFormat.get(
    'icarus.workflow-runtime-command-protocol-table/1',
  );
  const transactionTable = byFormat.get(
    'icarus.workflow-run-transaction-protocol-table/1',
  );
  if (
    !errorCatalog ||
    !factCatalog ||
    !eventCatalog ||
    !permissionCatalog ||
    !reasonCatalog ||
    !denialCatalog ||
    !stateTables ||
    !commandTable ||
    !transactionTable
  ) {
    throw new CatalogProtocolContractError('G0.4 semantic artifact is missing');
  }

  assertJsonObject(errorCatalog.payload.entries);
  if (
    !sameValues(
      Object.keys(errorCatalog.payload.entries),
      WORKFLOW_COMPILER_ERROR_CODES,
    )
  ) {
    throw new CatalogProtocolContractError('Compiler error coverage drift');
  }

  const factEntries = entriesFrom(factCatalog);
  const factKinds = factEntries.map((entry) => String(entry.fact_kind));
  if (!sameValues(factKinds, RUNTIME_FACT_KINDS)) {
    throw new CatalogProtocolContractError('Runtime Fact coverage drift');
  }
  const ranks = factEntries.map((entry) => Number(entry.fact_kind_rank));
  if (
    ranks.some((rank) => !Number.isSafeInteger(rank) || rank < 0) ||
    new Set(ranks).size !== ranks.length
  ) {
    throw new CatalogProtocolContractError(
      'Runtime Fact ranks must be unique non-negative safe integers',
    );
  }

  const eventEntries = entriesFrom(eventCatalog);
  const factBacked = eventEntries.filter(
    (entry) => entry.event_class === 'fact_backed',
  );
  if (
    factBacked.length !== RUNTIME_FACT_KINDS.length ||
    factBacked.some(
      (entry) =>
        entry.event_type !== entry.fact_kind ||
        !RUNTIME_FACT_KINDS.includes(entry.fact_kind as never),
    )
  ) {
    throw new CatalogProtocolContractError('Fact/Event atomic mapping drift');
  }
  if (
    eventEntries.some(
      (entry) =>
        (entry.event_class === 'audit_only' && entry.fact_kind !== null) ||
        (entry.event_class !== 'audit_only' &&
          entry.event_class !== 'fact_backed'),
    )
  ) {
    throw new CatalogProtocolContractError('Runtime Event class drift');
  }

  if (
    !sameValues(
      entriesFrom(permissionCatalog).map((entry) => String(entry.permission)),
      RUNTIME_PERMISSION_CODES,
    )
  ) {
    throw new CatalogProtocolContractError('Permission coverage drift');
  }
  if (
    !sameValues(
      entriesFrom(reasonCatalog).map((entry) => String(entry.reason_code)),
      CATALOG_PROTOCOL_CLOSED_UNIONS.command_reason_codes,
    )
  ) {
    throw new CatalogProtocolContractError('Command reason coverage drift');
  }
  if (
    !sameValues(
      entriesFrom(denialCatalog).map((entry) => String(entry.denial_code)),
      RUNTIME_COMMAND_DENIAL_CODES,
    )
  ) {
    throw new CatalogProtocolContractError('Command denial coverage drift');
  }

  const machines = stateTables.payload.machines;
  if (!Array.isArray(machines)) {
    throw new CatalogProtocolContractError('State machines must be an array');
  }
  const machineIds = new Set<string>();
  for (const machineValue of machines) {
    assertJsonObject(machineValue);
    const machineId = String(machineValue.machine_id);
    if (machineIds.has(machineId)) {
      throw new CatalogProtocolContractError(
        `Duplicate state machine ${machineId}`,
      );
    }
    machineIds.add(machineId);
    const machineValues = machineValue.values;
    const transitions = machineValue.transitions;
    if (!Array.isArray(machineValues) || !Array.isArray(transitions)) {
      throw new CatalogProtocolContractError(
        `State machine ${machineId} has an invalid shape`,
      );
    }
    const valuesByName = new Map<string, boolean>();
    for (const stateValue of machineValues) {
      assertJsonObject(stateValue);
      valuesByName.set(String(stateValue.value), Boolean(stateValue.terminal));
    }
    for (const transitionValue of transitions) {
      assertJsonObject(transitionValue);
      const from = String(transitionValue.from);
      const to = String(transitionValue.to);
      if (!valuesByName.has(from) || !valuesByName.has(to)) {
        throw new CatalogProtocolContractError(
          `State transition ${machineId}:${from}->${to} has an unknown endpoint`,
        );
      }
      if (valuesByName.get(from)) {
        throw new CatalogProtocolContractError(
          `Terminal state ${machineId}:${from} cannot transition`,
        );
      }
    }
  }

  const commandEntries = entriesFrom(commandTable);
  if (
    !sameValues(
      commandEntries.map((entry) => String(entry.command_type)),
      CATALOG_PROTOCOL_CLOSED_UNIONS.command_types,
    )
  ) {
    throw new CatalogProtocolContractError('Runtime Command coverage drift');
  }
  for (const entry of commandEntries) {
    if (
      !PROTOCOL_TABLE_CLOSED_UNIONS.command_target_kinds.includes(
        entry.target_kind as never,
      ) ||
      !stringValues(entry.allowed_reason_codes).every((reason) =>
        CATALOG_PROTOCOL_CLOSED_UNIONS.command_reason_codes.includes(
          reason as never,
        ),
      ) ||
      !sameValues(
        stringValues(entry.denial_codes),
        RUNTIME_COMMAND_DENIAL_CODES,
      )
    ) {
      throw new CatalogProtocolContractError(
        `Runtime Command mapping drift for ${String(entry.command_type)}`,
      );
    }
  }

  const transactionEntries = entriesFrom(transactionTable);
  if (
    !sameValues(
      transactionEntries.map((entry) => String(entry.transaction_id)),
      PROTOCOL_TABLE_CLOSED_UNIONS.transaction_protocol_ids,
    ) ||
    transactionEntries.some(
      (entry) => entry.transaction_mode !== 'begin_immediate',
    )
  ) {
    throw new CatalogProtocolContractError(
      'Transaction protocol coverage drift',
    );
  }
}

function clonePayload(payload: JsonObject): JsonObject {
  const clone = strictParseJson(JSON.stringify(payload));
  assertJsonObject(clone);
  return clone;
}

function pointerTokens(pointer: string): string[] {
  if (!pointer.startsWith('/')) {
    throw new Error(`Fixture JSON pointer must be absolute: ${pointer}`);
  }
  return pointer
    .slice(1)
    .split('/')
    .map((token) => token.replaceAll('~1', '/').replaceAll('~0', '~'));
}

function applyMutation(
  payload: JsonObject,
  mutation: CatalogProtocolMutation,
): void {
  const tokens = pointerTokens(mutation.pointer);
  const finalToken = tokens.pop();
  if (finalToken === undefined)
    throw new Error('Fixture pointer cannot be empty');
  let current: JsonValue = payload;
  for (const token of tokens) {
    if (Array.isArray(current)) {
      current = current[Number(token)]!;
    } else {
      assertJsonObject(current);
      current = current[token]!;
    }
  }
  if (mutation.operation === 'append') {
    if (Array.isArray(current)) {
      const target = current[Number(finalToken)];
      if (!Array.isArray(target))
        throw new Error('Append target is not an array');
      target.push(mutation.value);
    } else {
      assertJsonObject(current);
      const target = current[finalToken];
      if (!Array.isArray(target))
        throw new Error('Append target is not an array');
      target.push(mutation.value);
    }
    return;
  }
  if (Array.isArray(current)) {
    const index = Number(finalToken);
    if (mutation.operation === 'remove') current.splice(index, 1);
    else current[index] = mutation.value;
    return;
  }
  assertJsonObject(current);
  if (mutation.operation === 'remove') delete current[finalToken];
  else current[finalToken] = mutation.value;
}

export function validateCatalogProtocolPayload(
  format: string,
  payload: JsonObject,
): void {
  const expected = buildCatalogProtocolSemanticArtifacts().find(
    ([, artifact]) => artifact.format === format,
  )?.[1];
  if (!expected) {
    throw new CatalogProtocolContractError(`Unknown semantic format ${format}`);
  }
  if (canonicalJson(payload) !== canonicalJson(expected.payload)) {
    throw new CatalogProtocolContractError(`${format} semantic payload drift`);
  }
}

function validateFixtures(
  semanticArtifacts: Array<[string, ContractArtifactEnvelope]>,
): void {
  const byFormat = new Map(
    semanticArtifacts.map(([, artifact]) => [artifact.format, artifact]),
  );
  for (const testCase of CATALOG_PROTOCOL_POSITIVE_CASES) {
    const artifact = byFormat.get(testCase.artifact_format);
    if (!artifact) {
      throw new Error(`Unknown positive artifact ${testCase.artifact_format}`);
    }
    validateCatalogProtocolPayload(artifact.format, artifact.payload);
  }
  for (const testCase of CATALOG_PROTOCOL_NEGATIVE_CASES) {
    const artifact = byFormat.get(testCase.artifact_format);
    if (!artifact) {
      throw new Error(`Unknown negative artifact ${testCase.artifact_format}`);
    }
    const mutated = clonePayload(artifact.payload);
    applyMutation(mutated, testCase.mutation);
    try {
      validateCatalogProtocolPayload(artifact.format, mutated);
      throw new Error(`Negative fixture ${testCase.case_id} was accepted`);
    } catch (error) {
      if (
        !(error instanceof CatalogProtocolContractError) ||
        error.code !== testCase.expected_code
      ) {
        throw error;
      }
    }
  }
}

function validateDomainCatalog(
  artifacts: Array<[string, ContractArtifactEnvelope]>,
  manifest: ContractArtifactEnvelope,
): void {
  const catalog = artifacts.find(
    ([artifactPath]) => artifactPath === domainCatalogPath,
  )?.[1];
  if (!catalog || !Array.isArray(catalog.payload.entries)) {
    throw new Error('G0.4 domain catalog is missing');
  }
  const expected = [...artifacts.map(([, artifact]) => artifact), manifest];
  if (catalog.payload.entries.length !== expected.length) {
    throw new Error('G0.4 domain catalog coverage drift');
  }
  const seenFormats = new Set<string>();
  const seenDomains = new Set<string>();
  for (const entryValue of catalog.payload.entries) {
    assertJsonObject(entryValue);
    if (
      typeof entryValue.format !== 'string' ||
      typeof entryValue.domain_separator !== 'string' ||
      Object.keys(entryValue).sort().join(',') !== 'domain_separator,format' ||
      seenFormats.has(entryValue.format) ||
      seenDomains.has(entryValue.domain_separator)
    ) {
      throw new Error('G0.4 domain entries must be closed and one-to-one');
    }
    seenFormats.add(entryValue.format);
    seenDomains.add(entryValue.domain_separator);
  }
  for (const artifact of expected) {
    const entry = catalog.payload.entries.find((candidate) => {
      assertJsonObject(candidate);
      return candidate.format === artifact.format;
    });
    assertJsonObject(entry);
    if (entry.domain_separator !== artifact.domain_separator) {
      throw new Error(`G0.4 domain drift for ${artifact.format}`);
    }
  }
}

function validateDirectoryBoundaries(): void {
  const expectedCatalogFiles = [
    'foundation-domain-separators.json',
    'closed-schema-domain-separators.json',
    'catalog-protocol-domain-separators.json',
    ...CATALOG_PROTOCOL_ARTIFACT_DESCRIPTORS.filter(
      (descriptor) => descriptor.artifact_kind === 'catalog',
    ).map((descriptor) => path.basename(descriptor.artifact_path)),
  ].sort(asciiCompare);
  const actualCatalogFiles = fs
    .readdirSync(absoluteContractPath('catalogs'))
    .sort(asciiCompare);
  if (actualCatalogFiles.join('\n') !== expectedCatalogFiles.join('\n')) {
    throw new Error(
      'Catalog directory contains missing or out-of-slice artifacts',
    );
  }
  const expectedProtocolFiles = CATALOG_PROTOCOL_ARTIFACT_DESCRIPTORS.filter(
    (descriptor) => descriptor.artifact_kind === 'protocol_table',
  )
    .map((descriptor) => path.basename(descriptor.artifact_path))
    .sort(asciiCompare);
  const actualProtocolFiles = fs
    .readdirSync(absoluteContractPath('protocols'))
    .sort(asciiCompare);
  if (actualProtocolFiles.join('\n') !== expectedProtocolFiles.join('\n')) {
    throw new Error(
      'Protocol directory contains missing or out-of-slice artifacts',
    );
  }
  const fixtureFiles = fs
    .readdirSync(absoluteContractPath('conformance/catalog-protocols'))
    .sort(asciiCompare);
  if (fixtureFiles.join('\n') !== 'negative-cases.json\npositive-cases.json') {
    throw new Error('G0.4 conformance fixture directory boundary drift');
  }
  for (const directory of futureReservedDirectories) {
    const entries = fs
      .readdirSync(absoluteContractPath(directory))
      .sort(asciiCompare);
    if (entries.length !== 1 || entries[0] !== '.gitkeep') {
      throw new Error(`Future Gate directory contains artifacts: ${directory}`);
    }
  }
}

function validatePriorPackIdentity(): void {
  const foundation = readArtifact('contract-pack-foundation.json');
  const closedSchemas = readArtifact('contract-pack-closed-schemas.json');
  if (foundation.hash !== foundationManifestHash) {
    throw new Error('G0.2 foundation manifest changed during G0.4');
  }
  if (closedSchemas.hash !== closedSchemaManifestHash) {
    throw new Error('G0.3 closed-schema manifest changed during G0.4');
  }
}

function validateCompletePack(
  artifacts: Array<[string, ContractArtifactEnvelope]>,
  manifest: ContractArtifactEnvelope,
): void {
  const semanticArtifacts = artifacts.filter(([artifactPath]) =>
    CATALOG_PROTOCOL_ARTIFACT_DESCRIPTORS.some(
      (descriptor) => descriptor.artifact_path === artifactPath,
    ),
  );
  const byFormat = new Map(
    semanticArtifacts.map(([, artifact]) => [artifact.format, artifact]),
  );
  if (byFormat.size !== CATALOG_PROTOCOL_ARTIFACT_DESCRIPTORS.length) {
    throw new CatalogProtocolContractError('G0.4 format coverage drift');
  }
  for (const [, artifact] of semanticArtifacts) {
    if (artifact.hash !== calculateArtifactHash(artifact)) {
      throw new CatalogProtocolContractError(`${artifact.format} hash drift`);
    }
    validateCatalogProtocolPayload(artifact.format, artifact.payload);
  }
  validateCrossCatalogConformance(byFormat);
  validateFixtures(semanticArtifacts);
  validateDomainCatalog(artifacts, manifest);
  validateDirectoryBoundaries();
  validatePriorPackIdentity();
}

export function generateContractPackCatalogProtocols(): ContractArtifactEnvelope {
  const artifacts = expectedArtifacts();
  fs.rmSync(absoluteContractPath('protocols/.gitkeep'), { force: true });
  for (const [artifactPath, artifact] of artifacts) {
    writeAtomic(artifactPath, artifact);
  }
  const manifest = buildManifest(artifacts);
  writeAtomic(manifestPath, manifest);
  validateCompletePack(artifacts, manifest);
  return manifest;
}

export function checkContractPackCatalogProtocols(): ContractArtifactEnvelope {
  const artifacts = expectedArtifacts();
  for (const [artifactPath, artifact] of artifacts) {
    assertExpectedBytes(artifactPath, artifact);
  }
  const manifest = buildManifest(artifacts);
  assertExpectedBytes(manifestPath, manifest);
  const parsedManifest = readArtifact(manifestPath);
  if (parsedManifest.hash !== manifest.hash) {
    throw new Error('G0.4 manifest hash drift');
  }
  validateCompletePack(artifacts, parsedManifest);
  return parsedManifest;
}
