import fs from 'fs';
import path from 'path';

import { Ajv2020, type AnySchema, type ErrorObject } from 'ajv/dist/2020.js';

import {
  CLOSED_SCHEMA_DESCRIPTORS,
  CLOSED_SCHEMA_COMMAND_KEYS,
  CLOSED_SCHEMA_TOP_LEVEL_KEYS,
  CLOSED_SCHEMA_TOP_LEVEL_REQUIRED_KEYS,
  CLOSED_SCHEMA_UNIONS,
  buildClosedSchemaArtifacts,
} from './closed-schema-artifacts.js';
import {
  CLOSED_SCHEMA_NEGATIVE_CASES,
  CLOSED_SCHEMA_POSITIVE_CASES,
  type ClosedSchemaNegativeCase,
} from './closed-schema-fixtures.js';
import {
  calculateArtifactHash,
  canonicalJson,
  parseContractArtifactEnvelope,
} from './index.js';
import {
  assertJsonObject,
  strictParseJson,
  strictParseJsonBytes,
} from './strict-json.js';
import type {
  ContractArtifactEnvelope,
  JsonObject,
  JsonValue,
} from './types.js';
import { assertCurrentG2SealedBoundary } from './current-g2-sealed-boundary.js';

const contractsRoot = import.meta.dirname;
const foundationManifestHash =
  'sha256:e85b654581c036f8129677d7443a0704ebc8b8fbe87907b842aaefe1501e637d';
const manifestPath = 'contract-pack-closed-schemas.json';
const positiveCasesPath = 'conformance/closed-schemas/positive-cases.json';
const negativeCasesPath = 'conformance/closed-schemas/negative-cases.json';
const domainCatalogPath = 'catalogs/closed-schema-domain-separators.json';

const recordedFutureReservedDirectories = [
  'protocols',
  'safety',
  'sqlite',
  'conformance/draft',
  'conformance/sealed',
] as const;

const stillReservedDirectories = ['conformance/sealed'] as const;

function asciiCompare(left: string, right: string): number {
  return left < right ? -1 : left > right ? 1 : 0;
}

function absoluteContractPath(relativePath: string): string {
  const absolute = path.resolve(contractsRoot, relativePath);
  if (!absolute.startsWith(`${contractsRoot}${path.sep}`)) {
    throw new Error(`Contract path escapes root: ${relativePath}`);
  }
  return absolute;
}

function readJsonObject(relativePath: string): JsonObject {
  const absolute = absoluteContractPath(relativePath);
  if (!fs.lstatSync(absolute).isFile()) {
    throw new Error(`Contract path is not a regular file: ${relativePath}`);
  }
  const value = strictParseJsonBytes(fs.readFileSync(absolute));
  assertJsonObject(value);
  return value;
}

function renderJson(value: JsonValue): string {
  return `${JSON.stringify(value, null, 2)}\n`;
}

function writeAtomic(relativePath: string, value: JsonValue): void {
  const file = absoluteContractPath(relativePath);
  fs.mkdirSync(path.dirname(file), { recursive: true });
  const temporary = `${file}.tmp-${process.pid}`;
  fs.writeFileSync(temporary, renderJson(value), {
    encoding: 'utf8',
    mode: 0o644,
  });
  fs.renameSync(temporary, file);
}

function assertExpectedBytes(
  relativePath: string,
  expected: ContractArtifactEnvelope,
): void {
  const actual = fs.readFileSync(absoluteContractPath(relativePath), 'utf8');
  if (actual !== renderJson(expected)) {
    throw new Error(
      `${relativePath} is not generated byte-for-byte; run npm run contracts:generate`,
    );
  }
}

function buildArtifact(
  format: string,
  refId: string,
  domainSeparator: string,
  payload: JsonObject,
): ContractArtifactEnvelope {
  const detachedPayload = strictParseJson(JSON.stringify(payload));
  assertJsonObject(detachedPayload);
  const artifact: ContractArtifactEnvelope = {
    format,
    ref: { id: refId, version: '1.0.0' },
    version: 1,
    domain_separator: domainSeparator,
    hash: `sha256:${'0'.repeat(64)}`,
    payload: detachedPayload,
  };
  const complete = { ...artifact, hash: calculateArtifactHash(artifact) };
  parseContractArtifactEnvelope(complete);
  return complete;
}

function buildFixtureArtifacts(): Array<[string, ContractArtifactEnvelope]> {
  return [
    [
      positiveCasesPath,
      buildArtifact(
        'icarus.workflow-closed-schema-positive-cases/1',
        'icarus.workflow-closed-schema-positive-cases',
        'icarus:workflow-closed-schema-positive-cases:1\n',
        { cases: CLOSED_SCHEMA_POSITIVE_CASES },
      ),
    ],
    [
      negativeCasesPath,
      buildArtifact(
        'icarus.workflow-closed-schema-negative-cases/1',
        'icarus.workflow-closed-schema-negative-cases',
        'icarus:workflow-closed-schema-negative-cases:1\n',
        { cases: CLOSED_SCHEMA_NEGATIVE_CASES },
      ),
    ],
  ];
}

function buildDomainCatalog(): ContractArtifactEnvelope {
  const entries = [
    ...CLOSED_SCHEMA_DESCRIPTORS.map((descriptor) => ({
      format: descriptor.artifact_format,
      domain_separator: descriptor.domain_separator,
    })),
    {
      format: 'icarus.workflow-closed-schema-positive-cases/1',
      domain_separator: 'icarus:workflow-closed-schema-positive-cases:1\n',
    },
    {
      format: 'icarus.workflow-closed-schema-negative-cases/1',
      domain_separator: 'icarus:workflow-closed-schema-negative-cases:1\n',
    },
    {
      format: 'icarus.workflow-closed-schema-domain-separators/1',
      domain_separator: 'icarus:workflow-closed-schema-domain-separators:1\n',
    },
    {
      format: 'icarus.workflow-contract-pack-closed-schemas/1',
      domain_separator: 'icarus:workflow-contract-pack-closed-schemas:1\n',
    },
  ].sort((left, right) => asciiCompare(left.format, right.format));
  return buildArtifact(
    'icarus.workflow-closed-schema-domain-separators/1',
    'icarus.workflow-closed-schema-domain-separators',
    'icarus:workflow-closed-schema-domain-separators:1\n',
    { entries },
  );
}

function artifactDescriptor(
  artifactPath: string,
  artifact: ContractArtifactEnvelope,
): JsonObject {
  return {
    path: artifactPath,
    format: artifact.format,
    ref: artifact.ref,
    version: artifact.version,
    domain_separator: artifact.domain_separator,
    hash: artifact.hash,
  };
}

function buildManifest(
  artifacts: Array<[string, ContractArtifactEnvelope]>,
): ContractArtifactEnvelope {
  const schemaFormats = CLOSED_SCHEMA_DESCRIPTORS.map(
    (descriptor) => descriptor.artifact_format,
  ).sort(asciiCompare);
  return buildArtifact(
    'icarus.workflow-contract-pack-closed-schemas/1',
    'icarus.workflow-contract-pack-closed-schemas',
    'icarus:workflow-contract-pack-closed-schemas:1\n',
    {
      gate: 'G0.3',
      status: 'closed_schemas',
      foundation_manifest_hash: foundationManifestHash,
      schema_formats: schemaFormats,
      schema_targets: CLOSED_SCHEMA_DESCRIPTORS.map((descriptor) => ({
        artifact_path: descriptor.artifact_path,
        artifact_format: descriptor.artifact_format,
        target_contract: descriptor.target_format,
      })).sort((left, right) =>
        asciiCompare(left.artifact_format, right.artifact_format),
      ),
      positive_case_count: CLOSED_SCHEMA_POSITIVE_CASES.length,
      negative_case_count: CLOSED_SCHEMA_NEGATIVE_CASES.length,
      artifacts: artifacts
        .map(([artifactPath, artifact]) =>
          artifactDescriptor(artifactPath, artifact),
        )
        .sort((left, right) =>
          asciiCompare(String(left.path), String(right.path)),
        ),
      future_reserved_directories: [...recordedFutureReservedDirectories],
    },
  );
}

function expectedArtifacts(): Array<[string, ContractArtifactEnvelope]> {
  return [
    ...buildClosedSchemaArtifacts(),
    ...buildFixtureArtifacts(),
    [domainCatalogPath, buildDomainCatalog()],
  ];
}

function schemaProperties(schema: JsonObject): string[] {
  assertJsonObject(schema.properties);
  return Object.keys(schema.properties).sort(asciiCompare);
}

function schemaRequired(schema: JsonObject): string[] {
  if (!Array.isArray(schema.required)) return [];
  return schema.required.map(String).sort(asciiCompare);
}

function validateTypeScriptKeyConformance(
  schemaArtifacts: ContractArtifactEnvelope[],
): void {
  const byFormat = new Map(
    schemaArtifacts.map((artifact) => [artifact.format, artifact] as const),
  );
  for (const [format, expectedKeys] of Object.entries(
    CLOSED_SCHEMA_TOP_LEVEL_KEYS,
  )) {
    const artifact = byFormat.get(format);
    if (!artifact)
      throw new Error(`Missing schema for TypeScript keys: ${format}`);
    const actualKeys = schemaProperties(artifact.payload);
    if (
      actualKeys.join('\n') !== [...expectedKeys].sort(asciiCompare).join('\n')
    ) {
      throw new Error(`TypeScript/schema top-level key drift for ${format}`);
    }
    const expectedRequiredKeys = CLOSED_SCHEMA_TOP_LEVEL_REQUIRED_KEYS[format];
    if (
      !expectedRequiredKeys ||
      schemaRequired(artifact.payload).join('\n') !==
        [...expectedRequiredKeys].sort(asciiCompare).join('\n')
    ) {
      throw new Error(
        `TypeScript/schema top-level required key drift for ${format}`,
      );
    }
  }
}

function objectAt(value: JsonValue, keys: readonly string[]): JsonObject {
  let current: JsonValue = value;
  for (const key of keys) {
    assertJsonObject(current);
    current = current[key]!;
  }
  assertJsonObject(current);
  return current;
}

function unionConstValues(union: JsonObject, propertyName: string): string[] {
  if (!Array.isArray(union.oneOf))
    throw new Error('Closed union is missing oneOf');
  const values: string[] = [];
  for (const branch of union.oneOf) {
    assertJsonObject(branch);
    assertJsonObject(branch.properties);
    assertJsonObject(branch.properties[propertyName]);
    if (typeof branch.properties[propertyName].const !== 'string') {
      throw new Error(`Closed union branch lacks ${propertyName} const`);
    }
    values.push(branch.properties[propertyName].const);
  }
  return [...new Set(values)].sort(asciiCompare);
}

function assertSameValues(
  actual: readonly string[],
  expected: readonly string[],
  label: string,
): void {
  if (
    [...actual].sort(asciiCompare).join('\n') !==
    [...expected].sort(asciiCompare).join('\n')
  ) {
    throw new Error(`${label} TypeScript/schema union drift`);
  }
}

function validateTypeScriptUnionConformance(
  schemaArtifacts: ContractArtifactEnvelope[],
): void {
  const byFormat = new Map(
    schemaArtifacts.map((artifact) => [artifact.format, artifact] as const),
  );
  const definition = byFormat.get('icarus.workflow-definition-schema/1');
  const command = byFormat.get('icarus.workflow-runtime-command-schema/1');
  const feature = byFormat.get('icarus.workflow-feature-manifest-v2-schema/1');
  const source = byFormat.get('icarus.workflow-graph-scope-source-schema/1');
  const transition = byFormat.get('icarus.workflow-transition-schema/1');
  if (!definition || !command || !feature || !source || !transition) {
    throw new Error('Closed union conformance schema is missing');
  }

  const stateUnion = objectAt(definition.payload, [
    'properties',
    'states',
    'patternProperties',
    '^[A-Za-z0-9][A-Za-z0-9._-]{0,254}$',
  ]);
  assertSameValues(
    unionConstValues(stateUnion, 'type'),
    CLOSED_SCHEMA_UNIONS.workflow_state_types,
    'Workflow state',
  );
  assertSameValues(
    unionConstValues(command.payload, 'command_type'),
    CLOSED_SCHEMA_UNIONS.command_types,
    'Runtime command',
  );
  if (!Array.isArray(command.payload.oneOf)) {
    throw new Error('Runtime command schema is missing branches');
  }
  for (const branch of command.payload.oneOf) {
    assertJsonObject(branch);
    assertJsonObject(branch.properties);
    assertJsonObject(branch.properties.command_type);
    const expectedKeys = [
      ...CLOSED_SCHEMA_COMMAND_KEYS,
      ...(branch.properties.command_type.const ===
      'confirm_administrative_abandon'
        ? ['confirmation_ref']
        : []),
    ].sort(asciiCompare);
    if (
      Object.keys(branch.properties).sort(asciiCompare).join('\n') !==
      expectedKeys.join('\n')
    ) {
      throw new Error(
        `Runtime command key drift for ${String(branch.properties.command_type.const)}`,
      );
    }
    const expectedRequiredKeys = [
      ...CLOSED_SCHEMA_TOP_LEVEL_REQUIRED_KEYS[
        'icarus.workflow-runtime-command-schema/1'
      ]!,
      ...(branch.properties.command_type.const ===
      'confirm_administrative_abandon'
        ? ['confirmation_ref']
        : []),
    ].sort(asciiCompare);
    if (schemaRequired(branch).join('\n') !== expectedRequiredKeys.join('\n')) {
      throw new Error(
        `Runtime command required key drift for ${String(branch.properties.command_type.const)}`,
      );
    }
    assertJsonObject(branch.properties.reason_code);
    if (!Array.isArray(branch.properties.reason_code.enum)) {
      throw new Error('Runtime command reason code enum is missing');
    }
    assertSameValues(
      branch.properties.reason_code.enum.map(String),
      CLOSED_SCHEMA_UNIONS.command_reason_codes,
      'Runtime command reason code',
    );
  }
  const nodeUnion = objectAt(source.payload, ['$defs', 'graph_node']);
  assertSameValues(
    unionConstValues(nodeUnion, 'type'),
    CLOSED_SCHEMA_UNIONS.graph_node_types,
    'Graph node',
  );
  const resourceKind = objectAt(feature.payload, [
    'properties',
    'dynamic_workflow_resources',
    'items',
    'properties',
    'kind',
  ]);
  if (!Array.isArray(resourceKind.enum)) {
    throw new Error('Feature resource kind enum is missing');
  }
  assertSameValues(
    resourceKind.enum.map(String),
    CLOSED_SCHEMA_UNIONS.feature_resource_kinds,
    'Feature resource kind',
  );

  const valueBinding = objectAt(definition.payload, ['$defs', 'value_binding']);
  assertSameValues(
    unionConstValues(valueBinding, 'source'),
    CLOSED_SCHEMA_UNIONS.value_binding_sources,
    'Workflow value binding source',
  );
  const graphInputBinding = objectAt(definition.payload, [
    '$defs',
    'graph_input_binding',
  ]);
  assertSameValues(
    unionConstValues(graphInputBinding, 'source'),
    CLOSED_SCHEMA_UNIONS.graph_input_binding_sources,
    'Workflow graph input binding source',
  );
  const transitionEffect = objectAt(transition.payload, [
    '$defs',
    'transition_effect',
  ]);
  if (!Array.isArray(transitionEffect.oneOf)) {
    throw new Error('Transition effect union is missing branches');
  }
  for (const branch of transitionEffect.oneOf) {
    assertJsonObject(branch);
    const effectInputBinding = objectAt(branch, [
      'properties',
      'input_bindings',
      'patternProperties',
      '^[A-Za-z0-9][A-Za-z0-9._-]{0,254}$',
    ]);
    assertSameValues(
      unionConstValues(effectInputBinding, 'source'),
      CLOSED_SCHEMA_UNIONS.transition_effect_input_sources,
      'Workflow transition effect input binding source',
    );
  }
}

function validateVersionedRefConformance(
  schemaArtifacts: ContractArtifactEnvelope[],
): void {
  const foundationArtifact = parseContractArtifactEnvelope(
    readJsonObject('foundation/versioned-ref-schema.json'),
  );
  const {
    $schema: _schema,
    $id: _id,
    title: _title,
    ...foundationVersionedRef
  } = foundationArtifact.payload;
  const expected = canonicalJson(foundationVersionedRef);
  for (const artifact of schemaArtifacts) {
    const embedded = objectAt(artifact.payload, ['$defs', 'versioned_ref']);
    if (canonicalJson(embedded) !== expected) {
      throw new Error(`Embedded VersionedRef drift for ${artifact.format}`);
    }
  }
}

function validateClosedObjects(value: JsonValue, pointer = ''): void {
  if (Array.isArray(value)) {
    value.forEach((entry, index) =>
      validateClosedObjects(entry, `${pointer}/${index}`),
    );
    return;
  }
  if (value === null || typeof value !== 'object') return;
  const objectValue = value as JsonObject;
  if (objectValue.type === 'object') {
    const explicitRecord =
      objectValue.propertyNames !== undefined &&
      objectValue.additionalProperties !== undefined &&
      objectValue.additionalProperties !== true;
    const recursiveJsonObject =
      objectValue.additionalProperties !== null &&
      typeof objectValue.additionalProperties === 'object' &&
      (objectValue.additionalProperties as JsonObject).$ref ===
        '#/$defs/json_value';
    if (
      objectValue.additionalProperties !== false &&
      !explicitRecord &&
      !recursiveJsonObject
    ) {
      throw new Error(`Open object schema at ${pointer || '/'}`);
    }
  }
  for (const [key, child] of Object.entries(objectValue)) {
    validateClosedObjects(child, `${pointer}/${key}`);
  }
}

function matchesExpectedError(
  errors: ErrorObject[] | null | undefined,
  testCase: ClosedSchemaNegativeCase,
): boolean {
  return Boolean(
    errors?.some((error) => {
      if (
        error.keyword !== testCase.expected_keyword ||
        error.instancePath !== testCase.expected_instance_pointer
      ) {
        return false;
      }
      if (testCase.expected_additional_property === null) return true;
      return (
        error.params.additionalProperty ===
        testCase.expected_additional_property
      );
    }),
  );
}

function validateSchemasAndFixtures(
  artifacts: Array<[string, ContractArtifactEnvelope]>,
): void {
  const schemaArtifacts = artifacts
    .filter(([artifactPath]) => artifactPath.startsWith('schemas/'))
    .map(([, artifact]) => artifact);
  const ajv = new Ajv2020({
    allErrors: true,
    coerceTypes: false,
    removeAdditional: false,
    strict: true,
    useDefaults: false,
  });
  const validators = new Map<string, ReturnType<typeof ajv.compile>>();
  for (const descriptor of CLOSED_SCHEMA_DESCRIPTORS) {
    const artifact = schemaArtifacts.find(
      (candidate) => candidate.format === descriptor.artifact_format,
    );
    if (!artifact)
      throw new Error(`Missing schema artifact ${descriptor.artifact_format}`);
    parseContractArtifactEnvelope(artifact);
    validateClosedObjects(artifact.payload);
    validators.set(
      descriptor.artifact_format,
      ajv.compile(artifact.payload as AnySchema),
    );
  }

  validateTypeScriptKeyConformance(schemaArtifacts);
  validateTypeScriptUnionConformance(schemaArtifacts);
  validateVersionedRefConformance(schemaArtifacts);

  for (const testCase of CLOSED_SCHEMA_POSITIVE_CASES) {
    const validate = validators.get(testCase.schema_format);
    if (!validate)
      throw new Error(`Unknown positive schema ${testCase.schema_format}`);
    if (!validate(testCase.instance)) {
      throw new Error(
        `Positive fixture ${testCase.case_id} failed: ${ajv.errorsText(validate.errors)}`,
      );
    }
  }
  for (const testCase of CLOSED_SCHEMA_NEGATIVE_CASES) {
    const validate = validators.get(testCase.schema_format);
    if (!validate)
      throw new Error(`Unknown negative schema ${testCase.schema_format}`);
    if (validate(testCase.instance)) {
      throw new Error(`Negative fixture ${testCase.case_id} was accepted`);
    }
    if (!matchesExpectedError(validate.errors, testCase)) {
      throw new Error(
        `Negative fixture ${testCase.case_id} did not produce ${testCase.expected_keyword} at ${testCase.expected_instance_pointer}: ${ajv.errorsText(validate.errors)}`,
      );
    }
  }
}

function validateDomainCatalog(
  artifacts: Array<[string, ContractArtifactEnvelope]>,
  manifest: ContractArtifactEnvelope,
): void {
  const catalog = artifacts.find(
    ([artifactPath]) => artifactPath === domainCatalogPath,
  )?.[1];
  if (!catalog || !Array.isArray(catalog.payload.entries)) {
    throw new Error('Closed-schema domain catalog is missing');
  }
  const expected = [...artifacts.map(([, artifact]) => artifact), manifest];
  if (catalog.payload.entries.length !== expected.length) {
    throw new Error('Closed-schema domain catalog coverage drift');
  }
  const seenFormats = new Set<string>();
  const seenDomains = new Set<string>();
  for (const entry of catalog.payload.entries) {
    assertJsonObject(entry);
    if (
      typeof entry.format !== 'string' ||
      typeof entry.domain_separator !== 'string' ||
      Object.keys(entry).sort().join(',') !== 'domain_separator,format'
    ) {
      throw new Error('Closed-schema domain entry must be closed');
    }
    if (
      seenFormats.has(entry.format) ||
      seenDomains.has(entry.domain_separator)
    ) {
      throw new Error('Closed-schema domains must be one-to-one');
    }
    seenFormats.add(entry.format);
    seenDomains.add(entry.domain_separator);
  }
  for (const artifact of expected) {
    const entry = catalog.payload.entries.find((candidate) => {
      assertJsonObject(candidate);
      return candidate.format === artifact.format;
    });
    assertJsonObject(entry);
    if (entry.domain_separator !== artifact.domain_separator) {
      throw new Error(`Closed-schema domain drift for ${artifact.format}`);
    }
  }
}

function validateDirectoryBoundaries(): void {
  const expectedSchemaFiles = CLOSED_SCHEMA_DESCRIPTORS.map((descriptor) =>
    path.basename(descriptor.artifact_path),
  ).sort(asciiCompare);
  const actualSchemaFiles = fs
    .readdirSync(absoluteContractPath('schemas'))
    .sort(asciiCompare);
  if (actualSchemaFiles.join('\n') !== expectedSchemaFiles.join('\n')) {
    throw new Error(
      'Schema directory contains missing or out-of-slice artifacts',
    );
  }
  const fixtureFiles = fs
    .readdirSync(absoluteContractPath('conformance/closed-schemas'))
    .sort(asciiCompare);
  if (fixtureFiles.join('\n') !== 'negative-cases.json\npositive-cases.json') {
    throw new Error('Closed-schema fixture directory boundary drift');
  }
  for (const directory of stillReservedDirectories) {
    try {
      assertCurrentG2SealedBoundary(absoluteContractPath(directory));
    } catch {
      throw new Error(`Future Gate directory contains artifacts: ${directory}`);
    }
  }
}

function validateFoundationIdentity(): void {
  const foundation = parseContractArtifactEnvelope(
    readJsonObject('contract-pack-foundation.json'),
  );
  if (foundation.hash !== foundationManifestHash) {
    throw new Error('G0.2 foundation manifest changed during G0.3');
  }
}

function validateCompletePack(
  artifacts: Array<[string, ContractArtifactEnvelope]>,
  manifest: ContractArtifactEnvelope,
): void {
  validateFoundationIdentity();
  validateSchemasAndFixtures(artifacts);
  validateDomainCatalog(artifacts, manifest);
  validateDirectoryBoundaries();
}

export function generateContractPackClosedSchemas(): ContractArtifactEnvelope {
  const artifacts = expectedArtifacts();
  for (const [artifactPath, artifact] of artifacts) {
    writeAtomic(artifactPath, artifact);
  }
  const manifest = buildManifest(artifacts);
  writeAtomic(manifestPath, manifest);
  validateCompletePack(artifacts, manifest);
  return manifest;
}

export function checkContractPackClosedSchemas(): ContractArtifactEnvelope {
  const artifacts = expectedArtifacts();
  for (const [artifactPath, artifact] of artifacts) {
    assertExpectedBytes(artifactPath, artifact);
  }
  const manifest = buildManifest(artifacts);
  assertExpectedBytes(manifestPath, manifest);
  const parsedManifest = parseContractArtifactEnvelope(
    readJsonObject(manifestPath),
  );
  if (parsedManifest.hash !== manifest.hash) {
    throw new Error('Closed-schema manifest hash drift');
  }
  validateCompletePack(artifacts, parsedManifest);
  return parsedManifest;
}
