import crypto from 'crypto';
import fs from 'fs';
import path from 'path';

import {
  Ajv2020,
  type AnySchema,
  type ValidateFunction,
} from 'ajv/dist/2020.js';

import {
  buildG0ConformanceArtifact,
  buildG0ConformanceSchemaArtifacts,
  buildG0ConformanceSemanticArtifacts,
  G0_CONFORMANCE_SCHEMA_FORMAT_BY_TARGET,
} from './g0-conformance-artifacts.js';
import {
  evaluateG0ConformanceNegativeFixture,
  G0_CONFORMANCE_FIXTURE_DESCRIPTORS,
  G0_CONFORMANCE_NEGATIVE_FIXTURES,
  G0_CONFORMANCE_POSITIVE_FIXTURES,
} from './g0-conformance-fixtures.js';
import {
  assertG0PriorManifestIdentities,
  buildG0ArtifactHashInventory,
  buildG0GateReview,
  buildG0MarkdownContractCoverage,
  G0_1_IDENTITY_HASHES,
  G0_MARKDOWN_SEMANTIC_FORMATS,
  G0_PRIOR_MANIFEST_IDENTITIES,
  g0ConformanceToolHash,
} from './g0-conformance-source.js';
import {
  G0_ARTIFACT_INVENTORY_ENTRY_KEYS,
  G0_ARTIFACT_INVENTORY_KEYS,
  G0_CONFORMANCE_FIXTURE_MUTATIONS,
  G0_GATE_REVIEW_KEYS,
  G0_MARKDOWN_COVERAGE_ENTRY_KEYS,
  G0_MARKDOWN_COVERAGE_KEYS,
  type G0ArtifactHashInventory,
  type G0ConformanceNegativeFixture,
  type G0GateReview,
  type G0MarkdownContractCoverage,
} from './g0-conformance-types.js';
import { canonicalJson } from './hash.js';
import { parseContractArtifactEnvelope } from './artifact.js';
import { assertJsonObject, strictParseJsonBytes } from './strict-json.js';
import type {
  ContractArtifactEnvelope,
  JsonObject,
  JsonValue,
} from './types.js';

const contractsRoot = import.meta.dirname;
const repoRoot = path.resolve(contractsRoot, '../../..');
const workflowRuntimeRoot = path.resolve(contractsRoot, '..');
const manifestPath = 'contract-pack-g0-conformance-exit.json';
const domainCatalogPath = 'catalogs/g0-conformance-domain-separators.json';
const archivedFrameworkPath = path.join(
  repoRoot,
  'docs/archive/dynamic-workflow-runtime-v1/dynamic-workflow-dag-framework.md',
);

function archivedFramework(): string {
  return fs.readFileSync(archivedFrameworkPath, 'utf8');
}

export class G0ConformanceContractError extends Error {
  readonly code = 'g0_conformance_contract_drift';

  constructor(message: string) {
    super(message);
    this.name = 'G0ConformanceContractError';
  }
}

function absoluteContractPath(relativePath: string): string {
  const absolute = path.resolve(contractsRoot, relativePath);
  if (!absolute.startsWith(`${contractsRoot}${path.sep}`))
    throw new G0ConformanceContractError(
      `Contract path escapes root: ${relativePath}`,
    );
  return absolute;
}

function renderJson(value: JsonValue): string {
  return `${JSON.stringify(value, null, 2)}\n`;
}

function writeAtomic(relativePath: string, contents: string): void {
  const absolute = absoluteContractPath(relativePath);
  fs.mkdirSync(path.dirname(absolute), { recursive: true });
  const temporary = `${absolute}.tmp-${process.pid}`;
  fs.writeFileSync(temporary, contents, { encoding: 'utf8', mode: 0o644 });
  fs.renameSync(temporary, absolute);
}

function assertExpectedBytes(relativePath: string, expected: string): void {
  const actual = fs.readFileSync(absoluteContractPath(relativePath), 'utf8');
  if (actual !== expected)
    throw new G0ConformanceContractError(
      `${relativePath} is not generated byte-for-byte; run npm run contracts:generate`,
    );
}

function descriptor(relativePath: string, artifact: ContractArtifactEnvelope) {
  return {
    path: relativePath,
    format: artifact.format,
    ref: artifact.ref,
    version: artifact.version,
    domain_separator: artifact.domain_separator,
    hash: artifact.hash,
  };
}

function buildFixtureArtifacts(): Array<[string, ContractArtifactEnvelope]> {
  const payloads = [
    {
      format: 'icarus.workflow-g0-conformance-positive-cases/1',
      cases: G0_CONFORMANCE_POSITIVE_FIXTURES,
      positive_case_count: G0_CONFORMANCE_POSITIVE_FIXTURES.length,
    },
    {
      format: 'icarus.workflow-g0-conformance-negative-cases/1',
      cases: G0_CONFORMANCE_NEGATIVE_FIXTURES,
      negative_case_count: G0_CONFORMANCE_NEGATIVE_FIXTURES.length,
    },
  ] as const;
  return G0_CONFORMANCE_FIXTURE_DESCRIPTORS.map((fixture, index) => [
    fixture.artifact_path,
    buildG0ConformanceArtifact(
      fixture.artifact_format,
      fixture.ref_id,
      fixture.domain_separator,
      payloads[index] as unknown as JsonObject,
    ),
  ]);
}

function buildDomainCatalogArtifact(
  artifacts: Array<[string, ContractArtifactEnvelope]>,
): ContractArtifactEnvelope {
  const entries = [
    ...artifacts.map(([relativePath, artifact]) => ({
      format: artifact.format,
      domain_separator: artifact.domain_separator,
      artifact_path: relativePath,
    })),
    {
      format: 'icarus.workflow-contract-pack-g0-conformance-exit/1',
      domain_separator: 'icarus:workflow-contract-pack-g0-conformance-exit:1\n',
      artifact_path: manifestPath,
    },
    {
      format: 'icarus.workflow-g0-conformance-domain-separators/1',
      domain_separator: 'icarus:workflow-g0-conformance-domain-separators:1\n',
      artifact_path: domainCatalogPath,
    },
  ].sort((left, right) =>
    left.format < right.format ? -1 : left.format > right.format ? 1 : 0,
  );
  return buildG0ConformanceArtifact(
    'icarus.workflow-g0-conformance-domain-separators/1',
    'icarus.workflow-g0-conformance-domain-separators',
    'icarus:workflow-g0-conformance-domain-separators:1\n',
    {
      registry_version: 1,
      entries,
    },
  );
}

function expectedArtifacts(): Array<[string, ContractArtifactEnvelope]> {
  const coverage = buildG0MarkdownContractCoverage(archivedFramework());
  const inventory = buildG0ArtifactHashInventory();
  const review = buildG0GateReview(coverage, inventory);
  const artifacts = [
    ...buildG0ConformanceSchemaArtifacts(),
    ...buildG0ConformanceSemanticArtifacts(coverage, inventory, review),
    ...buildFixtureArtifacts(),
  ];
  const domain = buildDomainCatalogArtifact(artifacts);
  return [
    ...artifacts,
    [domainCatalogPath, domain] as [string, ContractArtifactEnvelope],
  ].sort(([left], [right]) => (left < right ? -1 : left > right ? 1 : 0));
}

function artifactByFormat(
  artifacts: Array<[string, ContractArtifactEnvelope]>,
  format: string,
): ContractArtifactEnvelope {
  const artifact = artifacts.find(
    ([, candidate]) => candidate.format === format,
  )?.[1];
  if (!artifact)
    throw new G0ConformanceContractError(`Missing G0.9 artifact: ${format}`);
  return artifact;
}

function payloadByFormat<T>(
  artifacts: Array<[string, ContractArtifactEnvelope]>,
  format: string,
): T {
  return artifactByFormat(artifacts, format).payload as unknown as T;
}

function buildManifest(
  artifacts: Array<[string, ContractArtifactEnvelope]>,
): ContractArtifactEnvelope {
  const coverage = payloadByFormat<G0MarkdownContractCoverage>(
    artifacts,
    'icarus.workflow-markdown-contract-coverage/1',
  );
  const inventory = payloadByFormat<G0ArtifactHashInventory>(
    artifacts,
    'icarus.workflow-g0-artifact-hash-inventory/1',
  );
  const review = payloadByFormat<G0GateReview>(
    artifacts,
    'icarus.workflow-g0-gate-review/1',
  );
  return buildG0ConformanceArtifact(
    'icarus.workflow-contract-pack-g0-conformance-exit/1',
    'icarus.workflow-contract-pack-g0-conformance-exit',
    'icarus:workflow-contract-pack-g0-conformance-exit:1\n',
    {
      gate: 'G0.9',
      status: 'g0_conformance_exit',
      gate_decision: 'pass',
      g0_1_managed_distribution_manifest_hash:
        G0_1_IDENTITY_HASHES.managed_distribution_manifest,
      g0_1_locked_toolchain_inputs_hash:
        G0_1_IDENTITY_HASHES.locked_toolchain_inputs,
      g0_1_package_lock_hash: G0_1_IDENTITY_HASHES.package_lock,
      prior_manifest_hashes: Object.fromEntries(
        Object.entries(G0_PRIOR_MANIFEST_IDENTITIES).map(
          ([sliceId, identity]) => [sliceId, identity.hash],
        ),
      ),
      generated_by_tool_hash: g0ConformanceToolHash(),
      markdown_coverage_hash: coverage.coverage_hash,
      markdown_coverage_entry_count: coverage.entries.length,
      semantic_format_count: G0_MARKDOWN_SEMANTIC_FORMATS.length,
      artifact_inventory_hash: inventory.inventory_hash,
      artifact_inventory_entry_count: inventory.entry_count,
      gate_review_hash: review.review_hash,
      exit_criterion_count: review.exit_criteria.length,
      positive_case_count: G0_CONFORMANCE_POSITIVE_FIXTURES.length,
      negative_case_count: G0_CONFORMANCE_NEGATIVE_FIXTURES.length,
      g0_status: 'DONE',
      g1_status: 'READY',
      g2_status: 'READY',
      g3_through_g9_status: 'NOT_READY',
      sqlite_profile_status: 'candidate',
      certification_status: 'not_certified',
      golden_semantic_review_status: 'absent',
      golden_seal_status: 'not_run',
      sealed_bundle_status: 'absent',
      executable_ddl_status: 'absent',
      production_compiler_status: 'absent',
      registry_runtime_status: 'absent',
      runtime_center_ui_status: 'absent',
      conformance_entrypoint: 'npm run test:g0',
      artifacts: artifacts.map(([relativePath, artifact]) =>
        descriptor(relativePath, artifact),
      ),
    },
  );
}

function keyset(
  actual: string[],
  expected: readonly string[],
  label: string,
): void {
  if (canonicalJson(actual.sort()) !== canonicalJson([...expected].sort()))
    throw new G0ConformanceContractError(`${label} TypeScript keyset drift`);
}

function validateTypeScriptConformance(
  artifacts: Array<[string, ContractArtifactEnvelope]>,
): void {
  const coverage = payloadByFormat<G0MarkdownContractCoverage>(
    artifacts,
    'icarus.workflow-markdown-contract-coverage/1',
  );
  const inventory = payloadByFormat<G0ArtifactHashInventory>(
    artifacts,
    'icarus.workflow-g0-artifact-hash-inventory/1',
  );
  const review = payloadByFormat<G0GateReview>(
    artifacts,
    'icarus.workflow-g0-gate-review/1',
  );
  keyset(Object.keys(coverage), G0_MARKDOWN_COVERAGE_KEYS, 'coverage');
  for (const candidate of coverage.entries)
    keyset(
      Object.keys(candidate),
      G0_MARKDOWN_COVERAGE_ENTRY_KEYS,
      'coverage entry',
    );
  keyset(Object.keys(inventory), G0_ARTIFACT_INVENTORY_KEYS, 'inventory');
  for (const candidate of inventory.entries)
    keyset(
      Object.keys(candidate),
      G0_ARTIFACT_INVENTORY_ENTRY_KEYS,
      'inventory entry',
    );
  keyset(Object.keys(review), G0_GATE_REVIEW_KEYS, 'gate review');
}

function compileSchemas(
  artifacts: Array<[string, ContractArtifactEnvelope]>,
): Map<string, ValidateFunction> {
  const ajv = new Ajv2020({
    strict: true,
    allErrors: true,
    coerceTypes: false,
    useDefaults: false,
    removeAdditional: false,
  });
  const result = new Map<string, ValidateFunction>();
  for (const [targetFormat, schemaFormat] of Object.entries(
    G0_CONFORMANCE_SCHEMA_FORMAT_BY_TARGET,
  )) {
    const schema = artifactByFormat(artifacts, schemaFormat);
    result.set(targetFormat, ajv.compile(schema.payload as AnySchema));
  }
  return result;
}

function validateSchemas(
  artifacts: Array<[string, ContractArtifactEnvelope]>,
): void {
  const validators = compileSchemas(artifacts);
  for (const [relativePath, artifact] of artifacts) {
    const validate = validators.get(artifact.format);
    if (validate && !validate(artifact.payload))
      throw new G0ConformanceContractError(
        `${relativePath} failed closed schema: ${JSON.stringify(validate.errors)}`,
      );
  }
  validateTypeScriptConformance(artifacts);
}

function validateCoverage(
  artifacts: Array<[string, ContractArtifactEnvelope]>,
): void {
  const coverage = payloadByFormat<G0MarkdownContractCoverage>(
    artifacts,
    'icarus.workflow-markdown-contract-coverage/1',
  );
  if (
    coverage.contract_values_without_markdown.length !== 0 ||
    coverage.markdown_values_without_contract.length !== 0 ||
    coverage.entries.length !== coverage.contract_value_count ||
    coverage.markdown_value_count !== coverage.contract_value_count ||
    coverage.category_counts.semantic_format !== 19 ||
    coverage.category_counts.compiler_error_code !== 27 ||
    coverage.category_counts.runtime_fact_kind !== 13 ||
    coverage.category_counts.runtime_event_type !== 39 ||
    coverage.category_counts.runtime_state_value < 80
  ) {
    throw new G0ConformanceContractError(
      'Markdown/Contract coverage is incomplete',
    );
  }
  for (const candidate of coverage.entries) {
    if (candidate.fixture_refs.length === 0 || !candidate.change_impact)
      throw new G0ConformanceContractError(
        `Coverage evidence incomplete: ${candidate.coverage_id}`,
      );
  }
}

function validateInventory(
  artifacts: Array<[string, ContractArtifactEnvelope]>,
): void {
  const inventory = payloadByFormat<G0ArtifactHashInventory>(
    artifacts,
    'icarus.workflow-g0-artifact-hash-inventory/1',
  );
  if (
    inventory.entry_count !== 133 ||
    inventory.entries.length !== inventory.entry_count ||
    inventory.duplicate_paths.length !== 0 ||
    inventory.missing_paths.length !== 0 ||
    inventory.class_counts.contract_manifest !== 7 ||
    inventory.class_counts.contract_artifact !== 76 ||
    inventory.class_counts.raw_source_bytes !== 40 ||
    inventory.class_counts.capacity_config !== 1 ||
    inventory.class_counts.toolchain_identity !== 9
  ) {
    throw new G0ConformanceContractError('G0 artifact inventory is incomplete');
  }
  for (const candidate of inventory.entries) {
    const absolute = path.resolve(repoRoot, candidate.path);
    const bytes = fs.readFileSync(absolute);
    const actualRaw = `sha256:${crypto
      .createHash('sha256')
      .update(bytes)
      .digest('hex')}`;
    if (candidate.raw_sha256 !== actualRaw)
      throw new G0ConformanceContractError(
        `Raw inventory hash mismatch: ${candidate.path}`,
      );
  }
}

function validateGateReview(
  artifacts: Array<[string, ContractArtifactEnvelope]>,
): void {
  const review = payloadByFormat<G0GateReview>(
    artifacts,
    'icarus.workflow-g0-gate-review/1',
  );
  if (
    review.decision !== 'pass' ||
    review.slice_identities.length !== 8 ||
    review.exit_criteria.length !== 9 ||
    review.gate_statuses.length !== 10 ||
    review.gate_statuses[0]?.status !== 'DONE' ||
    review.gate_statuses[1]?.status !== 'READY' ||
    review.gate_statuses[2]?.status !== 'READY' ||
    review.gate_statuses.slice(3).some((gate) => gate.status !== 'NOT_READY') ||
    review.status_proof.golden_semantic_review_status !== 'absent' ||
    review.status_proof.golden_seal_status !== 'not_run' ||
    review.status_proof.sealed_bundle_status !== 'absent' ||
    review.status_proof.sqlite_profile_status !== 'candidate' ||
    review.status_proof.sqlite_certification_status !== 'not_certified' ||
    review.status_proof.executable_ddl_status !== 'absent' ||
    review.status_proof.production_compiler_status !== 'absent'
  ) {
    throw new G0ConformanceContractError('G0 Gate review status drift');
  }
}

function validateFixtures(): void {
  if (
    G0_CONFORMANCE_POSITIVE_FIXTURES.length !== 8 ||
    G0_CONFORMANCE_NEGATIVE_FIXTURES.length !== 20 ||
    new Set(G0_CONFORMANCE_FIXTURE_MUTATIONS).size !== 20
  ) {
    throw new G0ConformanceContractError('G0.9 fixture coverage drift');
  }
  for (const fixture of G0_CONFORMANCE_NEGATIVE_FIXTURES) {
    if (
      evaluateG0ConformanceNegativeFixture(fixture) !== fixture.expected_error
    )
      throw new G0ConformanceContractError(
        `G0.9 negative fixture oracle drift: ${fixture.fixture_id}`,
      );
  }
}

function validateDomainCatalog(
  artifacts: Array<[string, ContractArtifactEnvelope]>,
  manifest: ContractArtifactEnvelope,
): void {
  const domain = artifactByFormat(
    artifacts,
    'icarus.workflow-g0-conformance-domain-separators/1',
  );
  const entries = domain.payload.entries;
  if (!Array.isArray(entries))
    throw new G0ConformanceContractError('G0.9 domain registry missing');
  const actualFormats = new Set(
    entries.map((value) => {
      assertJsonObject(value);
      return String(value.format);
    }),
  );
  const expectedFormats = new Set([
    ...artifacts.map(([, artifact]) => artifact.format),
    manifest.format,
  ]);
  if (
    actualFormats.size !== expectedFormats.size ||
    [...expectedFormats].some((format) => !actualFormats.has(format))
  ) {
    throw new G0ConformanceContractError('G0.9 domain coverage drift');
  }
}

function validateBoundaries(): void {
  const sealedEntries = fs.readdirSync(
    absoluteContractPath('conformance/sealed'),
  );
  const forbiddenPaths = [
    'compiler/graph-compiler.ts',
    'compiler/definition-lowering.ts',
    'compiler/conformance.ts',
    'store/runtime-store.ts',
    'store/schema/workflow-runtime-schema-v1.sql',
    'registry/resource-store.ts',
    'runtime/graph-runtime.ts',
    'projection/runtime-center-api.ts',
  ];
  if (
    sealedEntries.length !== 1 ||
    sealedEntries[0] !== '.gitkeep' ||
    forbiddenPaths.some((relativePath) =>
      fs.existsSync(path.join(workflowRuntimeRoot, relativePath)),
    )
  ) {
    throw new G0ConformanceContractError('G0 forbidden boundary crossed');
  }
  const sqlite = parseContractArtifactEnvelope(
    strictParseJsonBytes(
      fs.readFileSync(
        absoluteContractPath('sqlite/local_single_user_sqlite@1.json'),
      ),
    ),
  );
  if (
    sqlite.payload.certification_status !== 'candidate' ||
    sqlite.payload.sqlite_version !== null ||
    sqlite.payload.release_artifact_hash !== null
  ) {
    throw new G0ConformanceContractError(
      'SQLite candidate was falsely certified',
    );
  }
  const packageJson = strictParseJsonBytes(
    fs.readFileSync(path.join(repoRoot, 'package.json')),
  );
  assertJsonObject(packageJson);
  const scripts = packageJson.scripts;
  assertJsonObject(scripts);
  if (
    scripts['test:g0.9'] !==
      'vitest run src/workflow-runtime/contracts/g0-conformance.test.ts' ||
    typeof scripts['test:g0'] !== 'string' ||
    !scripts['test:g0'].includes('contracts:check') ||
    !scripts['test:g0'].includes('g0-conformance.test.ts')
  ) {
    throw new G0ConformanceContractError('Complete G0 entrypoint missing');
  }
  const ci = fs.readFileSync(
    path.join(repoRoot, '.github/workflows/ci.yml'),
    'utf8',
  );
  if (!ci.includes('npm run test:g0'))
    throw new G0ConformanceContractError(
      'CI does not run complete G0 conformance',
    );
}

function validatePack(
  artifacts: Array<[string, ContractArtifactEnvelope]>,
  manifest: ContractArtifactEnvelope,
): void {
  assertG0PriorManifestIdentities();
  validateSchemas(artifacts);
  validateCoverage(artifacts);
  validateInventory(artifacts);
  validateGateReview(artifacts);
  validateFixtures();
  validateDomainCatalog(artifacts, manifest);
  validateBoundaries();
  const regenerated = buildManifest(artifacts);
  if (canonicalJson(regenerated) !== canonicalJson(manifest))
    throw new G0ConformanceContractError('G0.9 manifest is not deterministic');
}

export function evaluateG0ConformanceFixture(
  fixture: G0ConformanceNegativeFixture,
): string {
  return evaluateG0ConformanceNegativeFixture(fixture);
}

export function generateContractPackG0Conformance(): ContractArtifactEnvelope {
  const artifacts = expectedArtifacts();
  const manifest = buildManifest(artifacts);
  validatePack(artifacts, manifest);
  for (const [relativePath, artifact] of artifacts)
    writeAtomic(relativePath, renderJson(artifact));
  writeAtomic(manifestPath, renderJson(manifest));
  return manifest;
}

export function checkContractPackG0Conformance(): ContractArtifactEnvelope {
  const artifacts = expectedArtifacts();
  const manifest = buildManifest(artifacts);
  validatePack(artifacts, manifest);
  for (const [relativePath, artifact] of artifacts)
    assertExpectedBytes(relativePath, renderJson(artifact));
  assertExpectedBytes(manifestPath, renderJson(manifest));
  return manifest;
}

export function buildG0ConformanceExpectedArtifactsForTest(): Array<
  [string, ContractArtifactEnvelope]
> {
  return expectedArtifacts();
}
