import fs from 'node:fs';
import path from 'node:path';

import { describe, expect, it } from 'vitest';

import { parseContractArtifactEnvelope } from './artifact.js';
import {
  checkG5BasicRuntimeContracts,
  G5_IMPLEMENTATION_SOURCE_PATHS,
} from './g5-basic-runtime-contract.js';
import { strictParseJsonBytes } from './strict-json.js';
import { G5_TRANSACTION_IDS } from './g5-basic-runtime-types.js';

const repoRoot = path.resolve(import.meta.dirname, '../../..');

describe('G5 Basic Runtime closed Contract Pack', () => {
  it('checks generated bytes and exact current authorities', () => {
    const pack = checkG5BasicRuntimeContracts();
    expect(pack.payload.status).toBe(
      'G5_REPAIR_EXIT_CANDIDATE_PENDING_INDEPENDENT_G5_WHOLE_GATE_REGRESSION',
    );
    expect(pack.payload.positive_case_count).toBe(9);
    expect(pack.payload.negative_case_count).toBe(14);
    expect(pack.payload.fault_case_count).toBe(16);
    const protocol = parseContractArtifactEnvelope(
      strictParseJsonBytes(
        fs.readFileSync(
          path.join(
            import.meta.dirname,
            'conformance/g5-basic-runtime/g5-basic-runtime-protocol@1.json',
          ),
        ),
      ),
    );
    expect(protocol.payload.transaction_ids).toEqual(G5_TRANSACTION_IDS);
    expect(protocol.payload.bindings).toEqual(
      expect.arrayContaining([
        expect.objectContaining({
          name: 'ownership',
          hash: 'sha256:6ba952bf7761f249fa16c0c44a37d48a67c9f5f21c3667a5c966ac59e8affb38',
        }),
        expect.objectContaining({
          name: 'execution_binding',
          hash: 'sha256:48f63ae7be30c61f056f78f713591f34431336cc722d6928fbc6e2783a062088',
        }),
        expect.objectContaining({
          name: 'schema_5',
          hash: 'sha256:baa39d55cac34133a29b461466aa450fec59bd2fd6df72334e8b33d1d1619869',
        }),
      ]),
    );
  });

  it('binds every production source and keeps G4 and forbidden surfaces unreachable', () => {
    expect(G5_IMPLEMENTATION_SOURCE_PATHS).toHaveLength(17);
    for (const relativePath of G5_IMPLEMENTATION_SOURCE_PATHS) {
      const source = fs.readFileSync(path.join(repoRoot, relativePath), 'utf8');
      expect(source).not.toMatch(
        /workflow-runtime\/bootstrap|g4-test-bootstrap/,
      );
      expect(source).not.toMatch(
        /(?:INSERT\s+(?:OR\s+\w+\s+)?INTO|UPDATE|DELETE\s+FROM)\s+["`']?(?:workflow_runtime_commands|workflow_runtime_command_invocations|workflow_graph_completion_cuts|workflow_relations)\b/i,
      );
      expect(source).not.toMatch(/\bworkflow_deadline\b|\bT6e\b/);
    }
    const referenceModel = fs.readFileSync(
      path.join(
        repoRoot,
        'src/workflow-runtime/contracts/g5-basic-runtime-reference-model.ts',
      ),
      'utf8',
    );
    expect(referenceModel).not.toMatch(
      /workflow-runtime\/runtime|runtime\/reconciler|WorkflowRuntimeStore/,
    );
  });
});
