export const G6_EXIT_STATUS =
  'G6_DYNAMIC_CLOSE_CONSTRUCTION_CANDIDATE_PENDING_INDEPENDENT_AFFECTED_CHAIN_REGRESSION' as const;

export const G6_PERSISTENT_MODE_POLICY =
  'HYBRID_GATE_CONTINUOUS_RUNTIME_V1' as const;

export const G6_FIXTURE_BINDING_DOMAIN =
  'icarus:workflow-g6-dynamic-close-fixture-binding:1\n';
