import fs from 'fs';
import path from 'path';

import { Ajv2020, type AnySchema, type ErrorObject } from 'ajv/dist/2020.js';

import { parseContractArtifactEnvelope } from './artifact.js';
import { canonicalJson } from './hash.js';
import {
  buildLogicalSchemaArtifact,
  buildLogicalSchemaSemanticArtifacts,
  LOGICAL_SCHEMA_ARTIFACT_DESCRIPTORS,
  LOGICAL_SCHEMA_FORMAT_BY_TARGET,
  payloadAsJsonValue,
} from './logical-schema-artifacts.js';
import {
  LOGICAL_SCHEMA_NEGATIVE_CASES,
  LOGICAL_SCHEMA_POSITIVE_CASES,
  type LogicalSchemaMutation,
  type LogicalSchemaNegativeCase,
} from './logical-schema-fixtures.js';
import {
  buildLogicalQueryCatalogPayload,
  buildLogicalSchemaSourcePayload,
  buildTypedRelationCatalogPayload,
} from './logical-schema-source.js';
import {
  EXTERNAL_REFERENCE_KEYS,
  LOGICAL_CHECK_KEYS,
  LOGICAL_COLUMN_KEYS,
  LOGICAL_FOREIGN_KEY_KEYS,
  LOGICAL_INDEX_KEYS,
  LOGICAL_PRIMARY_KEY_KEYS,
  LOGICAL_QUERY_CATALOG_KEYS,
  LOGICAL_QUERY_KEYS,
  LOGICAL_QUERY_ORDER_KEYS,
  LOGICAL_RELATION_POLICY_KEYS,
  LOGICAL_SCHEMA_SOURCE_KEYS,
  LOGICAL_TABLE_KEYS,
  LOGICAL_UNIQUE_KEY_KEYS,
  TYPED_RELATION_CATALOG_KEYS,
  TYPED_RELATION_KEYS,
  type LogicalQueryCatalogPayload,
  type LogicalSchemaSourcePayload,
  type LogicalTableMetadata,
  type TypedRelationCatalogPayload,
} from './logical-schema-types.js';
import { RUNTIME_STATE_MACHINES } from './protocol-table-types.js';
import {
  assertJsonObject,
  strictParseJson,
  strictParseJsonBytes,
} from './strict-json.js';
import type {
  ContractArtifactEnvelope,
  JsonObject,
  JsonValue,
} from './types.js';

const contractsRoot = import.meta.dirname;
const foundationManifestHash =
  'sha256:e85b654581c036f8129677d7443a0704ebc8b8fbe87907b842aaefe1501e637d';
const closedSchemaManifestHash =
  'sha256:c5ea281d64480787322e8b6ef619b2f90784084d87ba4373c94288ed5e7aa3a8';
const catalogProtocolManifestHash =
  'sha256:e4947c515a28b3baf6782a980db9c26d32612b3c6acd3cd04348e73bd54ff607';
const safetySqliteManifestHash =
  'sha256:76b8e1196ac422500be9c79a767e673e9c30fa3d9bbb1dc12fc54613cd40b428';
const currentReopenedCatalogProtocolManifestHash =
  'sha256:a648dc9326255b109690cb47d58032775825ae065caf8f7cbb0ef73efcf984f7';
const currentReopenedSafetySqliteManifestHash =
  'sha256:4f756c9427a9e5fd8f034c2abdab3c614b675af8b8bbb350fc4219917159cd8d';
const manifestPath = 'contract-pack-logical-schema.json';
const positiveCasesPath = 'conformance/logical-schema/positive-cases.json';
const negativeCasesPath = 'conformance/logical-schema/negative-cases.json';
const domainCatalogPath = 'catalogs/logical-schema-domain-separators.json';

export class LogicalSchemaContractError extends Error {
  readonly code = 'logical_schema_contract_drift';

  constructor(message: string) {
    super(message);
    this.name = 'LogicalSchemaContractError';
  }
}

function asciiCompare(left: string, right: string): number {
  return left < right ? -1 : left > right ? 1 : 0;
}

function absoluteContractPath(relativePath: string): string {
  const absolute = path.resolve(contractsRoot, relativePath);
  if (!absolute.startsWith(`${contractsRoot}${path.sep}`)) {
    throw new Error(`Contract path escapes root: ${relativePath}`);
  }
  return absolute;
}

function renderJson(value: JsonValue): string {
  return `${JSON.stringify(value, null, 2)}\n`;
}

function writeAtomicFile(
  relativePath: string,
  artifact: ContractArtifactEnvelope,
): void {
  const absolute = absoluteContractPath(relativePath);
  fs.mkdirSync(path.dirname(absolute), { recursive: true });
  const temporary = `${absolute}.tmp-${process.pid}`;
  fs.writeFileSync(temporary, renderJson(artifact), {
    encoding: 'utf8',
    mode: 0o644,
  });
  fs.renameSync(temporary, absolute);
}

function assertExpectedBytes(
  relativePath: string,
  expected: ContractArtifactEnvelope,
): void {
  const actual = fs.readFileSync(absoluteContractPath(relativePath), 'utf8');
  if (actual !== renderJson(expected)) {
    throw new LogicalSchemaContractError(
      `${relativePath} is not generated byte-for-byte; run npm run contracts:generate`,
    );
  }
}

function readArtifact(relativePath: string): ContractArtifactEnvelope {
  return parseContractArtifactEnvelope(
    strictParseJsonBytes(fs.readFileSync(absoluteContractPath(relativePath))),
  );
}

function buildFixtureArtifacts(): Array<[string, ContractArtifactEnvelope]> {
  return [
    [
      positiveCasesPath,
      buildLogicalSchemaArtifact(
        'icarus.workflow-logical-schema-positive-cases/1',
        'icarus.workflow-logical-schema-positive-cases',
        'icarus:workflow-logical-schema-positive-cases:1\n',
        { cases: payloadAsJsonValue(LOGICAL_SCHEMA_POSITIVE_CASES) },
      ),
    ],
    [
      negativeCasesPath,
      buildLogicalSchemaArtifact(
        'icarus.workflow-logical-schema-negative-cases/1',
        'icarus.workflow-logical-schema-negative-cases',
        'icarus:workflow-logical-schema-negative-cases:1\n',
        { cases: payloadAsJsonValue(LOGICAL_SCHEMA_NEGATIVE_CASES) },
      ),
    ],
  ];
}

function buildDomainCatalog(
  priorArtifacts: Array<[string, ContractArtifactEnvelope]>,
): ContractArtifactEnvelope {
  const entries = [
    ...priorArtifacts.map(([, artifact]) => ({
      format: artifact.format,
      domain_separator: artifact.domain_separator,
    })),
    {
      format: 'icarus.workflow-logical-schema-domain-separators/1',
      domain_separator: 'icarus:workflow-logical-schema-domain-separators:1\n',
    },
    {
      format: 'icarus.workflow-contract-pack-logical-schema/1',
      domain_separator: 'icarus:workflow-contract-pack-logical-schema:1\n',
    },
  ].sort((left, right) => asciiCompare(left.format, right.format));
  return buildLogicalSchemaArtifact(
    'icarus.workflow-logical-schema-domain-separators/1',
    'icarus.workflow-logical-schema-domain-separators',
    'icarus:workflow-logical-schema-domain-separators:1\n',
    { entries },
  );
}

function artifactDescriptor(
  artifactPath: string,
  artifact: ContractArtifactEnvelope,
): JsonObject {
  return {
    path: artifactPath,
    format: artifact.format,
    ref: artifact.ref,
    version: artifact.version,
    domain_separator: artifact.domain_separator,
    hash: artifact.hash,
  };
}

function buildManifest(
  artifacts: Array<[string, ContractArtifactEnvelope]>,
): ContractArtifactEnvelope {
  const source = buildLogicalSchemaSourcePayload();
  const relations = buildTypedRelationCatalogPayload();
  const queries = buildLogicalQueryCatalogPayload();
  return buildLogicalSchemaArtifact(
    'icarus.workflow-contract-pack-logical-schema/1',
    'icarus.workflow-contract-pack-logical-schema',
    'icarus:workflow-contract-pack-logical-schema:1\n',
    {
      gate: 'G0.6',
      status: 'logical_schema_metadata_contract',
      foundation_manifest_hash: foundationManifestHash,
      closed_schema_manifest_hash: closedSchemaManifestHash,
      catalog_protocol_manifest_hash: catalogProtocolManifestHash,
      safety_sqlite_manifest_hash: safetySqliteManifestHash,
      schema_count: LOGICAL_SCHEMA_ARTIFACT_DESCRIPTORS.filter(
        (descriptor) => descriptor.artifact_kind === 'schema',
      ).length,
      table_count: source.table_count,
      column_count: source.column_count,
      internal_relation_count: relations.internal_relation_count,
      external_reference_count: relations.external_reference_count,
      foreign_key_intent_count: source.tables.reduce(
        (total, table) => total + table.foreign_keys.length,
        0,
      ),
      unique_key_intent_count: source.tables.reduce(
        (total, table) => total + table.unique_keys.length,
        0,
      ),
      check_intent_count: source.tables.reduce(
        (total, table) => total + table.checks.length,
        0,
      ),
      index_intent_count: source.tables.reduce(
        (total, table) => total + table.indexes.length,
        0,
      ),
      query_count: queries.query_count,
      positive_case_count: LOGICAL_SCHEMA_POSITIVE_CASES.length,
      negative_case_count: LOGICAL_SCHEMA_NEGATIVE_CASES.length,
      sqlite_profile_status: 'candidate',
      certification_status: 'not_certified',
      executable_ddl_status: 'absent',
      executable_schema_manifest_status: 'absent',
      sqlite_connection_factory_status: 'absent',
      sql_text_status: 'absent',
      artifacts: artifacts
        .map(([artifactPath, artifact]) =>
          artifactDescriptor(artifactPath, artifact),
        )
        .sort((left, right) =>
          asciiCompare(String(left.path), String(right.path)),
        ),
      next_reserved_directories: ['conformance/draft', 'conformance/sealed'],
      explicitly_absent_artifacts: [
        'executable_migration',
        'executable_schema_manifest',
        'sqlite_connection_factory',
        'sqlite_open_or_pragma_execution',
        'workflow_runtime_store',
        'runtime_supported_limits_certification',
        'compiler_or_golden_sealing',
        'registry_or_runtime_semantics',
        'runtime_center_or_ui',
      ],
    },
  );
}

function expectedArtifacts(): Array<[string, ContractArtifactEnvelope]> {
  const semantic = buildLogicalSchemaSemanticArtifacts();
  const fixtures = buildFixtureArtifacts();
  const prior = [...semantic, ...fixtures];
  return [...prior, [domainCatalogPath, buildDomainCatalog(prior)]];
}

function assertKeyset(
  actual: readonly string[],
  expected: readonly string[],
  label: string,
): void {
  if (
    [...actual].sort(asciiCompare).join('\n') !==
    [...expected].sort(asciiCompare).join('\n')
  ) {
    throw new LogicalSchemaContractError(`${label} keyset drift`);
  }
}

function validateClosedObjects(value: JsonValue, pointer = ''): void {
  if (Array.isArray(value)) {
    value.forEach((child, index) =>
      validateClosedObjects(child, `${pointer}/${index}`),
    );
    return;
  }
  if (value === null || typeof value !== 'object') return;
  const objectValue = value as JsonObject;
  if (
    objectValue.type === 'object' &&
    objectValue.additionalProperties !== false
  ) {
    throw new LogicalSchemaContractError(
      `Open G0.6 object schema at ${pointer || '/'}`,
    );
  }
  for (const [key, child] of Object.entries(objectValue)) {
    validateClosedObjects(child, `${pointer}/${key}`);
  }
}

function compileSchemas(artifacts: Array<[string, ContractArtifactEnvelope]>): {
  ajv: Ajv2020;
  validators: Map<string, ReturnType<Ajv2020['compile']>>;
  schemasByTarget: Map<string, JsonObject>;
} {
  const ajv = new Ajv2020({
    allErrors: true,
    coerceTypes: false,
    removeAdditional: false,
    strict: true,
    useDefaults: false,
  });
  const validators = new Map<string, ReturnType<Ajv2020['compile']>>();
  const schemasByTarget = new Map<string, JsonObject>();
  for (const descriptor of LOGICAL_SCHEMA_ARTIFACT_DESCRIPTORS.filter(
    (candidate) => candidate.artifact_kind === 'schema',
  )) {
    const artifact = artifacts.find(
      ([artifactPath]) => artifactPath === descriptor.artifact_path,
    )?.[1];
    if (!artifact || descriptor.target_format === null) {
      throw new Error(`Missing G0.6 schema ${descriptor.artifact_path}`);
    }
    validateClosedObjects(artifact.payload);
    schemasByTarget.set(descriptor.target_format, artifact.payload);
    validators.set(
      descriptor.target_format,
      ajv.compile(artifact.payload as AnySchema),
    );
  }
  return { ajv, validators, schemasByTarget };
}

function schemaPropertyKeys(schema: JsonObject, label: string): string[] {
  assertJsonObject(schema.properties);
  if (Object.keys(schema.properties).length === 0) {
    throw new LogicalSchemaContractError(`${label} has no properties`);
  }
  return Object.keys(schema.properties);
}

function validateSchemaTypeScriptConformance(
  schemasByTarget: Map<string, JsonObject>,
): void {
  const source = schemasByTarget.get(
    'icarus.workflow-runtime-logical-schema-source/1',
  );
  const relations = schemasByTarget.get(
    'icarus.workflow-runtime-typed-relation-catalog/1',
  );
  const queries = schemasByTarget.get(
    'icarus.workflow-runtime-query-catalog/1',
  );
  if (!source || !relations || !queries) {
    throw new LogicalSchemaContractError(
      'G0.6 target schema mapping is incomplete',
    );
  }
  assertKeyset(
    schemaPropertyKeys(source, 'source schema'),
    LOGICAL_SCHEMA_SOURCE_KEYS,
    'source schema',
  );
  assertJsonObject(source.$defs);
  assertJsonObject(source.$defs.table);
  assertJsonObject(source.$defs.column);
  assertKeyset(
    schemaPropertyKeys(source.$defs.table, 'table schema'),
    LOGICAL_TABLE_KEYS,
    'table schema',
  );
  assertKeyset(
    schemaPropertyKeys(source.$defs.column, 'column schema'),
    LOGICAL_COLUMN_KEYS,
    'column schema',
  );
  assertJsonObject(source.properties);
  assertJsonObject(source.properties.relation_policy);
  assertKeyset(
    schemaPropertyKeys(
      source.properties.relation_policy,
      'relation policy schema',
    ),
    LOGICAL_RELATION_POLICY_KEYS,
    'relation policy schema',
  );
  const sourceDefinitionKeysets = [
    ['external_reference', EXTERNAL_REFERENCE_KEYS],
    ['primary_key', LOGICAL_PRIMARY_KEY_KEYS],
    ['foreign_key', LOGICAL_FOREIGN_KEY_KEYS],
    ['unique_key', LOGICAL_UNIQUE_KEY_KEYS],
    ['check', LOGICAL_CHECK_KEYS],
    ['index', LOGICAL_INDEX_KEYS],
  ] as const;
  for (const [definitionName, expectedKeys] of sourceDefinitionKeysets) {
    assertJsonObject(source.$defs[definitionName]);
    assertKeyset(
      schemaPropertyKeys(
        source.$defs[definitionName],
        `${definitionName} schema`,
      ),
      expectedKeys,
      `${definitionName} schema`,
    );
  }
  assertKeyset(
    schemaPropertyKeys(relations, 'relation catalog schema'),
    TYPED_RELATION_CATALOG_KEYS,
    'relation catalog schema',
  );
  assertJsonObject(relations.$defs);
  assertJsonObject(relations.$defs.relation);
  assertKeyset(
    schemaPropertyKeys(relations.$defs.relation, 'relation schema'),
    TYPED_RELATION_KEYS,
    'relation schema',
  );
  assertKeyset(
    schemaPropertyKeys(queries, 'query catalog schema'),
    LOGICAL_QUERY_CATALOG_KEYS,
    'query catalog schema',
  );
  assertJsonObject(queries.$defs);
  assertJsonObject(queries.$defs.query);
  assertJsonObject(queries.$defs.order);
  assertKeyset(
    schemaPropertyKeys(queries.$defs.query, 'query schema'),
    LOGICAL_QUERY_KEYS,
    'query schema',
  );
  assertKeyset(
    schemaPropertyKeys(queries.$defs.order, 'query order schema'),
    LOGICAL_QUERY_ORDER_KEYS,
    'query order schema',
  );
}

function validateTypeScriptConformance(): void {
  const source = buildLogicalSchemaSourcePayload();
  const relations = buildTypedRelationCatalogPayload();
  const queries = buildLogicalQueryCatalogPayload();
  assertKeyset(Object.keys(source), LOGICAL_SCHEMA_SOURCE_KEYS, 'source');
  assertKeyset(
    Object.keys(source.relation_policy),
    LOGICAL_RELATION_POLICY_KEYS,
    'relation policy',
  );
  assertKeyset(Object.keys(source.tables[0]!), LOGICAL_TABLE_KEYS, 'table');
  assertKeyset(
    Object.keys(source.tables[0]!.columns[0]!),
    LOGICAL_COLUMN_KEYS,
    'column',
  );
  assertKeyset(
    Object.keys(source.tables[0]!.primary_key),
    LOGICAL_PRIMARY_KEY_KEYS,
    'primary key',
  );
  const foreignKey = source.tables.flatMap((table) => table.foreign_keys)[0]!;
  const uniqueKey = source.tables.flatMap((table) => table.unique_keys)[0]!;
  const check = source.tables.flatMap((table) => table.checks)[0]!;
  const index = source.tables.flatMap((table) => table.indexes)[0]!;
  const externalReference = source.tables
    .flatMap((table) => table.columns)
    .find((column) => column.external_reference !== null)!.external_reference!;
  assertKeyset(
    Object.keys(externalReference),
    EXTERNAL_REFERENCE_KEYS,
    'external reference',
  );
  assertKeyset(
    Object.keys(foreignKey),
    LOGICAL_FOREIGN_KEY_KEYS,
    'foreign key',
  );
  assertKeyset(Object.keys(uniqueKey), LOGICAL_UNIQUE_KEY_KEYS, 'unique key');
  assertKeyset(Object.keys(check), LOGICAL_CHECK_KEYS, 'check');
  assertKeyset(Object.keys(index), LOGICAL_INDEX_KEYS, 'index');
  assertKeyset(
    Object.keys(relations),
    TYPED_RELATION_CATALOG_KEYS,
    'relation catalog',
  );
  assertKeyset(
    Object.keys(relations.relations[0]!),
    TYPED_RELATION_KEYS,
    'relation',
  );
  assertKeyset(
    Object.keys(queries),
    LOGICAL_QUERY_CATALOG_KEYS,
    'query catalog',
  );
  assertKeyset(Object.keys(queries.queries[0]!), LOGICAL_QUERY_KEYS, 'query');
  assertKeyset(
    Object.keys(queries.queries[0]!.order_by[0]!),
    LOGICAL_QUERY_ORDER_KEYS,
    'query order',
  );
  const tables = new Map(source.tables.map((table) => [table.name, table]));
  for (const machine of RUNTIME_STATE_MACHINES) {
    const separator = machine.field.lastIndexOf('.');
    const tableName = machine.field.slice(0, separator);
    const columnName = machine.field.slice(separator + 1);
    const column = tables
      .get(tableName)
      ?.columns.find((candidate) => candidate.name === columnName);
    if (!column) {
      throw new LogicalSchemaContractError(
        `G0.4 state machine field is missing from G0.6: ${machine.field}`,
      );
    }
    assertKeyset(
      column.enum_values,
      machine.values.map((value) => value.value),
      `${machine.field} enum`,
    );
  }
}

function knownColumns(table: LogicalTableMetadata): Set<string> {
  return new Set(table.columns.map((column) => column.name));
}

function assertColumnsExist(
  table: LogicalTableMetadata,
  columns: readonly string[],
  label: string,
): void {
  const known = knownColumns(table);
  for (const column of columns) {
    if (!known.has(column)) {
      throw new LogicalSchemaContractError(
        `${label} references unknown ${table.name}.${column}`,
      );
    }
  }
}

function validateSource(source: LogicalSchemaSourcePayload): void {
  if (
    source.executable_status !== 'non_executable' ||
    source.ddl_generation_status !== 'forbidden_in_g0_6' ||
    source.sqlite_open_status !== 'forbidden_in_g0_6'
  ) {
    throw new LogicalSchemaContractError(
      'G0.6 metadata-only boundary was widened',
    );
  }
  if (
    source.table_count !== source.tables.length ||
    source.column_count !==
      source.tables.reduce((total, table) => total + table.columns.length, 0)
  ) {
    throw new LogicalSchemaContractError('Logical table or column count drift');
  }
  const tables = new Map(source.tables.map((table) => [table.name, table]));
  if (tables.size !== source.tables.length || source.tables.length !== 74) {
    throw new LogicalSchemaContractError(
      'All 74 Normative Logical Schema tables must appear exactly once',
    );
  }
  const globalRelationIds = new Set<string>();
  const globalConstraintIds = new Set<string>();
  const forbidden = new Set(source.forbidden_logical_columns);

  for (const [tableIndex, table] of source.tables.entries()) {
    if (table.ordinal !== tableIndex + 1 || table.columns.length === 0) {
      throw new LogicalSchemaContractError(
        `Table ordinal or empty column drift: ${table.name}`,
      );
    }
    const columns = knownColumns(table);
    if (columns.size !== table.columns.length) {
      throw new LogicalSchemaContractError(`Duplicate column in ${table.name}`);
    }
    for (const [columnIndex, column] of table.columns.entries()) {
      if (column.ordinal !== columnIndex + 1) {
        throw new LogicalSchemaContractError(
          `Column ordinal drift: ${table.name}.${column.name}`,
        );
      }
      if (
        forbidden.has(column.name) ||
        column.name.endsWith('_at') ||
        column.name === 'version'
      ) {
        throw new LogicalSchemaContractError(
          `Forbidden logical column: ${table.name}.${column.name}`,
        );
      }
      if (
        column.name.endsWith('_ref') &&
        column.logical_type !== 'external_reference'
      ) {
        throw new LogicalSchemaContractError(
          `Bare reference lacks external validator or typed target: ${table.name}.${column.name}`,
        );
      }
      if (
        (column.logical_type === 'external_reference') !==
        Boolean(column.external_reference)
      ) {
        throw new LogicalSchemaContractError(
          `External reference metadata drift: ${table.name}.${column.name}`,
        );
      }
      if (column.name.endsWith('_hash') && column.logical_type !== 'hash') {
        throw new LogicalSchemaContractError(
          `Hash column type drift: ${table.name}.${column.name}`,
        );
      }
      if (
        column.external_reference &&
        !column.relation_ids.includes(`ext:${table.name}:${column.name}`)
      ) {
        throw new LogicalSchemaContractError(
          `External relation id missing: ${table.name}.${column.name}`,
        );
      }
    }
    assertColumnsExist(
      table,
      table.primary_key.columns,
      `${table.name} primary key`,
    );
    for (const primaryColumn of table.primary_key.columns) {
      if (
        table.columns.find((column) => column.name === primaryColumn)!.nullable
      ) {
        throw new LogicalSchemaContractError(
          `Nullable primary key: ${table.name}.${primaryColumn}`,
        );
      }
    }
    for (const relation of table.foreign_keys) {
      if (globalRelationIds.has(relation.relation_id)) {
        throw new LogicalSchemaContractError(
          `Duplicate relation id ${relation.relation_id}`,
        );
      }
      globalRelationIds.add(relation.relation_id);
      assertColumnsExist(table, relation.source_columns, relation.relation_id);
      const target = tables.get(relation.target_table);
      if (!target) {
        throw new LogicalSchemaContractError(
          `${relation.relation_id} targets unknown table`,
        );
      }
      assertColumnsExist(target, relation.target_columns, relation.relation_id);
      if (relation.source_columns.length !== relation.target_columns.length) {
        throw new LogicalSchemaContractError(
          `${relation.relation_id} column arity drift`,
        );
      }
      const targetKeySets = [
        target.primary_key.columns,
        ...target.unique_keys.map((key) => key.columns),
      ];
      if (
        !targetKeySets.some(
          (columns) =>
            columns.length === relation.target_columns.length &&
            columns.every(
              (column, indexValue) =>
                column === relation.target_columns[indexValue],
            ),
        )
      ) {
        throw new LogicalSchemaContractError(
          `${relation.relation_id} target columns are not a declared PK/UK`,
        );
      }
      for (const sourceColumn of relation.source_columns) {
        if (
          !table.columns
            .find((column) => column.name === sourceColumn)!
            .relation_ids.includes(relation.relation_id)
        ) {
          throw new LogicalSchemaContractError(
            `${relation.relation_id} missing from source column metadata`,
          );
        }
      }
    }
    for (const key of table.unique_keys) {
      if (globalConstraintIds.has(key.key_id)) {
        throw new LogicalSchemaContractError(`Duplicate key id ${key.key_id}`);
      }
      globalConstraintIds.add(key.key_id);
      assertColumnsExist(table, key.columns, key.key_id);
    }
    for (const candidate of table.checks) {
      if (globalConstraintIds.has(candidate.check_id)) {
        throw new LogicalSchemaContractError(
          `Duplicate check id ${candidate.check_id}`,
        );
      }
      globalConstraintIds.add(candidate.check_id);
      assertColumnsExist(table, candidate.columns, candidate.check_id);
    }
    for (const candidate of table.indexes) {
      if (globalConstraintIds.has(candidate.index_id)) {
        throw new LogicalSchemaContractError(
          `Duplicate index id ${candidate.index_id}`,
        );
      }
      globalConstraintIds.add(candidate.index_id);
      assertColumnsExist(table, candidate.columns, candidate.index_id);
    }
  }
}

function validateRelations(
  source: LogicalSchemaSourcePayload,
  catalog: TypedRelationCatalogPayload,
): void {
  const expected = buildTypedRelationCatalogPayload();
  if (
    catalog.internal_relation_count !==
      catalog.relations.filter(
        (relation) => relation.relation_kind === 'foreign_key',
      ).length ||
    catalog.external_reference_count !==
      catalog.relations.filter(
        (relation) => relation.relation_kind === 'external_reference',
      ).length
  ) {
    throw new LogicalSchemaContractError('Typed relation count drift');
  }
  const expectedIds = new Set(
    expected.relations.map((relation) => relation.relation_id),
  );
  if (
    catalog.relations.length !== expectedIds.size ||
    catalog.relations.some((relation) => !expectedIds.has(relation.relation_id))
  ) {
    throw new LogicalSchemaContractError(
      'Typed relation catalog coverage drift',
    );
  }
  const tableNames = new Set(source.tables.map((table) => table.name));
  for (const relation of catalog.relations) {
    if (!tableNames.has(relation.source_table)) {
      throw new LogicalSchemaContractError(
        `${relation.relation_id} has unknown source table`,
      );
    }
    if (relation.relation_kind === 'foreign_key') {
      if (
        relation.target_table === null ||
        !tableNames.has(relation.target_table) ||
        relation.validator_owner !== null ||
        relation.reference_domain !== null ||
        relation.on_delete === null ||
        relation.deferrability === null
      ) {
        throw new LogicalSchemaContractError(
          `${relation.relation_id} internal target metadata drift`,
        );
      }
    } else if (
      relation.target_table !== null ||
      relation.target_columns.length !== 0 ||
      relation.on_delete !== null ||
      relation.deferrability !== null ||
      relation.validator_owner === null ||
      relation.reference_domain === null
    ) {
      throw new LogicalSchemaContractError(
        `${relation.relation_id} external validator metadata drift`,
      );
    }
  }
  if (
    canonicalJson(catalog as unknown as JsonValue) !==
    canonicalJson(expected as unknown as JsonValue)
  ) {
    throw new LogicalSchemaContractError(
      'Typed relation catalog exact metadata drift',
    );
  }
}

function validateQueries(
  source: LogicalSchemaSourcePayload,
  catalog: LogicalQueryCatalogPayload,
): void {
  if (
    catalog.executable_status !== 'non_executable' ||
    catalog.sql_text_status !== 'absent' ||
    catalog.query_count !== catalog.queries.length
  ) {
    throw new LogicalSchemaContractError(
      'Query catalog metadata-only boundary or count drift',
    );
  }
  const tables = new Map(source.tables.map((table) => [table.name, table]));
  const queryIds = new Set<string>();
  for (const query of catalog.queries) {
    if (queryIds.has(query.query_id)) {
      throw new LogicalSchemaContractError(
        `Duplicate query id ${query.query_id}`,
      );
    }
    queryIds.add(query.query_id);
    const table = tables.get(query.table);
    if (!table) {
      throw new LogicalSchemaContractError(
        `${query.query_id} targets unknown table`,
      );
    }
    for (const joinTable of query.join_tables) {
      if (!tables.has(joinTable)) {
        throw new LogicalSchemaContractError(
          `${query.query_id} joins unknown table`,
        );
      }
    }
    assertColumnsExist(
      table,
      [
        ...query.equality_columns,
        ...query.range_columns,
        ...query.order_by.map((order) => order.column),
      ],
      query.query_id,
    );
    const requiredIndex = table.indexes.find(
      (candidate) => candidate.index_id === query.required_index_id,
    );
    if (
      !requiredIndex ||
      !requiredIndex.supports_query_ids.includes(query.query_id)
    ) {
      throw new LogicalSchemaContractError(
        `${query.query_id} has no bidirectional required index intent`,
      );
    }
  }
  for (const table of source.tables) {
    for (const index of table.indexes) {
      for (const queryId of index.supports_query_ids) {
        if (!queryIds.has(queryId)) {
          throw new LogicalSchemaContractError(
            `${index.index_id} references unknown query ${queryId}`,
          );
        }
      }
    }
  }
}

function cloneObject(value: JsonObject): JsonObject {
  const clone = strictParseJson(JSON.stringify(value));
  assertJsonObject(clone);
  return clone;
}

function pointerTokens(pointer: string): string[] {
  if (!pointer.startsWith('/')) {
    throw new Error(`Fixture pointer must be absolute: ${pointer}`);
  }
  return pointer
    .slice(1)
    .split('/')
    .map((token) => token.replaceAll('~1', '/').replaceAll('~0', '~'));
}

function applyMutation(
  payload: JsonObject,
  mutation: LogicalSchemaMutation,
): void {
  const tokens = pointerTokens(mutation.pointer);
  const finalToken = tokens.pop();
  if (finalToken === undefined) throw new Error('Empty fixture pointer');
  let current: JsonValue = payload;
  for (const token of tokens) {
    if (Array.isArray(current)) current = current[Number(token)]!;
    else {
      assertJsonObject(current);
      current = current[token]!;
    }
  }
  if (Array.isArray(current)) {
    const index = Number(finalToken);
    if (mutation.operation === 'remove') current.splice(index, 1);
    else if (mutation.operation === 'add')
      current.splice(index, 0, mutation.value);
    else current[index] = mutation.value;
    return;
  }
  assertJsonObject(current);
  if (mutation.operation === 'remove') delete current[finalToken];
  else current[finalToken] = mutation.value;
}

function expectedSchemaError(
  errors: ErrorObject[] | null | undefined,
  testCase: LogicalSchemaNegativeCase,
): boolean {
  return Boolean(
    errors?.some(
      (error) =>
        error.keyword === testCase.expected_keyword &&
        error.instancePath === testCase.expected_instance_pointer,
    ),
  );
}

function expectedTargets(): Map<string, JsonObject> {
  return new Map([
    [
      'icarus.workflow-runtime-logical-schema-source/1',
      payloadAsJsonValue(buildLogicalSchemaSourcePayload()) as JsonObject,
    ],
    [
      'icarus.workflow-runtime-typed-relation-catalog/1',
      payloadAsJsonValue(buildTypedRelationCatalogPayload()) as JsonObject,
    ],
    [
      'icarus.workflow-runtime-query-catalog/1',
      payloadAsJsonValue(buildLogicalQueryCatalogPayload()) as JsonObject,
    ],
  ]);
}

function validateSemanticContract(
  targetFormat: string,
  payload: JsonObject,
  expected: Map<string, JsonObject>,
): void {
  const source =
    targetFormat === 'icarus.workflow-runtime-logical-schema-source/1'
      ? (payload as unknown as LogicalSchemaSourcePayload)
      : buildLogicalSchemaSourcePayload();
  validateSource(source);
  if (targetFormat === 'icarus.workflow-runtime-typed-relation-catalog/1') {
    validateRelations(
      source,
      payload as unknown as TypedRelationCatalogPayload,
    );
  } else if (targetFormat === 'icarus.workflow-runtime-query-catalog/1') {
    validateQueries(source, payload as unknown as LogicalQueryCatalogPayload);
  }
  const exact = expected.get(targetFormat);
  if (!exact || canonicalJson(payload) !== canonicalJson(exact)) {
    throw new LogicalSchemaContractError(
      `${targetFormat} exact baseline drift`,
    );
  }
}

function validateFixtures(
  validators: Map<string, ReturnType<Ajv2020['compile']>>,
  ajv: Ajv2020,
): void {
  const targets = expectedTargets();
  for (const testCase of LOGICAL_SCHEMA_POSITIVE_CASES) {
    const validate = validators.get(testCase.target_format);
    const target = targets.get(testCase.target_format);
    if (!validate || !target) throw new Error(`Unknown positive target`);
    if (!validate(target)) {
      throw new LogicalSchemaContractError(
        `Positive fixture ${testCase.case_id} failed: ${ajv.errorsText(validate.errors)}`,
      );
    }
    validateSemanticContract(testCase.target_format, target, targets);
  }
  for (const testCase of LOGICAL_SCHEMA_NEGATIVE_CASES) {
    const validate = validators.get(testCase.target_format);
    const target = targets.get(testCase.target_format);
    if (!validate || !target) throw new Error(`Unknown negative target`);
    const mutated = cloneObject(target);
    applyMutation(mutated, testCase.mutation);
    const accepted = validate(mutated);
    if (testCase.expected_stage === 'schema') {
      if (accepted || !expectedSchemaError(validate.errors, testCase)) {
        throw new LogicalSchemaContractError(
          `Negative fixture ${testCase.case_id} did not fail schema: ${ajv.errorsText(validate.errors)}`,
        );
      }
      continue;
    }
    if (!accepted) {
      throw new LogicalSchemaContractError(
        `Negative fixture ${testCase.case_id} failed schema early: ${ajv.errorsText(validate.errors)}`,
      );
    }
    try {
      validateSemanticContract(testCase.target_format, mutated, targets);
      throw new Error(`Negative fixture ${testCase.case_id} was accepted`);
    } catch (error) {
      if (
        !(error instanceof LogicalSchemaContractError) ||
        error.code !== testCase.expected_code
      ) {
        throw error;
      }
    }
  }
}

function validatePriorPackIdentity(): void {
  const expected = [
    ['contract-pack-foundation.json', foundationManifestHash],
    ['contract-pack-closed-schemas.json', closedSchemaManifestHash],
    [
      'contract-pack-catalog-protocols.json',
      currentReopenedCatalogProtocolManifestHash,
    ],
    [
      'contract-pack-safety-sqlite.json',
      currentReopenedSafetySqliteManifestHash,
    ],
  ] as const;
  for (const [relativePath, expectedHash] of expected) {
    if (readArtifact(relativePath).hash !== expectedHash) {
      throw new LogicalSchemaContractError(
        `Prior Contract Pack identity changed: ${relativePath}`,
      );
    }
  }
  const sqliteCandidate = readArtifact(
    'sqlite/local_single_user_sqlite@1.json',
  );
  if (
    sqliteCandidate.payload.certification_status !== 'candidate' ||
    sqliteCandidate.payload.sqlite_version !== null ||
    sqliteCandidate.payload.release_artifact_hash !== null
  ) {
    throw new LogicalSchemaContractError(
      'G0.6 must not certify or bind the SQLite candidate',
    );
  }
}

function validateDomainCatalog(
  artifacts: Array<[string, ContractArtifactEnvelope]>,
  manifest: ContractArtifactEnvelope,
): void {
  const domain = artifacts.find(
    ([relativePath]) => relativePath === domainCatalogPath,
  )?.[1];
  if (!domain || !Array.isArray(domain.payload.entries)) {
    throw new LogicalSchemaContractError('Missing G0.6 domain catalog');
  }
  const expectedFormats = new Set([
    ...artifacts
      .filter(([relativePath]) => relativePath !== domainCatalogPath)
      .map(([, artifact]) => artifact.format),
    domain.format,
    manifest.format,
  ]);
  const actualFormats = new Set(
    domain.payload.entries.map((entry) => {
      assertJsonObject(entry);
      return String(entry.format);
    }),
  );
  if (
    actualFormats.size !== expectedFormats.size ||
    [...expectedFormats].some((format) => !actualFormats.has(format))
  ) {
    throw new LogicalSchemaContractError('G0.6 domain coverage drift');
  }
}

function validatePack(
  artifacts: Array<[string, ContractArtifactEnvelope]>,
  manifest: ContractArtifactEnvelope,
): void {
  validatePriorPackIdentity();
  validateTypeScriptConformance();
  const { ajv, validators, schemasByTarget } = compileSchemas(artifacts);
  validateSchemaTypeScriptConformance(schemasByTarget);
  const targets = expectedTargets();
  for (const [targetFormat, target] of targets) {
    const validate = validators.get(targetFormat);
    if (!validate || !validate(target)) {
      throw new LogicalSchemaContractError(
        `${targetFormat} failed closed schema: ${ajv.errorsText(validate?.errors)}`,
      );
    }
    validateSemanticContract(targetFormat, target, targets);
  }
  validateRelations(
    buildLogicalSchemaSourcePayload(),
    buildTypedRelationCatalogPayload(),
  );
  validateQueries(
    buildLogicalSchemaSourcePayload(),
    buildLogicalQueryCatalogPayload(),
  );
  validateFixtures(validators, ajv);
  validateDomainCatalog(artifacts, manifest);
  if (
    LOGICAL_SCHEMA_FORMAT_BY_TARGET[
      'icarus.workflow-runtime-logical-schema-source/1'
    ] !== 'icarus.workflow-runtime-logical-schema-source-schema/1'
  ) {
    throw new LogicalSchemaContractError('Schema target mapping drift');
  }
}

export function generateContractPackLogicalSchema(): ContractArtifactEnvelope {
  const artifacts = expectedArtifacts();
  const manifest = buildManifest(artifacts);
  validatePack(artifacts, manifest);
  for (const [relativePath, artifact] of artifacts) {
    writeAtomicFile(relativePath, artifact);
  }
  writeAtomicFile(manifestPath, manifest);
  return manifest;
}

export function checkContractPackLogicalSchema(): ContractArtifactEnvelope {
  const artifacts = expectedArtifacts();
  const manifest = buildManifest(artifacts);
  validatePack(artifacts, manifest);
  for (const [relativePath, artifact] of artifacts) {
    assertExpectedBytes(relativePath, artifact);
  }
  assertExpectedBytes(manifestPath, manifest);
  return manifest;
}
