import fs from 'fs';
import path from 'path';

import { Ajv2020, type AnySchema, type ErrorObject } from 'ajv/dist/2020.js';

import { parseContractArtifactEnvelope } from './artifact.js';
import {
  SAFETY_SQLITE_ARTIFACT_DESCRIPTORS,
  SAFETY_SQLITE_NESTED_TYPESCRIPT_KEYS,
  SAFETY_SQLITE_SCHEMA_FORMAT_BY_TARGET,
  SAFETY_SQLITE_TYPESCRIPT_KEYS,
  buildDeploymentRuntimeCapacityBaseline,
  buildSafetySqliteArtifact,
  buildSafetySqliteSemanticArtifacts,
  payloadAsJsonValue,
} from './safety-sqlite-artifacts.js';
import {
  SAFETY_SQLITE_NEGATIVE_CASES,
  SAFETY_SQLITE_POSITIVE_CASES,
  type SafetySqliteMutation,
  type SafetySqliteNegativeCase,
} from './safety-sqlite-fixtures.js';
import {
  CAPACITY_LIMIT_PATHS,
  DEPLOYMENT_CAPACITY_RELOAD_CONTRACT,
  DEPLOYMENT_CAPACITY_KEYS,
  ENFORCEMENT_RECORD_KEYS,
  LOCAL_SINGLE_USER_PRODUCT_FLOOR,
  LOCAL_SINGLE_USER_RETENTION_POLICY,
  LOCAL_SINGLE_USER_SAFETY_PROFILE,
  LOCAL_SINGLE_USER_SQLITE_PROFILE,
  PRODUCT_FLOOR_BENCHMARK_KEYS,
  PRODUCT_FLOOR_LIMIT_KEYS,
  RETENTION_DURATION_KEYS,
  RETENTION_RULE_KEYS,
  SAFETY_CEILING_GROUP_KEYS,
  SAFETY_LIMIT_PATHS,
  SQLITE_PROFILE_KEYS,
} from './safety-sqlite-types.js';
import {
  calculateArtifactHash,
  canonicalJson,
  domainSeparatedSha256,
} from './hash.js';
import {
  assertJsonObject,
  strictParseJson,
  strictParseJsonBytes,
} from './strict-json.js';
import type {
  ContractArtifactEnvelope,
  JsonObject,
  JsonValue,
} from './types.js';

const contractsRoot = import.meta.dirname;
const repositoryRoot = path.resolve(contractsRoot, '../../..');
const manifestPath = 'contract-pack-safety-sqlite.json';
const positiveCasesPath = 'conformance/safety-sqlite/positive-cases.json';
const negativeCasesPath = 'conformance/safety-sqlite/negative-cases.json';
const domainCatalogPath = 'catalogs/safety-sqlite-domain-separators.json';
const capacityConfigPath = 'config/workflow-runtime-capacity.json';

export class SafetySqliteContractError extends Error {
  readonly code = 'safety_sqlite_contract_drift';

  constructor(message: string) {
    super(message);
    this.name = 'SafetySqliteContractError';
  }
}

function asciiCompare(left: string, right: string): number {
  return left < right ? -1 : left > right ? 1 : 0;
}

function absoluteContractPath(relativePath: string): string {
  const absolute = path.resolve(contractsRoot, relativePath);
  if (!absolute.startsWith(`${contractsRoot}${path.sep}`)) {
    throw new Error(`Contract path escapes root: ${relativePath}`);
  }
  return absolute;
}

function absoluteRepositoryPath(relativePath: string): string {
  const absolute = path.resolve(repositoryRoot, relativePath);
  if (!absolute.startsWith(`${repositoryRoot}${path.sep}`)) {
    throw new Error(`Repository path escapes root: ${relativePath}`);
  }
  return absolute;
}

function renderJson(value: JsonValue): string {
  return `${JSON.stringify(value, null, 2)}\n`;
}

function writeAtomicFile(absoluteFile: string, value: JsonValue): void {
  fs.mkdirSync(path.dirname(absoluteFile), { recursive: true });
  const temporary = `${absoluteFile}.tmp-${process.pid}`;
  fs.writeFileSync(temporary, renderJson(value), {
    encoding: 'utf8',
    mode: 0o644,
  });
  fs.renameSync(temporary, absoluteFile);
}

function writeContractArtifact(
  relativePath: string,
  artifact: ContractArtifactEnvelope,
): void {
  writeAtomicFile(absoluteContractPath(relativePath), artifact);
}

function assertExpectedContractBytes(
  relativePath: string,
  expected: ContractArtifactEnvelope,
): void {
  const actual = fs.readFileSync(absoluteContractPath(relativePath), 'utf8');
  if (actual !== renderJson(expected)) {
    throw new Error(
      `${relativePath} is not generated byte-for-byte; run npm run contracts:generate`,
    );
  }
}

function readArtifact(relativePath: string): ContractArtifactEnvelope {
  return parseContractArtifactEnvelope(
    strictParseJsonBytes(fs.readFileSync(absoluteContractPath(relativePath))),
  );
}

function buildFixtureArtifacts(): Array<[string, ContractArtifactEnvelope]> {
  return [
    [
      positiveCasesPath,
      buildSafetySqliteArtifact(
        'icarus.workflow-safety-sqlite-positive-cases/1',
        'icarus.workflow-safety-sqlite-positive-cases',
        'icarus:workflow-safety-sqlite-positive-cases:1\n',
        { cases: SAFETY_SQLITE_POSITIVE_CASES },
      ),
    ],
    [
      negativeCasesPath,
      buildSafetySqliteArtifact(
        'icarus.workflow-safety-sqlite-negative-cases/1',
        'icarus.workflow-safety-sqlite-negative-cases',
        'icarus:workflow-safety-sqlite-negative-cases:1\n',
        { cases: SAFETY_SQLITE_NEGATIVE_CASES },
      ),
    ],
  ];
}

function buildDomainCatalog(
  priorArtifacts: Array<[string, ContractArtifactEnvelope]>,
): ContractArtifactEnvelope {
  const entries = [
    ...priorArtifacts.map(([, artifact]) => ({
      format: artifact.format,
      domain_separator: artifact.domain_separator,
    })),
    {
      format: 'icarus.deployment-runtime-capacity/1',
      domain_separator: 'icarus:deployment-runtime-capacity:1\n',
    },
    {
      format: 'icarus.workflow-safety-enforcement-record/1',
      domain_separator: 'icarus:workflow-safety-enforcement-record:1\n',
    },
    {
      format: 'icarus.workflow-safety-sqlite-domain-separators/1',
      domain_separator: 'icarus:workflow-safety-sqlite-domain-separators:1\n',
    },
    {
      format: 'icarus.workflow-contract-pack-safety-sqlite/1',
      domain_separator: 'icarus:workflow-contract-pack-safety-sqlite:1\n',
    },
  ].sort((left, right) => asciiCompare(left.format, right.format));
  return buildSafetySqliteArtifact(
    'icarus.workflow-safety-sqlite-domain-separators/1',
    'icarus.workflow-safety-sqlite-domain-separators',
    'icarus:workflow-safety-sqlite-domain-separators:1\n',
    { entries },
  );
}

function artifactDescriptor(
  artifactPath: string,
  artifact: ContractArtifactEnvelope,
): JsonObject {
  return {
    path: artifactPath,
    format: artifact.format,
    ref: artifact.ref,
    version: artifact.version,
    domain_separator: artifact.domain_separator,
    hash: artifact.hash,
  };
}

function buildManifest(
  artifacts: Array<[string, ContractArtifactEnvelope]>,
  capacityConfig: JsonObject,
): ContractArtifactEnvelope {
  return buildSafetySqliteArtifact(
    'icarus.workflow-contract-pack-safety-sqlite/1',
    'icarus.workflow-contract-pack-safety-sqlite',
    'icarus:workflow-contract-pack-safety-sqlite:1\n',
    {
      gate: 'G0.5',
      status: 'safety_retention_sqlite_contracts',
      schema_count: SAFETY_SQLITE_ARTIFACT_DESCRIPTORS.filter(
        (descriptor) => descriptor.artifact_kind === 'schema',
      ).length,
      safety_limit_count: SAFETY_LIMIT_PATHS.length,
      capacity_limit_count: CAPACITY_LIMIT_PATHS.length,
      enforcement_record_count:
        SAFETY_LIMIT_PATHS.length + CAPACITY_LIMIT_PATHS.length,
      positive_case_count: SAFETY_SQLITE_POSITIVE_CASES.length,
      negative_case_count: SAFETY_SQLITE_NEGATIVE_CASES.length,
      sqlite_profile_status: 'operational',
      artifacts: artifacts
        .map(([artifactPath, artifact]) =>
          artifactDescriptor(artifactPath, artifact),
        )
        .sort((left, right) =>
          asciiCompare(String(left.path), String(right.path)),
        ),
      capacity_baseline: {
        path: capacityConfigPath,
        format: 'icarus.deployment-runtime-capacity/1',
        hash: capacityConfig.config_hash!,
      },
      capacity_reload_contract: DEPLOYMENT_CAPACITY_RELOAD_CONTRACT,
      explicitly_absent_artifacts: [
        'runtime_supported_limits_certification',
        'executable_ddl',
        'schema_manifest',
        'query_catalog',
        'sealed_golden_bundle',
      ],
    },
  );
}

function expectedArtifacts(): Array<[string, ContractArtifactEnvelope]> {
  const semantic = buildSafetySqliteSemanticArtifacts();
  const fixtures = buildFixtureArtifacts();
  const prior = [...semantic, ...fixtures];
  return [...prior, [domainCatalogPath, buildDomainCatalog(prior)]];
}

function expectedTargetPayloads(
  artifacts: Array<[string, ContractArtifactEnvelope]>,
  capacity: JsonObject,
): Map<string, JsonObject> {
  const targetPayloads = new Map<string, JsonObject>([
    ['icarus.deployment-runtime-capacity/1', capacity],
  ]);
  for (const [, artifact] of artifacts) {
    if (SAFETY_SQLITE_SCHEMA_FORMAT_BY_TARGET[artifact.format]) {
      targetPayloads.set(artifact.format, artifact.payload);
    }
  }
  return targetPayloads;
}

function schemaProperties(schema: JsonObject): JsonObject {
  assertJsonObject(schema.properties);
  return schema.properties;
}

function assertKeyset(
  actual: readonly string[],
  expected: readonly string[],
  label: string,
): void {
  const actualSorted = [...actual].sort(asciiCompare);
  const expectedSorted = [...expected].sort(asciiCompare);
  if (actualSorted.join('\n') !== expectedSorted.join('\n')) {
    throw new SafetySqliteContractError(`${label} TypeScript/schema key drift`);
  }
}

function validateTypeScriptSchemaConformance(
  schemasByTarget: Map<string, JsonObject>,
): void {
  for (const [targetFormat, expectedKeys] of Object.entries(
    SAFETY_SQLITE_TYPESCRIPT_KEYS,
  )) {
    const schema = schemasByTarget.get(targetFormat);
    if (!schema) throw new Error(`Missing G0.5 schema for ${targetFormat}`);
    assertKeyset(
      Object.keys(schemaProperties(schema)),
      expectedKeys,
      targetFormat,
    );
  }

  const safety = schemasByTarget.get(
    'icarus.workflow-runtime-safety-profile/1',
  )!;
  const safetyProperties = schemaProperties(safety);
  assertJsonObject(safetyProperties.ceilings);
  const ceilingGroups = schemaProperties(safetyProperties.ceilings);
  assertKeyset(
    Object.keys(ceilingGroups),
    Object.keys(SAFETY_CEILING_GROUP_KEYS),
    'Safety groups',
  );
  for (const [group, expectedKeys] of Object.entries(
    SAFETY_CEILING_GROUP_KEYS,
  )) {
    assertJsonObject(ceilingGroups[group]);
    assertKeyset(
      Object.keys(schemaProperties(ceilingGroups[group])),
      expectedKeys,
      `Safety ${group}`,
    );
  }

  const floor = schemasByTarget.get('icarus.workflow-runtime-product-floor/1')!;
  const floorProperties = schemaProperties(floor);
  assertJsonObject(floorProperties.limits);
  assertJsonObject(floorProperties.benchmark_requirements);
  assertKeyset(
    Object.keys(schemaProperties(floorProperties.limits)),
    PRODUCT_FLOOR_LIMIT_KEYS,
    'Product floor limits',
  );
  assertKeyset(
    Object.keys(schemaProperties(floorProperties.benchmark_requirements)),
    PRODUCT_FLOOR_BENCHMARK_KEYS,
    'Product floor benchmark',
  );

  const retention = schemasByTarget.get(
    'icarus.workflow-runtime-retention-policy/1',
  )!;
  const retentionProperties = schemaProperties(retention);
  assertJsonObject(retentionProperties.durations_ms);
  assertJsonObject(retentionProperties.rules);
  assertKeyset(
    Object.keys(schemaProperties(retentionProperties.durations_ms)),
    RETENTION_DURATION_KEYS,
    'Retention durations',
  );
  assertKeyset(
    Object.keys(schemaProperties(retentionProperties.rules)),
    RETENTION_RULE_KEYS,
    'Retention rules',
  );

  const matrix = schemasByTarget.get(
    'icarus.workflow-safety-enforcement-matrix/1',
  )!;
  assertJsonObject(matrix.$defs);
  assertJsonObject(matrix.$defs.enforcement_record);
  assertKeyset(
    Object.keys(schemaProperties(matrix.$defs.enforcement_record)),
    ENFORCEMENT_RECORD_KEYS,
    'Enforcement record',
  );

  assertKeyset(
    Object.keys(LOCAL_SINGLE_USER_PRODUCT_FLOOR.limits),
    SAFETY_SQLITE_NESTED_TYPESCRIPT_KEYS.product_floor_limits,
    'Product floor TypeScript limits',
  );
  assertKeyset(
    Object.keys(LOCAL_SINGLE_USER_PRODUCT_FLOOR.benchmark_requirements),
    SAFETY_SQLITE_NESTED_TYPESCRIPT_KEYS.product_floor_benchmark,
    'Product floor TypeScript benchmark',
  );
  assertKeyset(
    Object.keys(LOCAL_SINGLE_USER_RETENTION_POLICY.durations_ms),
    SAFETY_SQLITE_NESTED_TYPESCRIPT_KEYS.retention_durations,
    'Retention TypeScript durations',
  );
  assertKeyset(
    Object.keys(LOCAL_SINGLE_USER_RETENTION_POLICY.rules),
    SAFETY_SQLITE_NESTED_TYPESCRIPT_KEYS.retention_rules,
    'Retention TypeScript rules',
  );
  assertKeyset(
    Object.keys(LOCAL_SINGLE_USER_SQLITE_PROFILE),
    SQLITE_PROFILE_KEYS,
    'SQLite profile TypeScript keys',
  );
  assertKeyset(
    DEPLOYMENT_CAPACITY_KEYS,
    SAFETY_SQLITE_TYPESCRIPT_KEYS['icarus.deployment-runtime-capacity/1'],
    'Capacity TypeScript keys',
  );
}

function validateClosedObjects(value: JsonValue, pointer = ''): void {
  if (Array.isArray(value)) {
    value.forEach((child, index) =>
      validateClosedObjects(child, `${pointer}/${index}`),
    );
    return;
  }
  if (value === null || typeof value !== 'object') return;
  const objectValue = value as JsonObject;
  if (
    objectValue.type === 'object' &&
    objectValue.additionalProperties !== false
  ) {
    throw new SafetySqliteContractError(
      `Open G0.5 object schema at ${pointer || '/'}`,
    );
  }
  for (const [key, child] of Object.entries(objectValue)) {
    validateClosedObjects(child, `${pointer}/${key}`);
  }
}

function compileSchemas(artifacts: Array<[string, ContractArtifactEnvelope]>): {
  ajv: Ajv2020;
  validators: Map<string, ReturnType<Ajv2020['compile']>>;
  schemasByTarget: Map<string, JsonObject>;
} {
  const ajv = new Ajv2020({
    allErrors: true,
    coerceTypes: false,
    removeAdditional: false,
    strict: true,
    useDefaults: false,
  });
  const validators = new Map<string, ReturnType<Ajv2020['compile']>>();
  const schemasByTarget = new Map<string, JsonObject>();
  for (const descriptor of SAFETY_SQLITE_ARTIFACT_DESCRIPTORS.filter(
    (candidate) => candidate.artifact_kind === 'schema',
  )) {
    const artifact = artifacts.find(
      ([artifactPath]) => artifactPath === descriptor.artifact_path,
    )?.[1];
    if (!artifact || descriptor.target_format === null) {
      throw new Error(
        `Missing G0.5 schema artifact ${descriptor.artifact_path}`,
      );
    }
    validateClosedObjects(artifact.payload);
    schemasByTarget.set(descriptor.target_format, artifact.payload);
    validators.set(
      descriptor.target_format,
      ajv.compile(artifact.payload as AnySchema),
    );
  }
  validateTypeScriptSchemaConformance(schemasByTarget);
  return { ajv, validators, schemasByTarget };
}

function cloneObject(value: JsonObject): JsonObject {
  const clone = strictParseJson(JSON.stringify(value));
  assertJsonObject(clone);
  return clone;
}

function pointerTokens(pointer: string): string[] {
  if (!pointer.startsWith('/')) {
    throw new Error(`Fixture JSON pointer must be absolute: ${pointer}`);
  }
  return pointer
    .slice(1)
    .split('/')
    .map((token) => token.replaceAll('~1', '/').replaceAll('~0', '~'));
}

function applyMutation(
  payload: JsonObject,
  mutation: SafetySqliteMutation,
): void {
  const tokens = pointerTokens(mutation.pointer);
  const finalToken = tokens.pop();
  if (finalToken === undefined)
    throw new Error('Fixture pointer cannot be empty');
  let current: JsonValue = payload;
  for (const token of tokens) {
    if (Array.isArray(current)) current = current[Number(token)]!;
    else {
      assertJsonObject(current);
      current = current[token]!;
    }
  }
  if (Array.isArray(current)) {
    const index = Number(finalToken);
    if (mutation.operation === 'remove') current.splice(index, 1);
    else if (mutation.operation === 'add')
      current.splice(index, 0, mutation.value);
    else current[index] = mutation.value;
    return;
  }
  assertJsonObject(current);
  if (mutation.operation === 'remove') delete current[finalToken];
  else current[finalToken] = mutation.value;
}

function expectedSchemaError(
  errors: ErrorObject[] | null | undefined,
  testCase: SafetySqliteNegativeCase,
): boolean {
  return Boolean(
    errors?.some(
      (error) =>
        error.keyword === testCase.expected_keyword &&
        error.instancePath === testCase.expected_instance_pointer,
    ),
  );
}

function withoutKey(objectValue: JsonObject, key: string): JsonObject {
  return Object.fromEntries(
    Object.entries(objectValue).filter(([candidate]) => candidate !== key),
  );
}

function validateCapacitySemantic(payload: JsonObject): void {
  const expectedHash = domainSeparatedSha256(
    'icarus:deployment-runtime-capacity:1\n',
    withoutKey(payload, 'config_hash'),
  );
  if (
    payload.config_hash !== expectedHash ||
    Number(payload.soft_blob_high_water_bytes) >=
      Number(payload.max_physical_blob_bytes)
  ) {
    throw new SafetySqliteContractError(
      'Deployment Capacity hash or blob watermark invariant drift',
    );
  }
}

function validateProductFloorSemantic(payload: JsonObject): void {
  assertJsonObject(payload.limits);
  const safety = LOCAL_SINGLE_USER_SAFETY_PROFILE.ceilings;
  const expectedByFloorKey: Record<string, number> = {
    max_scopes_total: safety.run.max_scopes_total,
    max_nodes_total: safety.run.max_nodes_total,
    max_nodes_per_scope: safety.scope.max_nodes_per_scope,
    max_edges_total: safety.run.max_edges_total,
    max_edges_per_scope: safety.scope.max_edges_per_scope,
    max_map_items_total: safety.run.max_map_items_total,
    max_items_per_map: safety.map.max_items_per_map,
    max_attempts_total: safety.run.max_attempts_total,
    max_waits_total: safety.run.max_waits_total,
    max_builds_total: safety.run.max_builds_total,
    max_effect_operations_total: safety.run.max_effect_operations_total,
    max_facts_per_transaction: safety.reconciliation.max_facts_per_transaction,
    max_frontier_bytes: safety.scope.max_frontier_bytes,
    max_nesting_depth: safety.scope.max_nesting_depth,
    max_required_child_creations_per_t8:
      safety.workflow.max_required_child_creations_per_transition,
  };
  for (const [key, expected] of Object.entries(expectedByFloorKey)) {
    if (payload.limits[key] !== expected) {
      throw new SafetySqliteContractError(
        `Product Floor is not aligned with Safety at ${key}`,
      );
    }
  }
}

function validateRetentionSemantic(payload: JsonObject): void {
  assertJsonObject(payload.durations_ms);
  if (
    payload.durations_ms.pending_signal_safety_ttl_ms !==
      LOCAL_SINGLE_USER_SAFETY_PROFILE.ceilings.wait
        .max_pending_signal_age_ms ||
    Number(payload.durations_ms.workflow_audit_metadata_retention_ms) <
      Number(payload.durations_ms.workflow_audit_payload_retention_ms) ||
    Number(
      payload.durations_ms.inbox_rejected_late_unmatched_audit_retention_ms,
    ) <
      Number(
        payload.durations_ms.inbox_rejected_late_unmatched_payload_retention_ms,
      )
  ) {
    throw new SafetySqliteContractError(
      'Retention cross-contract invariant drift',
    );
  }
}

function validateMatrixSemantic(payload: JsonObject): void {
  if (!Array.isArray(payload.records)) {
    throw new SafetySqliteContractError(
      'Enforcement Matrix records are missing',
    );
  }
  const expectedPaths = [...SAFETY_LIMIT_PATHS, ...CAPACITY_LIMIT_PATHS].sort(
    asciiCompare,
  );
  const actualPaths: string[] = [];
  for (const recordValue of payload.records) {
    assertJsonObject(recordValue);
    const limitPath = String(recordValue.limit_path);
    actualPaths.push(limitPath);
    if (limitPath.includes('*') || recordValue.reservation_point === null) {
      throw new SafetySqliteContractError(
        `Enforcement record lacks a concrete path/checkpoint: ${limitPath}`,
      );
    }
    const expectedRecordHash = domainSeparatedSha256(
      'icarus:workflow-safety-enforcement-record:1\n',
      withoutKey(recordValue, 'record_hash'),
    );
    if (recordValue.record_hash !== expectedRecordHash) {
      throw new SafetySqliteContractError(
        `Enforcement record hash drift: ${limitPath}`,
      );
    }
    const capacity = limitPath.startsWith('capacity.');
    if (
      recordValue.included_in_plan_hash === capacity ||
      (capacity &&
        (recordValue.supported_limit_path !== null ||
          recordValue.t7_fence_dimension !== null))
    ) {
      throw new SafetySqliteContractError(
        `Enforcement Plan/Supported mapping drift: ${limitPath}`,
      );
    }
  }
  if (
    actualPaths.sort(asciiCompare).join('\n') !== expectedPaths.join('\n') ||
    new Set(actualPaths).size !== actualPaths.length
  ) {
    throw new SafetySqliteContractError(
      'Enforcement Matrix must own each Safety/Capacity field exactly once',
    );
  }
}

function validateSemanticContract(
  targetFormat: string,
  payload: JsonObject,
  expectedTargets: Map<string, JsonObject>,
): void {
  const expected = expectedTargets.get(targetFormat);
  if (!expected) throw new Error(`Unknown G0.5 target ${targetFormat}`);
  switch (targetFormat) {
    case 'icarus.workflow-runtime-safety-profile/1': {
      const workflow = payload.ceilings as JsonObject;
      assertJsonObject(workflow);
      assertJsonObject(workflow.workflow);
      if (
        Number(workflow.workflow.max_graph_runs) >
        Number(workflow.workflow.max_state_activations) - 1
      ) {
        throw new SafetySqliteContractError(
          'Safety does not reserve a terminal activation',
        );
      }
      break;
    }
    case 'icarus.deployment-runtime-capacity/1':
      validateCapacitySemantic(payload);
      break;
    case 'icarus.workflow-runtime-product-floor/1':
      validateProductFloorSemantic(payload);
      break;
    case 'icarus.workflow-runtime-retention-policy/1':
      validateRetentionSemantic(payload);
      break;
    case 'icarus.workflow-safety-enforcement-matrix/1':
      validateMatrixSemantic(payload);
      break;
    case 'icarus.sqlite-execution-profile/1':
      break;
    default:
      throw new Error(`Unhandled G0.5 target ${targetFormat}`);
  }
  if (canonicalJson(payload) !== canonicalJson(expected)) {
    throw new SafetySqliteContractError(`${targetFormat} exact baseline drift`);
  }
}

function validateFixtures(
  validators: Map<string, ReturnType<Ajv2020['compile']>>,
  ajv: Ajv2020,
  expectedTargets: Map<string, JsonObject>,
): void {
  for (const testCase of SAFETY_SQLITE_POSITIVE_CASES) {
    const validate = validators.get(testCase.target_format);
    const target = expectedTargets.get(testCase.target_format);
    if (!validate || !target) {
      throw new Error(`Unknown G0.5 positive target ${testCase.target_format}`);
    }
    if (!validate(target)) {
      throw new Error(
        `Positive fixture ${testCase.case_id} failed: ${ajv.errorsText(validate.errors)}`,
      );
    }
    validateSemanticContract(testCase.target_format, target, expectedTargets);
  }

  for (const testCase of SAFETY_SQLITE_NEGATIVE_CASES) {
    const validate = validators.get(testCase.target_format);
    const target = expectedTargets.get(testCase.target_format);
    if (!validate || !target) {
      throw new Error(`Unknown G0.5 negative target ${testCase.target_format}`);
    }
    const mutated = cloneObject(target);
    applyMutation(mutated, testCase.mutation);
    const schemaAccepted = validate(mutated);
    if (testCase.expected_stage === 'schema') {
      if (schemaAccepted || !expectedSchemaError(validate.errors, testCase)) {
        throw new SafetySqliteContractError(
          `Negative fixture ${testCase.case_id} did not fail schema as expected: ${ajv.errorsText(validate.errors)}`,
        );
      }
      continue;
    }
    if (!schemaAccepted) {
      throw new SafetySqliteContractError(
        `Negative fixture ${testCase.case_id} failed schema before semantic validation: ${ajv.errorsText(validate.errors)}`,
      );
    }
    try {
      validateSemanticContract(
        testCase.target_format,
        mutated,
        expectedTargets,
      );
      throw new Error(`Negative fixture ${testCase.case_id} was accepted`);
    } catch (error) {
      if (
        !(error instanceof SafetySqliteContractError) ||
        error.code !== testCase.expected_code
      ) {
        throw error;
      }
    }
  }
}

function validateVersionedRefConformance(
  schemasByTarget: Map<string, JsonObject>,
): void {
  const foundationSchema = readArtifact(
    'foundation/versioned-ref-schema.json',
  ).payload;
  const expectedEmbedded = Object.fromEntries(
    Object.entries(foundationSchema).filter(
      ([key]) => !['$schema', '$id', 'title'].includes(key),
    ),
  );
  for (const targetFormat of ['icarus.workflow-safety-enforcement-matrix/1']) {
    const schema = schemasByTarget.get(targetFormat);
    if (!schema) throw new Error(`Missing schema for ${targetFormat}`);
    assertJsonObject(schema.$defs);
    assertJsonObject(schema.$defs.versioned_ref);
    if (
      canonicalJson(schema.$defs.versioned_ref) !==
      canonicalJson(expectedEmbedded)
    ) {
      throw new SafetySqliteContractError(
        `${targetFormat} VersionedRef semantics drift from G0.2`,
      );
    }
  }
}

function validateDomainCatalog(
  artifacts: Array<[string, ContractArtifactEnvelope]>,
  manifest: ContractArtifactEnvelope,
): void {
  const catalog = artifacts.find(
    ([artifactPath]) => artifactPath === domainCatalogPath,
  )?.[1];
  if (!catalog || !Array.isArray(catalog.payload.entries)) {
    throw new Error('G0.5 domain catalog is missing');
  }
  const expectedEntries = [
    ...artifacts.map(([, artifact]) => ({
      format: artifact.format,
      domain_separator: artifact.domain_separator,
    })),
    {
      format: 'icarus.deployment-runtime-capacity/1',
      domain_separator: 'icarus:deployment-runtime-capacity:1\n',
    },
    {
      format: 'icarus.workflow-safety-enforcement-record/1',
      domain_separator: 'icarus:workflow-safety-enforcement-record:1\n',
    },
    {
      format: manifest.format,
      domain_separator: manifest.domain_separator,
    },
  ];
  const expectedByFormat = new Map(
    expectedEntries.map((entry) => [entry.format, entry.domain_separator]),
  );
  const seenFormats = new Set<string>();
  const seenDomains = new Set<string>();
  for (const entryValue of catalog.payload.entries) {
    assertJsonObject(entryValue);
    assertKeyset(
      Object.keys(entryValue),
      ['format', 'domain_separator'],
      'G0.5 domain entry',
    );
    const format = String(entryValue.format);
    const domain = String(entryValue.domain_separator);
    if (
      expectedByFormat.get(format) !== domain ||
      seenFormats.has(format) ||
      seenDomains.has(domain)
    ) {
      throw new Error('G0.5 domain catalog is not one-to-one and complete');
    }
    seenFormats.add(format);
    seenDomains.add(domain);
  }
  if (seenFormats.size !== expectedByFormat.size) {
    throw new Error('G0.5 domain catalog coverage drift');
  }
}

function validateDirectoryBoundaries(): void {
  const expectedSafetyFiles = SAFETY_SQLITE_ARTIFACT_DESCRIPTORS.filter(
    (descriptor) => descriptor.artifact_path.startsWith('safety/'),
  )
    .map((descriptor) => path.basename(descriptor.artifact_path))
    .sort(asciiCompare);
  const actualSafetyFiles = fs
    .readdirSync(absoluteContractPath('safety'))
    .sort(asciiCompare);
  if (actualSafetyFiles.join('\n') !== expectedSafetyFiles.join('\n')) {
    throw new Error(
      'Safety directory contains missing or out-of-slice artifacts',
    );
  }

  const expectedSqliteFiles = SAFETY_SQLITE_ARTIFACT_DESCRIPTORS.filter(
    (descriptor) => descriptor.artifact_path.startsWith('sqlite/'),
  )
    .map((descriptor) => path.basename(descriptor.artifact_path))
    .sort(asciiCompare);
  const actualSqliteFiles = fs
    .readdirSync(absoluteContractPath('sqlite'))
    .sort(asciiCompare);
  const allowedSqliteFiles = new Set([
    ...expectedSqliteFiles,
    'workflow-runtime-logical-schema-source-schema.json',
    'workflow-runtime-logical-schema-source@1.json',
    'workflow-runtime-query-catalog-schema.json',
    'workflow-runtime-query-catalog@1.json',
    'workflow-runtime-typed-relation-catalog-schema.json',
    'workflow-runtime-typed-relation-catalog@1.json',
  ]);
  if (
    expectedSqliteFiles.some((file) => !actualSqliteFiles.includes(file)) ||
    actualSqliteFiles.some((file) => !allowedSqliteFiles.has(file))
  ) {
    throw new Error(
      'SQLite directory contains missing or out-of-slice artifacts',
    );
  }

  const fixtureFiles = fs
    .readdirSync(absoluteContractPath('conformance/safety-sqlite'))
    .sort(asciiCompare);
  if (fixtureFiles.join('\n') !== 'negative-cases.json\npositive-cases.json') {
    throw new Error('G0.5 fixture directory boundary drift');
  }
  const capacityPath = absoluteRepositoryPath(capacityConfigPath);
  if (!fs.lstatSync(capacityPath).isFile()) {
    throw new Error('Deployment Capacity baseline is not a regular file');
  }
}

function validateCompletePack(
  artifacts: Array<[string, ContractArtifactEnvelope]>,
  capacity: JsonObject,
  manifest: ContractArtifactEnvelope,
): void {
  for (const [, artifact] of artifacts) {
    parseContractArtifactEnvelope(artifact);
    if (artifact.hash !== calculateArtifactHash(artifact)) {
      throw new SafetySqliteContractError(`${artifact.format} hash drift`);
    }
  }
  const { ajv, validators, schemasByTarget } = compileSchemas(artifacts);
  validateVersionedRefConformance(schemasByTarget);
  const expectedTargets = expectedTargetPayloads(artifacts, capacity);
  for (const [targetFormat, target] of expectedTargets) {
    const validate = validators.get(targetFormat);
    if (!validate || !validate(target)) {
      throw new SafetySqliteContractError(
        `${targetFormat} failed its closed schema: ${ajv.errorsText(validate?.errors)}`,
      );
    }
    validateSemanticContract(targetFormat, target, expectedTargets);
  }
  validateFixtures(validators, ajv, expectedTargets);
  validateDomainCatalog(artifacts, manifest);
  validateDirectoryBoundaries();
}

export function generateContractPackSafetySqlite(): ContractArtifactEnvelope {
  const capacity = payloadAsJsonValue(buildDeploymentRuntimeCapacityBaseline());
  assertJsonObject(capacity);
  const artifacts = expectedArtifacts();
  fs.rmSync(absoluteContractPath('safety/.gitkeep'), { force: true });
  fs.rmSync(absoluteContractPath('sqlite/.gitkeep'), { force: true });
  for (const [artifactPath, artifact] of artifacts) {
    writeContractArtifact(artifactPath, artifact);
  }
  writeAtomicFile(absoluteRepositoryPath(capacityConfigPath), capacity);
  const manifest = buildManifest(artifacts, capacity);
  writeContractArtifact(manifestPath, manifest);
  validateCompletePack(artifacts, capacity, manifest);
  return manifest;
}

export function checkContractPackSafetySqlite(): ContractArtifactEnvelope {
  const capacity = payloadAsJsonValue(buildDeploymentRuntimeCapacityBaseline());
  assertJsonObject(capacity);
  const artifacts = expectedArtifacts();
  for (const [artifactPath, artifact] of artifacts) {
    assertExpectedContractBytes(artifactPath, artifact);
  }
  const actualCapacity = fs.readFileSync(
    absoluteRepositoryPath(capacityConfigPath),
    'utf8',
  );
  if (actualCapacity !== renderJson(capacity)) {
    throw new Error(
      `${capacityConfigPath} is not generated byte-for-byte; run npm run contracts:generate`,
    );
  }
  const manifest = buildManifest(artifacts, capacity);
  assertExpectedContractBytes(manifestPath, manifest);
  const parsedManifest = readArtifact(manifestPath);
  if (parsedManifest.hash !== manifest.hash) {
    throw new Error('G0.5 manifest hash drift');
  }
  validateCompletePack(artifacts, capacity, parsedManifest);
  return parsedManifest;
}
