import fs from 'fs';
import path from 'path';

import { Ajv2020, type AnySchema } from 'ajv/dist/2020.js';

import { parseContractArtifactEnvelope } from './artifact.js';
import {
  buildStaticAbsenceArtifact,
  buildStaticAbsenceSemanticArtifacts,
  STATIC_ABSENCE_ARTIFACT_DESCRIPTORS,
  STATIC_ABSENCE_FORMAT_BY_TARGET,
  staticPayloadAsJsonObject,
} from './static-absence-artifacts.js';
import {
  STATIC_ABSENCE_NEGATIVE_CASES,
  STATIC_ABSENCE_POSITIVE_CASES,
} from './static-absence-fixtures.js';
import { canonicalJson } from './hash.js';
import {
  assertIsolatedTestRoots,
  STATIC_ABSENCE_REPO_ROOT,
} from './static-absence-source.js';
import {
  ABSENCE_BASELINE_KEYS,
  MIGRATION_CANDIDATE_BOUNDARY_KEYS,
  PRODUCT_SURFACE_ENTRY_KEYS,
  PRODUCT_SURFACE_MANIFEST_KEYS,
  type MigrationCandidateBoundaryManifest,
  type ProductSurfaceCoverageManifest,
  type StaticAbsenceNegativeCase,
  type WorkflowRuntimeAbsenceBaseline,
} from './static-absence-types.js';
import { assertJsonObject, strictParseJsonBytes } from './strict-json.js';
import type {
  ContractArtifactEnvelope,
  JsonObject,
  JsonValue,
} from './types.js';

const contractsRoot = import.meta.dirname;
const foundationManifestHash =
  'sha256:e85b654581c036f8129677d7443a0704ebc8b8fbe87907b842aaefe1501e637d';
const closedSchemaManifestHash =
  'sha256:c5ea281d64480787322e8b6ef619b2f90784084d87ba4373c94288ed5e7aa3a8';
const catalogProtocolManifestHash =
  'sha256:e4947c515a28b3baf6782a980db9c26d32612b3c6acd3cd04348e73bd54ff607';
const safetySqliteManifestHash =
  'sha256:76b8e1196ac422500be9c79a767e673e9c30fa3d9bbb1dc12fc54613cd40b428';
const logicalSchemaManifestHash =
  'sha256:32de639cc0ee6c6f33aa4291ea03ffa55b0a22752190fb88862e72a3f6857520';
const manifestPath = 'contract-pack-static-absence.json';
const positiveCasesPath = 'conformance/static-absence/positive-cases.json';
const negativeCasesPath = 'conformance/static-absence/negative-cases.json';
const domainCatalogPath = 'catalogs/static-absence-domain-separators.json';

export class StaticAbsencePackError extends Error {
  readonly code = 'static_absence_contract_drift';

  constructor(message: string) {
    super(message);
    this.name = 'StaticAbsencePackError';
  }
}

function asciiCompare(left: string, right: string): number {
  return left < right ? -1 : left > right ? 1 : 0;
}

function absoluteContractPath(relativePath: string): string {
  const absolute = path.resolve(contractsRoot, relativePath);
  if (!absolute.startsWith(`${contractsRoot}${path.sep}`)) {
    throw new StaticAbsencePackError(
      `Contract path escapes root: ${relativePath}`,
    );
  }
  return absolute;
}

function renderJson(value: JsonValue): string {
  return `${JSON.stringify(value, null, 2)}\n`;
}

function writeAtomicFile(
  relativePath: string,
  artifact: ContractArtifactEnvelope,
): void {
  const absolute = absoluteContractPath(relativePath);
  fs.mkdirSync(path.dirname(absolute), { recursive: true });
  const temporary = `${absolute}.tmp-${process.pid}`;
  fs.writeFileSync(temporary, renderJson(artifact), {
    encoding: 'utf8',
    mode: 0o644,
  });
  fs.renameSync(temporary, absolute);
}

function assertExpectedBytes(
  relativePath: string,
  expected: ContractArtifactEnvelope,
): void {
  const actual = fs.readFileSync(absoluteContractPath(relativePath), 'utf8');
  if (actual !== renderJson(expected)) {
    throw new StaticAbsencePackError(
      `${relativePath} is not generated byte-for-byte; run npm run contracts:generate`,
    );
  }
}

function readArtifact(relativePath: string): ContractArtifactEnvelope {
  return parseContractArtifactEnvelope(
    strictParseJsonBytes(fs.readFileSync(absoluteContractPath(relativePath))),
  );
}

function buildFixtureArtifacts(): Array<[string, ContractArtifactEnvelope]> {
  return [
    [
      positiveCasesPath,
      buildStaticAbsenceArtifact(
        'icarus.workflow-static-absence-positive-cases/1',
        'icarus.workflow-static-absence-positive-cases',
        'icarus:workflow-static-absence-positive-cases:1\n',
        { cases: staticPayloadAsJsonObject(STATIC_ABSENCE_POSITIVE_CASES) },
      ),
    ],
    [
      negativeCasesPath,
      buildStaticAbsenceArtifact(
        'icarus.workflow-static-absence-negative-cases/1',
        'icarus.workflow-static-absence-negative-cases',
        'icarus:workflow-static-absence-negative-cases:1\n',
        { cases: staticPayloadAsJsonObject(STATIC_ABSENCE_NEGATIVE_CASES) },
      ),
    ],
  ];
}

function buildDomainCatalog(
  priorArtifacts: Array<[string, ContractArtifactEnvelope]>,
): ContractArtifactEnvelope {
  const entries = [
    ...priorArtifacts.map(([, artifact]) => ({
      format: artifact.format,
      domain_separator: artifact.domain_separator,
    })),
    {
      format: 'icarus.workflow-static-absence-domain-separators/1',
      domain_separator: 'icarus:workflow-static-absence-domain-separators:1\n',
    },
    {
      format: 'icarus.workflow-contract-pack-static-absence/1',
      domain_separator: 'icarus:workflow-contract-pack-static-absence:1\n',
    },
  ].sort((left, right) => asciiCompare(left.format, right.format));
  return buildStaticAbsenceArtifact(
    'icarus.workflow-static-absence-domain-separators/1',
    'icarus.workflow-static-absence-domain-separators',
    'icarus:workflow-static-absence-domain-separators:1\n',
    { entries },
  );
}

function expectedArtifacts(): Array<[string, ContractArtifactEnvelope]> {
  const semantic = buildStaticAbsenceSemanticArtifacts();
  const fixtures = buildFixtureArtifacts();
  const prior = [...semantic, ...fixtures];
  return [...prior, [domainCatalogPath, buildDomainCatalog(prior)]];
}

function artifactDescriptor(
  artifactPath: string,
  artifact: ContractArtifactEnvelope,
): JsonObject {
  return {
    path: artifactPath,
    format: artifact.format,
    ref: artifact.ref,
    version: artifact.version,
    domain_separator: artifact.domain_separator,
    hash: artifact.hash,
  };
}

function findPayload<T extends JsonObject>(
  artifacts: Array<[string, ContractArtifactEnvelope]>,
  format: string,
): T {
  const artifact = artifacts.find(
    ([, candidate]) => candidate.format === format,
  )?.[1];
  if (!artifact)
    throw new StaticAbsencePackError(`Missing G0.7 artifact ${format}`);
  return artifact.payload as T;
}

function buildManifest(
  artifacts: Array<[string, ContractArtifactEnvelope]>,
): ContractArtifactEnvelope {
  const absence = findPayload<WorkflowRuntimeAbsenceBaseline>(
    artifacts,
    'icarus.workflow-runtime-absence-baseline/1',
  );
  const surfaces = findPayload<ProductSurfaceCoverageManifest>(
    artifacts,
    'icarus.product-surface-coverage/1',
  );
  const candidate = findPayload<MigrationCandidateBoundaryManifest>(
    artifacts,
    'icarus.migration-candidate-boundary/1',
  );
  return buildStaticAbsenceArtifact(
    'icarus.workflow-contract-pack-static-absence/1',
    'icarus.workflow-contract-pack-static-absence',
    'icarus:workflow-contract-pack-static-absence:1\n',
    {
      gate: 'G0.7',
      status: 'static_absence_and_surface_contract',
      foundation_manifest_hash: foundationManifestHash,
      closed_schema_manifest_hash: closedSchemaManifestHash,
      catalog_protocol_manifest_hash: catalogProtocolManifestHash,
      safety_sqlite_manifest_hash: safetySqliteManifestHash,
      logical_schema_manifest_hash: logicalSchemaManifestHash,
      source_core_build_hash: absence.source_core_build_hash,
      generated_by_tool_hash: absence.generated_by_tool_hash,
      absence_baseline_hash: absence.baseline_hash,
      product_surface_manifest_hash: surfaces.manifest_hash,
      migration_candidate_boundary_hash: candidate.boundary_hash,
      schema_count: STATIC_ABSENCE_ARTIFACT_DESCRIPTORS.filter(
        (descriptor) => descriptor.artifact_kind === 'schema',
      ).length,
      active_surface_count: surfaces.active_surface_count,
      removed_surface_count: surfaces.removed_surface_count,
      archived_candidate_file_count: candidate.archived_file_count,
      positive_case_count: STATIC_ABSENCE_POSITIVE_CASES.length,
      negative_case_count: STATIC_ABSENCE_NEGATIVE_CASES.length,
      proof_sources: [
        'typescript_ast_import_graph',
        'web_route_enumeration',
        'electron_dom_inventory',
        'feature_manifest_parser',
        'sqlite_schema_inspection',
        'configured_filesystem_roots',
      ],
      candidate_content_source_scan_status: 'forbidden_and_zero',
      test_root_policy: 'isolated_temporary_data_and_store_roots',
      sqlite_profile_status: 'candidate',
      certification_status: 'not_certified',
      executable_ddl_status: 'absent',
      sqlite_runtime_execution_status: 'absent',
      artifacts: artifacts
        .map(([artifactPath, artifact]) =>
          artifactDescriptor(artifactPath, artifact),
        )
        .sort((left, right) =>
          asciiCompare(String(left.path), String(right.path)),
        ),
      next_reserved_directories: ['conformance/draft', 'conformance/sealed'],
      explicitly_absent_artifacts: [
        'golden_draft_or_review_input',
        'executable_migration_or_schema_manifest',
        'workflow_runtime_store_or_sqlite_factory',
        'compiler_or_golden_sealing',
        'registry_or_runtime_semantics',
        'runtime_center_or_ui',
        'certified_sqlite_profile_or_supported_limits',
      ],
    },
  );
}

function assertKeyset(
  actual: readonly string[],
  expected: readonly string[],
  label: string,
): void {
  if (
    [...actual].sort(asciiCompare).join('\n') !==
    [...expected].sort(asciiCompare).join('\n')
  ) {
    throw new StaticAbsencePackError(`${label} keyset drift`);
  }
}

function validatePriorPackIdentity(): void {
  const expected = [
    ['contract-pack-foundation.json', foundationManifestHash],
    ['contract-pack-closed-schemas.json', closedSchemaManifestHash],
    ['contract-pack-catalog-protocols.json', catalogProtocolManifestHash],
    ['contract-pack-safety-sqlite.json', safetySqliteManifestHash],
    ['contract-pack-logical-schema.json', logicalSchemaManifestHash],
  ] as const;
  for (const [relativePath, expectedHash] of expected) {
    if (readArtifact(relativePath).hash !== expectedHash) {
      throw new StaticAbsencePackError(
        `Prior manifest identity drift: ${relativePath}`,
      );
    }
  }
  const sqliteCandidate = readArtifact(
    'sqlite/local_single_user_sqlite@1.json',
  );
  if (
    sqliteCandidate.payload.certification_status !== 'candidate' ||
    sqliteCandidate.payload.sqlite_version !== null ||
    sqliteCandidate.payload.better_sqlite3_native_module_hash !== null ||
    sqliteCandidate.payload.release_artifact_hash !== null
  ) {
    throw new StaticAbsencePackError(
      'SQLite candidate was presented as certified',
    );
  }
}

function validateClosedSchemaObjects(value: JsonValue, pointer = ''): void {
  if (Array.isArray(value)) {
    value.forEach((child, index) =>
      validateClosedSchemaObjects(child, `${pointer}/${index}`),
    );
    return;
  }
  if (value === null || typeof value !== 'object') return;
  const objectValue = value as JsonObject;
  if (
    objectValue.type === 'object' &&
    objectValue.additionalProperties !== false
  ) {
    throw new StaticAbsencePackError(
      `Open G0.7 object schema at ${pointer || '/'}`,
    );
  }
  for (const [key, child] of Object.entries(objectValue)) {
    validateClosedSchemaObjects(child, `${pointer}/${key}`);
  }
}

function compileSchemas(artifacts: Array<[string, ContractArtifactEnvelope]>): {
  ajv: Ajv2020;
  validators: Map<string, ReturnType<Ajv2020['compile']>>;
  schemas: Map<string, JsonObject>;
} {
  const ajv = new Ajv2020({
    allErrors: true,
    coerceTypes: false,
    removeAdditional: false,
    strict: true,
    useDefaults: false,
  });
  const validators = new Map<string, ReturnType<Ajv2020['compile']>>();
  const schemas = new Map<string, JsonObject>();
  for (const descriptor of STATIC_ABSENCE_ARTIFACT_DESCRIPTORS.filter(
    (candidate) => candidate.artifact_kind === 'schema',
  )) {
    const artifact = artifacts.find(
      ([artifactPath]) => artifactPath === descriptor.artifact_path,
    )?.[1];
    if (!artifact || descriptor.target_format === null) {
      throw new StaticAbsencePackError(
        `Missing G0.7 schema ${descriptor.artifact_path}`,
      );
    }
    validateClosedSchemaObjects(artifact.payload);
    schemas.set(descriptor.target_format, artifact.payload);
    validators.set(
      descriptor.target_format,
      ajv.compile(artifact.payload as AnySchema),
    );
  }
  return { ajv, validators, schemas };
}

function schemaPropertyKeys(schema: JsonObject, label: string): string[] {
  assertJsonObject(schema.properties);
  if (Object.keys(schema.properties).length === 0) {
    throw new StaticAbsencePackError(`${label} has no properties`);
  }
  return Object.keys(schema.properties);
}

function validateTypeScriptSchemaConformance(
  schemas: Map<string, JsonObject>,
): void {
  const absence = schemas.get('icarus.workflow-runtime-absence-baseline/1');
  const surfaces = schemas.get('icarus.product-surface-coverage/1');
  const candidate = schemas.get('icarus.migration-candidate-boundary/1');
  if (!absence || !surfaces || !candidate) {
    throw new StaticAbsencePackError(
      'G0.7 schema target coverage is incomplete',
    );
  }
  assertKeyset(
    schemaPropertyKeys(absence, 'absence schema'),
    ABSENCE_BASELINE_KEYS,
    'absence schema',
  );
  assertKeyset(
    schemaPropertyKeys(surfaces, 'surface manifest schema'),
    PRODUCT_SURFACE_MANIFEST_KEYS,
    'surface manifest schema',
  );
  assertJsonObject(surfaces.properties);
  assertJsonObject(surfaces.properties.entries);
  assertJsonObject(surfaces.properties.entries.items);
  const entryUnion = surfaces.properties.entries.items.oneOf;
  if (!Array.isArray(entryUnion) || entryUnion.length !== 2) {
    throw new StaticAbsencePackError(
      'Surface entry union must be closed active/removed',
    );
  }
  for (const [index, entrySchema] of entryUnion.entries()) {
    assertJsonObject(entrySchema);
    assertKeyset(
      schemaPropertyKeys(entrySchema, `surface entry ${index}`),
      PRODUCT_SURFACE_ENTRY_KEYS,
      `surface entry ${index}`,
    );
  }
  assertKeyset(
    schemaPropertyKeys(candidate, 'candidate boundary schema'),
    MIGRATION_CANDIDATE_BOUNDARY_KEYS,
    'candidate boundary schema',
  );
}

export function evaluateStaticAbsenceNegativeFixture(
  fixture: StaticAbsenceNegativeCase,
): string {
  const proof = {
    removedSourceHits: [] as string[],
    gatewayBypassHits: [] as string[],
    removedApiHits: [] as string[],
    removedUiHits: [] as string[],
    legacySchemaHits: [] as string[],
    legacyFilesystemHits: [] as string[],
    legacyResourceHits: [] as string[],
    protectedFixtureCount: 1,
    testDataRoot: '/tmp/icarus-g0-7/data',
    testStoreRoot: '/tmp/icarus-g0-7/store',
    candidateReachabilityHits: [] as string[],
    candidateContentSourceScanCount: 0,
    surface: {
      status: 'removed' as 'active' | 'removed',
      replacementRef: null as string | null,
      contractFixtureHash: null as string | null,
      removalFixtureHash: `sha256:${'1'.repeat(64)}` as string | null,
    },
  };
  switch (fixture.mutation) {
    case 'add_removed_identifier':
    case 'add_removed_import':
      proof.removedSourceHits.push(fixture.mutation);
      break;
    case 'add_runtime_internal_import':
      proof.gatewayBypassHits.push(fixture.mutation);
      break;
    case 'add_removed_exact_route':
    case 'add_removed_prefix_route':
      proof.removedApiHits.push(fixture.mutation);
      break;
    case 'add_removed_nav_key':
    case 'add_removed_screen_id':
      proof.removedUiHits.push(fixture.mutation);
      break;
    case 'add_legacy_table':
    case 'add_legacy_column':
    case 'add_legacy_index':
      proof.legacySchemaHits.push(fixture.mutation);
      break;
    case 'add_legacy_data_root':
      proof.legacyFilesystemHits.push(fixture.mutation);
      break;
    case 'add_legacy_resource_root':
    case 'add_removed_feature_resource_key':
      proof.legacyResourceHits.push(fixture.mutation);
      break;
    case 'remove_protected_fixture':
      proof.protectedFixtureCount = 0;
      break;
    case 'set_test_data_root_to_production':
      proof.testDataRoot = path.join(STATIC_ABSENCE_REPO_ROOT, 'data');
      break;
    case 'set_test_store_root_to_production':
      proof.testStoreRoot = path.join(STATIC_ABSENCE_REPO_ROOT, 'store');
      break;
    case 'set_test_root_inside_candidate':
      proof.testDataRoot = path.join(
        STATIC_ABSENCE_REPO_ROOT,
        'local',
        'migration-candidates',
        'fixture',
      );
      break;
    case 'add_candidate_production_edge':
    case 'add_candidate_test_helper_edge':
    case 'add_candidate_setup_edge':
    case 'add_candidate_feature_registry_ref':
    case 'add_candidate_compiler_fixture':
    case 'add_candidate_build_copy':
    case 'add_candidate_release_pattern':
    case 'add_candidate_runtime_read':
      proof.candidateReachabilityHits.push(fixture.mutation);
      break;
    case 'scan_candidate_content_for_source_hits':
      proof.candidateContentSourceScanCount = 1;
      break;
    case 'removed_surface_with_replacement':
      proof.surface.replacementRef = 'compatibility:forbidden';
      break;
    case 'removed_surface_without_fixture':
      proof.surface.removalFixtureHash = null;
      break;
    case 'active_surface_without_fixture':
      proof.surface = {
        status: 'active',
        replacementRef: 'protected:test',
        contractFixtureHash: null,
        removalFixtureHash: null,
      };
      break;
    case 'active_surface_with_removal_fixture':
      proof.surface = {
        status: 'active',
        replacementRef: 'protected:test',
        contractFixtureHash: `sha256:${'2'.repeat(64)}`,
        removalFixtureHash: `sha256:${'3'.repeat(64)}`,
      };
      break;
    default:
      throw new StaticAbsencePackError(
        `Unknown negative mutation ${fixture.mutation}`,
      );
  }
  if (proof.removedSourceHits.length > 0) return 'removed_source_reachable';
  if (proof.gatewayBypassHits.length > 0) return 'runtime_gateway_bypass';
  if (proof.removedApiHits.length > 0) return 'removed_api_reachable';
  if (proof.removedUiHits.length > 0) return 'removed_ui_reachable';
  if (proof.legacySchemaHits.length > 0) return 'legacy_schema_present';
  if (proof.legacyFilesystemHits.length > 0) return 'legacy_filesystem_present';
  if (proof.legacyResourceHits.length > 0) return 'legacy_resource_present';
  if (proof.protectedFixtureCount === 0) return 'protected_capability_missing';
  try {
    assertIsolatedTestRoots(proof.testDataRoot, proof.testStoreRoot);
  } catch {
    return 'test_root_not_isolated';
  }
  if (proof.candidateContentSourceScanCount > 0)
    return 'candidate_content_scan_forbidden';
  if (proof.candidateReachabilityHits.length > 0)
    return 'migration_candidate_reachable';
  if (
    (proof.surface.status === 'active' &&
      (proof.surface.replacementRef === null ||
        proof.surface.contractFixtureHash === null ||
        proof.surface.removalFixtureHash !== null)) ||
    (proof.surface.status === 'removed' &&
      (proof.surface.replacementRef !== null ||
        proof.surface.contractFixtureHash !== null ||
        proof.surface.removalFixtureHash === null))
  ) {
    return 'surface_status_contract_invalid';
  }
  throw new StaticAbsencePackError(
    `Negative fixture unexpectedly passed: ${fixture.case_id}`,
  );
}

function validateFixtures(): void {
  const positiveIds = new Set(
    STATIC_ABSENCE_POSITIVE_CASES.map((fixture) => fixture.case_id),
  );
  const negativeIds = new Set(
    STATIC_ABSENCE_NEGATIVE_CASES.map((fixture) => fixture.case_id),
  );
  if (
    positiveIds.size !== STATIC_ABSENCE_POSITIVE_CASES.length ||
    negativeIds.size !== STATIC_ABSENCE_NEGATIVE_CASES.length
  ) {
    throw new StaticAbsencePackError('Duplicate G0.7 fixture id');
  }
  const requiredKinds = new Set([
    'source',
    'api',
    'ui',
    'schema',
    'filesystem',
    'resource',
  ]);
  for (const fixture of STATIC_ABSENCE_NEGATIVE_CASES) {
    if (
      evaluateStaticAbsenceNegativeFixture(fixture) !== fixture.expected_error
    ) {
      throw new StaticAbsencePackError(
        `Negative fixture oracle drift: ${fixture.case_id}`,
      );
    }
    requiredKinds.delete(fixture.proof_kind);
  }
  if (requiredKinds.size > 0) {
    throw new StaticAbsencePackError(
      `Removed surface fixture coverage is incomplete: ${[...requiredKinds].join(', ')}`,
    );
  }
}

function validateSemanticContracts(
  artifacts: Array<[string, ContractArtifactEnvelope]>,
): void {
  const absence = findPayload<WorkflowRuntimeAbsenceBaseline>(
    artifacts,
    'icarus.workflow-runtime-absence-baseline/1',
  );
  const surfaces = findPayload<ProductSurfaceCoverageManifest>(
    artifacts,
    'icarus.product-surface-coverage/1',
  );
  const candidate = findPayload<MigrationCandidateBoundaryManifest>(
    artifacts,
    'icarus.migration-candidate-boundary/1',
  );
  assertKeyset(Object.keys(absence), ABSENCE_BASELINE_KEYS, 'absence payload');
  assertKeyset(
    Object.keys(surfaces),
    PRODUCT_SURFACE_MANIFEST_KEYS,
    'surface payload',
  );
  assertKeyset(
    Object.keys(candidate),
    MIGRATION_CANDIDATE_BOUNDARY_KEYS,
    'candidate payload',
  );
  if (
    absence.source_core_build_hash !== surfaces.source_core_build_hash ||
    absence.source_core_build_hash !== candidate.source_core_build_hash ||
    absence.generated_by_tool_hash !== surfaces.generated_by_tool_hash ||
    absence.migration_candidate_boundary_hash !== candidate.boundary_hash
  ) {
    throw new StaticAbsencePackError('G0.7 build/tool/boundary identity drift');
  }
  if (
    surfaces.active_surface_count !==
      surfaces.entries.filter((entry) => entry.status === 'active').length ||
    surfaces.removed_surface_count !==
      surfaces.entries.filter((entry) => entry.status === 'removed').length ||
    new Set(surfaces.entries.map((entry) => entry.surface_id)).size !==
      surfaces.entries.length
  ) {
    throw new StaticAbsencePackError('Product surface count or identity drift');
  }
  for (const entry of surfaces.entries) {
    assertKeyset(
      Object.keys(entry),
      PRODUCT_SURFACE_ENTRY_KEYS,
      `surface ${entry.surface_id}`,
    );
    if (
      (entry.status === 'active' &&
        (entry.replacement_ref === null ||
          entry.contract_fixture_hash === null ||
          entry.removal_fixture_hash !== null)) ||
      (entry.status === 'removed' &&
        (entry.replacement_ref !== null ||
          entry.contract_fixture_hash !== null ||
          entry.removal_fixture_hash === null))
    ) {
      throw new StaticAbsencePackError(
        `Surface status contract invalid: ${entry.surface_id}`,
      );
    }
  }
  if (
    candidate.candidate_root !== 'local/migration-candidates/' ||
    candidate.archived_file_count !== 16
  ) {
    throw new StaticAbsencePackError('Candidate archive identity/count drift');
  }
}

function validateDomainCatalog(
  artifacts: Array<[string, ContractArtifactEnvelope]>,
  manifest: ContractArtifactEnvelope,
): void {
  const domain = artifacts.find(
    ([relativePath]) => relativePath === domainCatalogPath,
  )?.[1];
  if (!domain || !Array.isArray(domain.payload.entries)) {
    throw new StaticAbsencePackError('Missing G0.7 domain catalog');
  }
  const expectedFormats = new Set([
    ...artifacts
      .filter(([relativePath]) => relativePath !== domainCatalogPath)
      .map(([, artifact]) => artifact.format),
    domain.format,
    manifest.format,
  ]);
  const actualFormats = new Set(
    domain.payload.entries.map((entry) => {
      assertJsonObject(entry);
      return String(entry.format);
    }),
  );
  if (
    actualFormats.size !== expectedFormats.size ||
    [...expectedFormats].some((format) => !actualFormats.has(format))
  ) {
    throw new StaticAbsencePackError('G0.7 domain coverage drift');
  }
}

function validatePack(
  artifacts: Array<[string, ContractArtifactEnvelope]>,
  manifest: ContractArtifactEnvelope,
): void {
  validatePriorPackIdentity();
  const { ajv, validators, schemas } = compileSchemas(artifacts);
  validateTypeScriptSchemaConformance(schemas);
  for (const descriptor of STATIC_ABSENCE_ARTIFACT_DESCRIPTORS.filter(
    (candidate) => candidate.artifact_kind === 'manifest',
  )) {
    const target = artifacts.find(
      ([artifactPath]) => artifactPath === descriptor.artifact_path,
    )?.[1];
    const schemaFormat =
      STATIC_ABSENCE_FORMAT_BY_TARGET[descriptor.artifact_format];
    const validate = validators.get(descriptor.artifact_format);
    if (!target || !schemaFormat || !validate || !validate(target.payload)) {
      throw new StaticAbsencePackError(
        `${descriptor.artifact_format} failed closed schema: ${ajv.errorsText(validate?.errors)}`,
      );
    }
  }
  validateSemanticContracts(artifacts);
  validateFixtures();
  validateDomainCatalog(artifacts, manifest);
  const regenerated = buildManifest(artifacts);
  if (
    canonicalJson(regenerated as unknown as JsonValue) !==
    canonicalJson(manifest as unknown as JsonValue)
  ) {
    throw new StaticAbsencePackError('G0.7 manifest is not deterministic');
  }
}

export function generateContractPackStaticAbsence(): ContractArtifactEnvelope {
  const artifacts = expectedArtifacts();
  const manifest = buildManifest(artifacts);
  validatePack(artifacts, manifest);
  for (const [relativePath, artifact] of artifacts)
    writeAtomicFile(relativePath, artifact);
  writeAtomicFile(manifestPath, manifest);
  return manifest;
}

export function checkContractPackStaticAbsence(): ContractArtifactEnvelope {
  const artifacts = expectedArtifacts();
  const manifest = buildManifest(artifacts);
  validatePack(artifacts, manifest);
  for (const [relativePath, artifact] of artifacts)
    assertExpectedBytes(relativePath, artifact);
  assertExpectedBytes(manifestPath, manifest);
  return manifest;
}
