const COLLABORATION_LABELS = Object.freeze({
  unknown: '未知',
  active: '已启用',
  archived: '已归档',
  dissolved: '已解散',
  observer: '观察者',
  member: '成员',
  requested: '待审批',
  rejected: '已拒绝',
  suspended: '已停用',
  removed: '已移除',
  left: '已退出',
  used: '已使用',
  revoked: '已撤销',
  open: '进行中',
  approval: '审批加入',
  invite_only: '仅限邀请',
  allowed: '允许',
  members_only: '仅限成员',
  proposed: '提议中',
  in_progress: '进行中',
  blocked: '已阻塞',
  done: '已完成',
  cancelled: '已取消',
  low: '低',
  info: '提示',
  medium: '中',
  critical: '严重',
  normal: '普通',
  high: '高',
  urgent: '紧急',
  accepted: '已接受',
  deferred: '已暂缓',
  ignored: '已忽略',
  false_positive: '误报',
  declined: '已拒绝',
  resolved: '已解决',
  draft: '草稿',
  published: '已发布',
  retired: '已停用',
  ready: '就绪',
  running: '运行中',
  pausing: '暂停中',
  paused: '已暂停',
  closing: '关闭中',
  closed: '已关闭',
  recovery_required: '需要恢复',
  pending: '待处理',
  claimed: '已认领',
  waiting_input: '等待输入',
  waiting_approval: '等待审批',
  awaiting_confirmation: '等待确认',
  completed: '已完成',
  prepared: '已准备',
  awaiting_external_result: '等待外部结果',
  validating: '校验中',
  ready_for_review: '待复核',
  invalid: '结果无效',
  partially_applied: '部分已应用',
  stale: '快照已过期',
  manual: '手动',
  assisted: '辅助执行',
  automatic: '自动执行',
  task: '任务',
  issue: '问题',
  decision: '决策',
  milestone: '里程碑',
  group: '群组',
  invite: '邀请',
  membership: '成员关系',
  workspace: '工作区',
  project: '全项目',
  mine: '与我相关',
  delta: '增量变化',
  work_item: '工作项',
  discussion: '讨论',
  workflow_definition: '工作流定义',
  workflow_instance: '工作流实例',
  turn: '执行轮次',
  participants: '按参与者',
  free: '自由布局',
  participant_slot: '参与者角色',
  principal: '成员身份',
  human: '人员',
  agent: 'Agent',
  workflow: '工作流',
  analysis_run: 'Analysis Run',
  managed_executor: 'Icarus 托管',
  external_agent: '外部 Agent',
  run_once: '单次运行',
  external: '外部执行器',
  read_only: '只读',
  workspace_write: '可写工作区',
  untrusted: '不受信任',
  'on-request': '按需询问',
  never: '从不询问',
  healthy: '健康',
  needs_attention: '需要关注',
  at_risk: '存在风险',
  needs_action: '需要处理',
  waiting_on_others: '等待他人',
  watching: '关注中',
  recently_resolved: '最近解决',
  fact: '事实',
  inference: '推断',
  question: '问题',
  delivery_risk: '交付风险',
  schedule_risk: '进度风险',
  dependency_risk: '依赖风险',
  workflow_stall: '工作流停滞',
  assignment_gap: '分配缺口',
  quality_gap: '质量缺口',
  missing_evidence: '证据缺失',
  collaboration_gap: '协作缺口',
  information_conflict: '信息冲突',
  capacity_risk: '产能风险',
  identity_risk: '身份风险',
  protocol_risk: '协议风险',
  new: '新增',
  ongoing: '持续',
  worsened: '恶化',
  improved: '改善',
  dismissed: '已关闭',
  previewed: '已预览',
  applying: '应用中',
  applied: '已应用',
  create_work_item: '转为工作项',
  open_discussion: '发起讨论',
  post_progress: '发布进展',
  watch_work_item: '关注工作项',
  request_information: '请求信息',
  publish_analysis_report: '发布 Markdown 报告',
  work_item_assignment: '工作项分配',
  work_item_blocked: '工作项阻塞',
  work_item_status_change: '工作项状态变化',
  work_item_unblocked: '工作项已解除阻塞',
  work_item_blocking_others: '工作项正在阻塞其他事项',
  work_item_due: '工作项到期',
  workflow_state_action: '当前工作流状态待处理',
  workflow_turn_action: '执行轮次待处理',
  workflow_state_timeout: '工作流状态超时',
  discussion_mention: '讨论中提及了你',
  local_identity_invalid: '本地身份异常',
  protocol_sync_failure: '协议同步失败',
  assignment_confirmation_required: '等待确认任务分配',
  waiting_for_blockers: '等待前置事项完成',
  active_assignment: '当前负责事项',
  watched_risk: '关注事项出现风险',
  blocking_high_priority_work: '正在阻塞高优先级事项',
  workflow_state_assignment_ready: '当前工作流状态已指派给你',
  state_assignment_ready: '当前状态已指派并等待处理',
  turn_timeout: '执行轮次已超时',
  turn_pending: '执行轮次等待开始',
  turn_waiting_input: '执行轮次等待输入',
  turn_waiting_approval: '执行轮次等待审批',
  turn_awaiting_confirmation: '执行轮次等待确认',
  turn_recovery_required: '执行轮次需要恢复',
  workflow_paused: '工作流已暂停',
  workflow_recovery_required: '工作流需要恢复',
  recovery_decision_required: '恢复请求等待处理',
  credential_missing: '本地 Credential 缺失',
  credential_revoked: '本地 Credential 已撤销',
  protocol_or_sync_verification_failed: '协议或同步校验失败',
  succeeded: '成功',
  failed: '失败',
  redacted: '已脱敏',
  stopped: '已停止',
  verified: '已验证',
  OK: '正常',
  PROTOCOL_QUARANTINED: '协议已隔离',
  Delivery: '交付流程',
  Build: '构建',
  builder: '构建者',
  Builder: '构建者',
  reviewer: '审核者',
  Reviewer: '审核者',
  Review: '审核',
  Shipped: '已交付',
  Ready: '就绪',
  Done: '完成',
  Complete: '完成',
  Approved: '已批准',
  'Changes requested': '需要修改',
  Blocked: '已阻塞',
  Cancelled: '已取消',
  changes_requested: '需要修改',
  ready_for_test: '准备测试',
  group_initialized: '群组已初始化',
  group_settings_updated: '群组设置已更新',
  group_archived: '群组已归档',
  group_reopened: '群组已重新启用',
  group_dissolved: '群组已解散',
  invite_issued: '邀请已发放',
  invite_revoked: '邀请已撤销',
  membership_requested: '已申请加入群组',
  membership_rejected: '加入申请已拒绝',
  member_registered: '成员已加入',
  member_suspended: '成员已停用',
  member_reactivated: '成员已恢复',
  member_removed: '成员已移除',
  member_left: '成员已退出',
  member_left_workflow_recovery: '成员退出后工作流需要恢复',
  client_revoked: '客户端已撤销',
  executor_registered: '执行器已注册',
  executor_revoked: '执行器已撤销',
  permission_granted: '权限已授予',
  permission_revoked: '权限已撤销',
  progress_update_posted: '进展已发布',
  shared_file_published: '共享文件已发布',
  shared_file_revised: '共享文件已更新',
  principal_file_published: '个人文件已发布',
  action_published: '操作已发布',
  action_revised: '操作已更新',
  work_item_created: '工作项已创建',
  work_item_details_updated: '工作项详情已更新',
  work_item_assignment_changed: '工作项负责人已变更',
  work_item_assignment_acknowledged: '工作项分配已接受',
  work_item_assignment_declined: '工作项分配已拒绝',
  work_item_status_changed: '工作项状态已变更',
  work_item_progress_posted: '工作项进展已发布',
  work_item_relation_changed: '工作项关联已变更',
  work_item_archived: '工作项已归档',
  discussion_created: '讨论已创建',
  message_posted: '消息已发布',
  message_revised: '消息已更新',
  message_tombstoned: '消息已移除',
  discussion_resolved: '讨论已解决',
  discussion_reopened: '讨论已重新打开',
  workflow_definition_proposed: '工作流定义已提议',
  workflow_definition_published: '工作流定义已发布',
  workflow_definition_retired: '工作流定义已停用',
  workflow_layout_updated: '工作流布局已更新',
  workflow_instance_created: '工作流实例已创建',
  workflow_instance_started: '工作流实例已启动',
  workflow_instance_paused: '工作流实例已暂停',
  workflow_instance_resumed: '工作流实例已恢复',
  workflow_instance_closed: '工作流实例已关闭',
  workflow_state_assignee_changed: '工作流状态负责人已变更',
  state_execution_published: '状态执行配置已发布',
  state_execution_revised: '状态执行配置已更新',
  state_execution_withdrawn: '状态执行配置已撤回',
  turn_created: '执行轮次已创建',
  turn_started: '执行轮次已启动',
  action_dispatched: '操作已派发',
  action_waiting_input: '操作正在等待输入',
  action_waiting_approval: '操作正在等待审批',
  action_completed: '操作已完成',
  turn_timeout_observed: '执行轮次已超时',
  turn_completed: '执行轮次已完成',
  turn_cancelled: '执行轮次已取消',
  turn_recovery_requested: '执行轮次已请求恢复',
  turn_recovered: '执行轮次已恢复',
  'group:admin': '群组管理',
  'group:archive': '归档群组',
  'member:approve': '审批成员',
  'permission:grant': '授予权限',
  'workspace:write_shared': '写入共享工作区',
  'workspace:publish_owned': '发布个人文件',
  'work_item:create': '创建工作项',
  'work_item:manage_owned': '管理本人工作项',
  'work_item:manage_all': '管理全部工作项',
  'discussion:create': '创建讨论',
  'discussion:post': '发布讨论消息',
  'discussion:moderate': '管理讨论',
  'workflow_definition:propose': '提议工作流定义',
  'workflow_definition:publish': '发布工作流定义',
  'workflow_instance:start_allowed': '启动工作流实例',
  'workflow_instance:manage_all': '管理全部工作流实例',
});

export function collaborationLabel(value, fallback = '未知') {
  const normalized = String(value ?? '').trim();
  if (!normalized) return fallback;
  const numberedState = /^State (\d+)$/u.exec(normalized);
  if (numberedState) return `状态 ${numberedState[1]}`;
  const numberedParticipant = /^Participant (\d+)$/u.exec(normalized);
  if (numberedParticipant) return `参与者 ${numberedParticipant[1]}`;
  return COLLABORATION_LABELS[normalized] || normalized;
}

export function collaborationStatusLabel(value) {
  return collaborationLabel(value);
}

export function collaborationEventLabel(value) {
  return collaborationLabel(value);
}

export function collaborationAggregateLabel(value) {
  return collaborationLabel(value);
}

export function collaborationPermissionLabel(value) {
  return collaborationLabel(value);
}
