import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';

import { build } from 'esbuild';
import { format } from 'prettier';

import { collaborationAnalysisJsonSchemas } from '../src/collaboration/analysis-contracts.js';

const root = path.resolve(import.meta.dirname, '..');
const skillRoot = path.join(root, 'project-analyst');
const generatedResources = path.join(
  root,
  'src/collaboration/analysis-capability-resources.generated.ts',
);

function json(value: unknown): string {
  return `${JSON.stringify(value, null, 2)}\n`;
}

async function bundle(entry: string, outfile: string): Promise<string> {
  const result = await build({
    entryPoints: [path.join(root, entry)],
    outfile: path.join(skillRoot, outfile),
    write: false,
    bundle: true,
    platform: 'node',
    format: 'esm',
    mainFields: ['module', 'main'],
    target: 'node20',
    minify: true,
    sourcemap: false,
    legalComments: 'none',
  });
  const output = result.outputFiles?.[0];
  if (!output) throw new Error(`esbuild did not produce ${outfile}`);
  return output.text.replace(/^[\t ]+$/gmu, '');
}

function generatedCapabilityResources(
  overrides: ReadonlyMap<string, string>,
): string {
  const included = [
    'SKILL.md',
    'references/action-policy.md',
    'references/evidence-rules.md',
    'references/finding-taxonomy.md',
    'references/package-mode.md',
    'references/repository-mode.md',
    'references/trust-model.md',
    'scripts/validate-result.mjs',
    'scripts/verify-evidence.mjs',
  ];
  const files = included.map((file) => ({
    path: file,
    contents:
      overrides.get(file) ?? readFileSync(path.join(skillRoot, file), 'utf8'),
  }));
  return `// Generated by scripts/build-project-analyst-skill.ts. Do not edit.\nexport const PROJECT_ANALYST_CAPABILITY_STATIC_FILES = ${JSON.stringify(files, null, 2)} as const;\n`;
}

async function main(): Promise<void> {
  const check = process.argv.slice(2).includes('--check');
  const schemas = collaborationAnalysisJsonSchemas();
  const contracts = {
    'analysis-input.schema.json': schemas.input,
    'analysis-result.schema.json': schemas.result,
    'proposed-action.schema.json': schemas.action,
    'repository-analysis-input.schema.json': schemas.repositoryInput,
    'repository-analysis-result.schema.json': schemas.repositoryResult,
    'repository-verification.schema.json': schemas.repositoryVerification,
  };
  const expectedContractFiles = Object.keys(contracts).sort();
  const expected = new Map<string, string>();
  for (const [file, schema] of Object.entries(contracts))
    expected.set(`contracts/${file}`, json(schema));
  expected.set(
    'scripts/repository-context.mjs',
    await bundle(
      'scripts/project-analyst-repository-cli.ts',
      'scripts/repository-context.mjs',
    ),
  );
  expected.set(
    'scripts/validate-result.mjs',
    await bundle(
      'scripts/project-analyst-validate-result.ts',
      'scripts/validate-result.mjs',
    ),
  );
  const generatedSource = await format(generatedCapabilityResources(expected), {
    parser: 'typescript',
    singleQuote: true,
  });
  if (check) {
    const actualContractFiles = readdirSync(
      path.join(skillRoot, 'contracts'),
    ).sort();
    const stale = [
      ...[...expected].flatMap(([file, contents]) =>
        readFileSync(path.join(skillRoot, file), 'utf8') === contents
          ? []
          : [file],
      ),
      ...(readFileSync(generatedResources, 'utf8') === generatedSource
        ? []
        : ['src/collaboration/analysis-capability-resources.generated.ts']),
      ...(actualContractFiles.join('\0') === expectedContractFiles.join('\0')
        ? []
        : ['project-analyst/contracts file set']),
    ];
    if (stale.length)
      throw new Error(
        `Project Analyst generated files are stale: ${stale.join(', ')}`,
      );
  } else {
    for (const [file, contents] of expected)
      writeFileSync(path.join(skillRoot, file), contents);
    writeFileSync(generatedResources, generatedSource);
  }
  const contractFiles = readdirSync(path.join(skillRoot, 'contracts')).sort();
  process.stdout.write(
    `${check ? 'Checked' : 'Built'} project-analyst Skill with ${String(contractFiles.length)} contracts.\n`,
  );
}

await main();
