import http from 'node:http';

import { describe, expect, it, vi } from 'vitest';

import type { CollaborationRuntime } from './runtime.js';
import type {
  CollaborationExecutionRecord,
  CollaborationExecutorBinding,
  CollaborationGroupRecord,
  CollaborationSyncAttempt,
} from './store.js';
import {
  CollaborationWebApi,
  collaborationWebApiTestables,
} from './web-api.js';

function apiGroup(): CollaborationGroupRecord {
  return {
    groupId: 'ag_test',
    name: 'Test',
    creatorPrincipalId: 'alice',
    localPrincipalId: 'alice',
    localAgentId: 'agent_alice',
    lifecycle: 'READY',
    businessState: 'development',
    protocolStatus: 'OK',
    protocolError: null,
    projection: null,
    remoteUrl: '/tmp/remote.git',
    repositoryPath: '/tmp/repository.git',
    signingKeyPath: '/tmp/signing-key',
    signingPublicKey: 'ssh-ed25519 public',
    signingKeyRef: 'ssh-ed25519:SHA256:test',
    pollIntervalMs: 15_000,
    nextSyncAtMs: 1,
    backoffAttempt: 0,
    lastSyncAtMs: null,
    lastError: null,
    headCommit: 'head-1',
  };
}

async function withApiServer(
  api: CollaborationWebApi,
  work: (baseUrl: string) => Promise<void>,
): Promise<void> {
  const server = http.createServer((req, res) => {
    void api.handle(req, res, new URL(req.url ?? '/', 'http://localhost'));
  });
  await new Promise<void>((resolve) => server.listen(0, '127.0.0.1', resolve));
  const address = server.address();
  if (!address || typeof address === 'string') throw new Error('No test port');
  try {
    await work(`http://127.0.0.1:${String(address.port)}`);
  } finally {
    await new Promise<void>((resolve, reject) =>
      server.close((error) => (error ? reject(error) : resolve())),
    );
  }
}

describe('Collaboration Web API redaction', () => {
  it('rejects attempts to override Host-generated collaboration identity', () => {
    expect(() =>
      collaborationWebApiTestables.rejectSystemIdentityOverrides({
        remoteUrl: '/tmp/group.git',
        principalId: 'caller-selected',
        agentId: 'caller-selected',
      }),
    ).toThrow(/must not be provided.*generated by the Host/);
    expect(() =>
      collaborationWebApiTestables.rejectSystemIdentityOverrides({
        remoteUrl: '/tmp/group.git',
        signingKeyPath: '/tmp/signing-key',
      }),
    ).not.toThrow();
  });

  it('never serializes the signing key path or remote credentials', () => {
    const group = {
      groupId: 'ag_test',
      name: 'Test',
      creatorPrincipalId: 'alice',
      localPrincipalId: 'alice',
      localAgentId: 'agent_alice',
      lifecycle: 'READY',
      businessState: 'development',
      protocolStatus: 'OK',
      protocolError:
        'git fetch https://private-token@example.test/group.git failed',
      projection: null,
      remoteUrl:
        'https://private-token@example.test/group.git?accessToken=query-secret&ref=main',
      repositoryPath: '/private/cache/repository.git',
      signingKeyPath: '/private/keys/id_ed25519',
      signingPublicKey: 'ssh-ed25519 public',
      signingKeyRef: 'ssh-ed25519:SHA256:test',
      pollIntervalMs: 15_000,
      nextSyncAtMs: 1,
      backoffAttempt: 0,
      lastSyncAtMs: null,
      lastError:
        'https://private-token@example.test/group.git?accessToken=query-secret is unavailable',
      headCommit: null,
    } satisfies CollaborationGroupRecord;

    const serialized = collaborationWebApiTestables.publicGroup(group);
    expect(JSON.stringify(serialized)).not.toContain('/private/keys');
    expect(JSON.stringify(serialized)).not.toContain('/private/cache');
    expect(serialized.remoteUrl).toContain('redacted@');
    expect(serialized.remoteUrl).toContain('accessToken=redacted');
    expect(serialized.remoteUrl).toContain('ref=main');
    expect(serialized.remoteUrl).not.toContain('query-secret');
    expect(serialized.protocolError).not.toContain('private-token');
    expect(serialized.lastError).not.toContain('private-token');
    expect(serialized.lastError).not.toContain('query-secret');
  });

  it('allowlists provider fields and removes raw receipt/metadata', () => {
    const execution = {
      executionId: 'execution-1',
      groupId: 'ag_test',
      turnId: 'turn-1',
      epoch: 1,
      attempt: 1,
      fencingToken: `sha256:${'a'.repeat(64)}`,
      operationKey: `sha256:${'b'.repeat(64)}`,
      executorKind: 'external',
      adapter: 'codex-task',
      state: 'running',
      executionRef: 'collaboration-action:opaque',
      providerMetadata: {
        transport: 'app_server_stdio',
        thread_id: 'thread-local',
        turn_id: 'turn-local',
        cli_version: '0.146.0',
        provider_secret_id: 'must-not-leak',
      },
      receipt: { private_receipt: 'must-not-leak' },
      observation: {
        state: 'running',
        executionRef: 'collaboration-action:opaque',
        providerMetadata: { provider_secret_id: 'must-not-leak' },
        result: null,
        resultHash: null,
      },
      pendingResultEvent: null,
      recoveryRequiredReason: null,
      dispatchStartedAtMs: 1,
      receiptRecordedAtMs: 2,
      createdAtMs: 1,
      updatedAtMs: 2,
    } satisfies CollaborationExecutionRecord;

    const serialized = collaborationWebApiTestables.publicExecution(execution);
    expect(serialized.provider).toMatchObject({
      kind: 'codex-task',
      threadId: 'thread-local',
      turnId: 'turn-local',
    });
    expect(JSON.stringify(serialized)).not.toContain('must-not-leak');
    expect(serialized).not.toHaveProperty('receipt');
    expect(serialized).not.toHaveProperty('providerMetadata');
  });

  it('redacts secret-like executor config keys recursively', () => {
    const binding = {
      groupId: 'ag_test',
      role: 'developer',
      executorKind: 'external',
      adapter: 'codex-task',
      agentJid: null,
      workspacePath: '/workspace',
      promptOverride: null,
      filesystemAccessCap: 'workspace_write',
      approvalPolicy: 'on-request',
      config: {
        transport: 'app_server',
        nested: {
          access_token: 'secret-value',
          apiKey: 'api-secret',
          clientSecret: 'client-secret',
          harmless: 'visible',
        },
      },
      enabled: true,
      updatedAtMs: 1,
    } satisfies CollaborationExecutorBinding;
    expect(collaborationWebApiTestables.publicBinding(binding).config).toEqual({
      transport: 'app_server',
      nested: {
        access_token: '[redacted]',
        apiKey: '[redacted]',
        clientSecret: '[redacted]',
        harmless: 'visible',
      },
    });
  });

  it('redacts credentials from standalone diagnostic URLs', () => {
    const diagnostic = collaborationWebApiTestables.redactDiagnostic(
      'clone https://user:password@example.test/group.git failed',
    );
    expect(diagnostic).toContain('https://redacted@example.test/group.git');
    expect(diagnostic).not.toContain('password');
  });

  it('redacts credentials from sync history errors', () => {
    const attempt = {
      id: 1,
      groupId: 'ag_test',
      startedAtMs: 1,
      completedAtMs: 2,
      outcome: 'failed',
      headBefore: 'before',
      headAfter: 'after',
      error:
        'fetch https://user:password@example.test/group.git?accessToken=query-secret failed',
      errorClass: 'runtime',
    } satisfies CollaborationSyncAttempt;
    const serialized = collaborationWebApiTestables.publicSyncAttempt(
      attempt,
      'https://user:password@example.test/group.git?accessToken=query-secret',
    );
    expect(serialized.error).toContain('redacted@example.test');
    expect(serialized.error).toContain('accessToken=redacted');
    expect(serialized.error).not.toContain('password');
    expect(serialized.error).not.toContain('query-secret');
  });
});

describe('Collaboration Web API data updates', () => {
  it('routes a revision- and turn-fenced UTF-8 data update', async () => {
    const group = apiGroup();
    const updateData = vi.fn(async () => ({
      group,
      path: 'data/notes/status.txt',
      contentSha256: `sha256:${'a'.repeat(64)}`,
      sizeBytes: 0,
    }));
    const runtime = {
      status: () => ({
        available: true,
        databasePath: '/tmp/collaboration.db',
        repositoryRoot: '/tmp/repositories',
        error: null,
        scheduler: null,
      }),
      store: { getGroup: () => group },
      groups: { updateData },
    } as unknown as CollaborationRuntime;

    await withApiServer(new CollaborationWebApi(runtime), async (baseUrl) => {
      const response = await fetch(
        `${baseUrl}/api/collaboration/groups/ag_test/data`,
        {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            path: 'notes/status.txt',
            content: '',
            mediaType: 'text/plain',
            expectedRevision: 7,
            turnId: 'turn_1',
            attempt: 2,
            fencingToken: `sha256:${'b'.repeat(64)}`,
          }),
        },
      );
      expect(response.status).toBe(200);
      expect(updateData).toHaveBeenCalledWith({
        groupId: 'ag_test',
        path: 'notes/status.txt',
        content: '',
        mediaType: 'text/plain',
        expectedRevision: 7,
        turn: {
          turnId: 'turn_1',
          attempt: 2,
          fencingToken: `sha256:${'b'.repeat(64)}`,
        },
      });
      await expect(response.json()).resolves.toMatchObject({
        path: 'data/notes/status.txt',
        sizeBytes: 0,
      });
    });
  });

  it('rejects an incomplete turn fence before calling the service', async () => {
    const group = apiGroup();
    const updateData = vi.fn();
    const runtime = {
      status: () => ({
        available: true,
        databasePath: '/tmp/collaboration.db',
        repositoryRoot: '/tmp/repositories',
        error: null,
        scheduler: null,
      }),
      store: { getGroup: () => group },
      groups: { updateData },
    } as unknown as CollaborationRuntime;

    await withApiServer(new CollaborationWebApi(runtime), async (baseUrl) => {
      const response = await fetch(
        `${baseUrl}/api/collaboration/groups/ag_test/data`,
        {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            path: 'notes/status.txt',
            content: 'unsafe',
            expectedRevision: 7,
            turnId: 'turn_1',
          }),
        },
      );
      expect(response.status).toBe(400);
      expect(updateData).not.toHaveBeenCalled();
    });
  });
});
