import { mkdirSync, rmSync, writeFileSync } from 'node:fs';
import http from 'node:http';
import crypto from 'node:crypto';
import path from 'node:path';

import { buildCollaborationAudit } from './audit.js';
import {
  listCollaborationSharedPaths,
  readPromptFromValidatedCacheAsync,
} from './git-transport.js';
import type {
  CollaborationProjection,
  ValidatedCollaborationHistory,
} from './protocol/index.js';
import type { CollaborationRuntime } from './runtime.js';
import type {
  CollaborationExecutionRecord,
  CollaborationExecutorBinding,
  CollaborationGroupRecord,
  CollaborationStagedArtifact,
  CollaborationSyncAttempt,
} from './store.js';

const API_PREFIX = '/api/collaboration';
const MAX_BODY_BYTES = 14 * 1024 * 1024;

function object(value: unknown): Record<string, unknown> {
  if (!value || typeof value !== 'object' || Array.isArray(value))
    throw new Error('A JSON object body is required');
  return value as Record<string, unknown>;
}

function rejectSystemIdentityOverrides(value: Record<string, unknown>): void {
  const fields = ['principalId', 'agentId', 'principal_id', 'agent_id'].filter(
    (key) => Object.hasOwn(value, key),
  );
  if (fields.length)
    throw new Error(
      `${fields.join(' and ')} must not be provided; collaboration identity is generated by the Host`,
    );
}

function requiredString(value: Record<string, unknown>, key: string): string {
  const candidate = value[key];
  if (typeof candidate !== 'string' || !candidate.trim())
    throw new Error(`${key} is required`);
  return candidate.trim();
}

function requiredText(value: Record<string, unknown>, key: string): string {
  const candidate = value[key];
  if (typeof candidate !== 'string') throw new Error(`${key} is required`);
  return candidate;
}

function optionalString(
  value: Record<string, unknown>,
  key: string,
): string | null {
  const candidate = value[key];
  return typeof candidate === 'string' && candidate.trim()
    ? candidate.trim()
    : null;
}

function stringArray(value: unknown, key: string): string[] {
  if (value === undefined) return [];
  if (!Array.isArray(value) || value.some((entry) => typeof entry !== 'string'))
    throw new Error(`${key} must be an array of strings`);
  return value as string[];
}

function send(res: http.ServerResponse, status: number, body: unknown): void {
  res.writeHead(status, { 'Content-Type': 'application/json' });
  res.end(JSON.stringify(body));
}

async function jsonBody(req: http.IncomingMessage): Promise<unknown> {
  const chunks: Buffer[] = [];
  let size = 0;
  for await (const chunk of req) {
    const buffer = Buffer.from(chunk);
    size += buffer.length;
    if (size > MAX_BODY_BYTES) throw new Error('Request body is too large');
    chunks.push(buffer);
  }
  return JSON.parse(Buffer.concat(chunks).toString('utf8') || '{}') as unknown;
}

function redactRemoteUrl(input: string): string {
  try {
    const parsed = new URL(input);
    if (parsed.username || parsed.password) {
      parsed.username = 'redacted';
      parsed.password = '';
    }
    for (const key of [...parsed.searchParams.keys()])
      if (isSecretConfigKey(key)) parsed.searchParams.set(key, 'redacted');
    return parsed.toString();
  } catch {
    return input;
  }
}

function redactDiagnostic(
  input: string | null,
  sensitiveUrls: readonly string[] = [],
): string | null {
  if (input == null) return null;
  let output = input;
  for (const remoteUrl of sensitiveUrls)
    output = output.replaceAll(remoteUrl, redactRemoteUrl(remoteUrl));
  return output.replace(/https?:\/\/[^\s"']+/g, (candidate) =>
    redactRemoteUrl(candidate),
  );
}

function isSecretConfigKey(key: string): boolean {
  const parts = key
    .replace(/([a-z0-9])([A-Z])/g, '$1_$2')
    .toLocaleLowerCase()
    .split(/[^a-z0-9]+/)
    .filter(Boolean);
  const values = new Set(parts);
  return (
    parts.some((part) =>
      [
        'password',
        'passwd',
        'token',
        'secret',
        'credential',
        'credentials',
        'authorization',
      ].includes(part),
    ) ||
    (values.has('api') && values.has('key')) ||
    (values.has('private') && values.has('key')) ||
    (values.has('signing') && values.has('key') && values.has('path'))
  );
}

function redactConfig(value: unknown, key = ''): unknown {
  if (isSecretConfigKey(key)) return '[redacted]';
  if (Array.isArray(value)) return value.map((child) => redactConfig(child));
  if (value && typeof value === 'object')
    return Object.fromEntries(
      Object.entries(value as Record<string, unknown>).map(
        ([childKey, child]) => [childKey, redactConfig(child, childKey)],
      ),
    );
  return value;
}

function publicProjection(
  projection: CollaborationProjection | null,
): CollaborationProjection | null {
  if (!projection) return null;
  return {
    ...projection,
    members: Object.fromEntries(
      Object.entries(projection.members).map(([principalId, members]) => [
        principalId,
        members.map((member) => ({
          ...member,
          signing_public_key: '[redacted]',
        })),
      ]),
    ),
  };
}

function publicGroup(group: CollaborationGroupRecord) {
  return {
    groupId: group.groupId,
    name: group.name,
    creatorPrincipalId: group.creatorPrincipalId,
    localPrincipalId: group.localPrincipalId,
    localAgentId: group.localAgentId,
    lifecycle: group.lifecycle,
    businessState: group.businessState,
    protocolStatus: group.protocolStatus,
    protocolError: redactDiagnostic(group.protocolError, [group.remoteUrl]),
    projection: publicProjection(group.projection),
    remoteUrl: redactRemoteUrl(group.remoteUrl),
    signingKeyRef: group.signingKeyRef,
    signingConfigured: Boolean(group.signingKeyPath),
    pollIntervalMs: group.pollIntervalMs,
    nextSyncAtMs: group.nextSyncAtMs,
    backoffAttempt: group.backoffAttempt,
    lastSyncAtMs: group.lastSyncAtMs,
    lastError: redactDiagnostic(group.lastError, [group.remoteUrl]),
    headCommit: group.headCommit,
  };
}

function publicBinding(binding: CollaborationExecutorBinding) {
  return {
    groupId: binding.groupId,
    stateId: binding.stateId,
    implementationHash: binding.implementationHash,
    actionHash: binding.actionHash,
    executorKind: binding.executorKind,
    adapter: binding.adapter,
    agentJid: binding.agentJid,
    workspacePath: binding.workspacePath,
    filesystemAccessCap: binding.filesystemAccessCap,
    approvalPolicy: binding.approvalPolicy,
    config: redactConfig(binding.config),
    enabled: binding.enabled,
    updatedAtMs: binding.updatedAtMs,
  };
}

function publicExecution(execution: CollaborationExecutionRecord) {
  const metadata = execution.providerMetadata ?? {};
  const provider =
    execution.adapter === 'codex-task'
      ? {
          kind: 'codex-task',
          transport: metadata.transport,
          threadId: metadata.thread_id,
          turnId: metadata.turn_id,
          cliVersion: metadata.cli_version,
          ephemeral: metadata.ephemeral,
        }
      : execution.executorKind === 'workflow'
        ? {
            kind: 'workflow',
            workflowId: metadata.workflow_id,
            graphRunId: metadata.graph_run_id,
            lifecycle: metadata.lifecycle,
            operationalState: metadata.operational_state,
          }
        : execution.executorKind === 'run_once'
          ? {
              kind: 'run_once',
              runId: metadata.run_id,
              queryId: metadata.query_id,
            }
          : { kind: execution.executorKind };
  const observation = execution.observation;
  return {
    executionId: execution.executionId,
    groupId: execution.groupId,
    turnId: execution.turnId,
    epoch: execution.epoch,
    attempt: execution.attempt,
    operationKey: execution.operationKey,
    executorKind: execution.executorKind,
    adapter: execution.adapter,
    state: execution.state,
    executionRef: execution.executionRef,
    publicReceipt: {
      accepted: execution.receipt?.accepted === true,
      operationKey: execution.operationKey,
      executionRef: execution.executionRef,
    },
    provider,
    observation: observation
      ? {
          state: observation.state,
          result: redactConfig(observation.result),
          resultHash: observation.resultHash,
          recoveryReason: observation.recoveryReason,
        }
      : null,
    recoveryRequiredReason: execution.recoveryRequiredReason,
    dispatchStartedAtMs: execution.dispatchStartedAtMs,
    receiptRecordedAtMs: execution.receiptRecordedAtMs,
    providerCompletedAtMs: execution.providerCompletedAtMs,
    createdAtMs: execution.createdAtMs,
    updatedAtMs: execution.updatedAtMs,
  };
}

function publicStagedArtifact(artifact: CollaborationStagedArtifact) {
  return {
    artifactId: artifact.artifactId,
    groupId: artifact.groupId,
    turnId: artifact.turnId,
    attempt: artifact.attempt,
    originalName: artifact.originalName,
    repositoryPath: artifact.repositoryPath,
    sha256: artifact.sha256,
    size: artifact.size,
    contentType: artifact.contentType,
    state: artifact.state,
    createdAtMs: artifact.createdAtMs,
    expiresAtMs: artifact.expiresAtMs,
  };
}

function currentAttemptArtifacts(
  runtime: CollaborationRuntime,
  group: CollaborationGroupRecord,
  turn: CollaborationProjection['turns'][string] | null,
) {
  if (!turn) return [];
  return runtime.store
    .listStagedArtifacts(group.groupId, turn.turnId)
    .filter(
      (artifact) =>
        artifact.attempt === turn.attempt &&
        artifact.principalId === group.localPrincipalId &&
        artifact.agentId === group.localAgentId,
    )
    .map(publicStagedArtifact);
}

async function readActiveImplementationPrompts(
  repositoryPath: string,
  history: ValidatedCollaborationHistory,
): Promise<Record<string, string>> {
  const entries = await Promise.all(
    Object.entries(history.projection.stateImplementations).map(
      async ([stateId, active]) => {
        const promptRef = active.action?.input.prompt_ref;
        if (!promptRef) return null;
        return [
          stateId,
          await readPromptFromValidatedCacheAsync({
            repositoryPath,
            head: history.head,
            promptRef,
          }),
        ] as const;
      },
    ),
  );
  return Object.fromEntries(entries.filter((entry) => entry !== null));
}

function publicSyncAttempt(
  attempt: CollaborationSyncAttempt,
  remoteUrl: string,
) {
  return { ...attempt, error: redactDiagnostic(attempt.error, [remoteUrl]) };
}

function publicIntegrityIncident<T extends { readonly message: string }>(
  incident: T,
  remoteUrl: string,
) {
  return {
    ...incident,
    message: redactDiagnostic(incident.message, [remoteUrl]),
  };
}

function requiredExpectedRevision(body: Record<string, unknown>): number {
  if (!Number.isInteger(body.expectedRevision))
    throw new Error('expectedRevision is required');
  return Number(body.expectedRevision);
}

function isRevisionConflict(error: unknown): boolean {
  return error instanceof Error && /^Expected revision /.test(error.message);
}

export class CollaborationWebApi {
  constructor(private readonly runtime: CollaborationRuntime) {}

  async handle(
    req: http.IncomingMessage,
    res: http.ServerResponse,
    url: URL,
  ): Promise<boolean> {
    if (!url.pathname.startsWith(`${API_PREFIX}/`)) return false;
    try {
      await this.route(req, res, url);
    } catch (error) {
      send(
        res,
        !this.runtime.status().available
          ? 503
          : isRevisionConflict(error)
            ? 409
            : 400,
        {
          error: redactDiagnostic(
            error instanceof Error ? error.message : String(error),
          ),
          collaboration: this.publicRuntimeStatus(),
        },
      );
    }
    return true;
  }

  private async route(
    req: http.IncomingMessage,
    res: http.ServerResponse,
    url: URL,
  ): Promise<void> {
    const pathname = url.pathname;
    if (pathname === `${API_PREFIX}/status` && req.method === 'GET') {
      send(res, 200, { collaboration: this.publicRuntimeStatus() });
      return;
    }
    if (pathname === `${API_PREFIX}/backup` && req.method === 'POST') {
      const body = object(await jsonBody(req));
      const backupDirectory =
        optionalString(body, 'backupDirectory') ??
        path.join(
          path.dirname(this.runtime.databasePath),
          'collaboration-backups',
          new Date().toISOString().replace(/[:.]/g, '-'),
        );
      send(res, 201, {
        backupDirectory,
        manifest: await this.runtime.createBackup(backupDirectory),
      });
      return;
    }
    if (pathname === `${API_PREFIX}/restore` && req.method === 'POST') {
      const body = object(await jsonBody(req));
      if (body.confirm !== 'RESTORE COLLABORATION')
        throw new Error('confirm must equal RESTORE COLLABORATION');
      send(res, 200, {
        ok: true,
        ...(await this.runtime.restoreBackup(
          requiredString(body, 'backupDirectory'),
        )),
      });
      return;
    }

    const base = `${API_PREFIX}/groups`;
    if (pathname === base && req.method === 'GET') {
      send(res, 200, {
        groups: this.runtime.groups
          .listGroups(url.searchParams.get('search') ?? '')
          .map(publicGroup),
      });
      return;
    }
    if (pathname === base && req.method === 'POST') {
      const body = object(await jsonBody(req));
      rejectSystemIdentityOverrides(body);
      if (body.actions !== undefined || body.prompts !== undefined)
        throw new Error(
          'Group creation accepts only the creator-owned workflow skeleton',
        );
      send(res, 201, {
        group: publicGroup(
          await this.runtime.groups.createGroup(
            body as unknown as Parameters<
              CollaborationRuntime['groups']['createGroup']
            >[0],
          ),
        ),
      });
      return;
    }
    if (pathname === `${base}/inspect` && req.method === 'POST') {
      const body = object(await jsonBody(req));
      send(res, 200, {
        summary: await this.runtime.groups.inspectRemote(
          requiredString(body, 'remoteUrl'),
        ),
      });
      return;
    }
    if (pathname === `${base}/join` && req.method === 'POST') {
      const body = object(await jsonBody(req));
      rejectSystemIdentityOverrides(body);
      send(res, 201, {
        group: publicGroup(
          await this.runtime.groups.joinGroup(
            body as unknown as Parameters<
              CollaborationRuntime['groups']['joinGroup']
            >[0],
          ),
        ),
      });
      return;
    }

    const segments = pathname
      .slice(`${base}/`.length)
      .split('/')
      .map(decodeURIComponent);
    const groupId = segments[0] ?? '';
    const group = this.runtime.store.getGroup(groupId);
    if (!group) {
      send(res, 404, { error: 'Collaboration group not found' });
      return;
    }
    let history = this.runtime.groups.getCachedHistory(groupId);
    if (!history) history = await this.runtime.groups.syncHistory(groupId);

    if (segments.length === 1 && req.method === 'GET') {
      const scheduler = (
        this.runtime as unknown as {
          scheduler?: CollaborationRuntime['scheduler'];
        }
      ).scheduler;
      if (scheduler?.refreshLocalNotifications)
        history = await scheduler.refreshLocalNotifications(groupId);
      const turn = history.projection.activeTurnId
        ? history.projection.turns[history.projection.activeTurnId]
        : null;
      const implementationPrompts = await readActiveImplementationPrompts(
        group.repositoryPath,
        history,
      );
      send(res, 200, {
        group: publicGroup(this.runtime.store.getGroup(groupId)!),
        definition: redactConfig(history.definition),
        implementationPrompts,
        bindings: this.runtime.store
          .listExecutorBindings(groupId)
          .map(publicBinding),
        executions: this.runtime.store
          .listExecutions(groupId)
          .map(publicExecution),
        stagedArtifacts: currentAttemptArtifacts(this.runtime, group, turn),
        notifications: (
          scheduler?.listPendingLocalNotifications(groupId, history) ??
          this.runtime.store
            .listPendingNotifications({
              recipientPrincipalId: group.localPrincipalId,
              recipientAgentId: group.localAgentId,
              groupId,
            })
            .filter(
              (notification) =>
                turn &&
                notification.turnId === turn.turnId &&
                notification.attempt === turn.attempt,
            )
        ).map((notification) => ({
          ...notification,
          route: `/groups/${encodeURIComponent(groupId)}/runtime?turn=${encodeURIComponent(notification.turnId)}`,
        })),
      });
      return;
    }

    if (segments[1] === 'sync' && req.method === 'POST') {
      await this.runtime.scheduler.syncNow(groupId);
      send(res, 200, {
        group: publicGroup(this.runtime.store.getGroup(groupId)!),
      });
      return;
    }
    if (
      segments[1] === 'machine' &&
      segments.length === 2 &&
      req.method === 'PUT'
    ) {
      const body = object(await jsonBody(req));
      rejectSystemIdentityOverrides(body);
      if (body.actions !== undefined || body.prompts !== undefined)
        throw new Error(
          'Machine editing accepts only the creator-owned workflow skeleton',
        );
      send(res, 200, {
        group: publicGroup(
          await this.runtime.groups.reviseMachine({
            groupId,
            machine: body.machine,
            roles: body.roles,
            expectedRevision: requiredExpectedRevision(body),
          } as Parameters<CollaborationRuntime['groups']['reviseMachine']>[0]),
        ),
      });
      return;
    }
    if (
      segments[1] === 'machine-layout' &&
      segments.length === 2 &&
      req.method === 'PUT'
    ) {
      const body = object(await jsonBody(req));
      rejectSystemIdentityOverrides(body);
      send(res, 200, {
        group: publicGroup(
          await this.runtime.groups.updateMachineLayout({
            groupId,
            layout: body.layout,
            expectedRevision: requiredExpectedRevision(body),
          } as Parameters<
            CollaborationRuntime['groups']['updateMachineLayout']
          >[0]),
        ),
      });
      return;
    }
    if (
      segments[1] === 'roles' &&
      segments.length === 2 &&
      req.method === 'GET'
    ) {
      send(res, 200, {
        roleClaims: history.projection.roleClaims,
        implementations: history.projection.stateImplementations,
        bindings: this.runtime.store
          .listExecutorBindings(groupId)
          .map(publicBinding),
      });
      return;
    }
    if (
      segments[1] === 'roles' &&
      segments[2] &&
      segments[3] === 'claim' &&
      segments.length === 4 &&
      req.method === 'POST'
    ) {
      object(await jsonBody(req));
      send(res, 200, {
        group: publicGroup(
          await this.runtime.groups.claimRole(groupId, segments[2]),
        ),
      });
      return;
    }
    if (
      segments[1] === 'roles' &&
      segments[2] &&
      segments[3] === 'claim' &&
      segments.length === 4 &&
      req.method === 'DELETE'
    ) {
      const body = object(await jsonBody(req));
      send(res, 200, {
        group: publicGroup(
          await this.runtime.groups.releaseRole(
            groupId,
            segments[2],
            requiredExpectedRevision(body),
          ),
        ),
      });
      return;
    }
    if (segments[1] === 'states' && segments[3] === 'implementation') {
      const stateId = segments[2]!;
      if (req.method === 'PUT') {
        const body = object(await jsonBody(req));
        rejectSystemIdentityOverrides(body);
        send(res, 200, {
          group: publicGroup(
            await this.runtime.groups.publishStateImplementation({
              groupId,
              stateId,
              mode: requiredString(body, 'mode') as
                | 'manual'
                | 'assisted'
                | 'automatic',
              expectedRevision: requiredExpectedRevision(body),
              action:
                body.action && typeof body.action === 'object'
                  ? (body.action as never)
                  : null,
            }),
          ),
        });
        return;
      }
      if (req.method === 'DELETE') {
        const body = object(await jsonBody(req));
        send(res, 200, {
          group: publicGroup(
            await this.runtime.groups.withdrawStateImplementation(
              groupId,
              stateId,
              requiredExpectedRevision(body),
            ),
          ),
        });
        return;
      }
    }
    if (
      segments[1] === 'states' &&
      segments[3] === 'binding' &&
      req.method === 'PUT'
    ) {
      const stateId = segments[2]!;
      const body = object(await jsonBody(req));
      if (
        body.executorKind !== undefined ||
        body.adapter !== undefined ||
        body.promptOverride !== undefined
      )
        throw new Error(
          'Local binding cannot override Action type, adapter, or Prompt',
        );
      const active = history.projection.stateImplementations[stateId];
      if (!active?.action || !active.actionHash)
        throw new Error('State has no executable implementation');
      if (
        !(history.projection.roleClaims[active.implementation.role] ?? []).some(
          (claim) =>
            claim.principal_id === group.localPrincipalId &&
            claim.agent_id === group.localAgentId,
        )
      )
        throw new Error('Only the local role owner can configure this binding');
      this.runtime.store.saveExecutorBinding({
        groupId,
        stateId,
        implementationHash: active.implementationHash,
        actionHash: active.actionHash,
        executorKind: active.action.kind,
        adapter: active.action.adapter ?? null,
        agentJid: optionalString(body, 'agentJid'),
        workspacePath: requiredString(body, 'workspacePath'),
        filesystemAccessCap: requiredString(body, 'filesystemAccessCap') as
          | 'read_only'
          | 'workspace_write',
        approvalPolicy: requiredString(body, 'approvalPolicy') as
          | 'untrusted'
          | 'on-request'
          | 'never',
        config:
          body.config &&
          typeof body.config === 'object' &&
          !Array.isArray(body.config)
            ? (body.config as Record<string, unknown>)
            : {},
        enabled: body.enabled !== false,
      });
      send(res, 200, {
        binding: publicBinding(
          this.runtime.store.getExecutorBinding(
            groupId,
            stateId,
            active.implementationHash,
            active.actionHash,
          )!,
        ),
      });
      return;
    }
    if (segments[1] === 'commands' && req.method === 'POST') {
      const body = object(await jsonBody(req));
      const expectedRevision = requiredExpectedRevision(body);
      const command = requiredString(body, 'command');
      const updated =
        command === 'start'
          ? await this.runtime.groups.start(
              groupId,
              expectedRevision,
              body.initialHandoff as never,
            )
          : command === 'pause'
            ? await this.runtime.groups.pause(groupId, expectedRevision)
            : command === 'resume'
              ? await this.runtime.groups.resume(groupId, expectedRevision)
              : command === 'close'
                ? await this.runtime.groups.close(
                    groupId,
                    requiredString(body, 'reason'),
                    expectedRevision,
                  )
                : command === 'recover'
                  ? await this.runtime.groups.recoverTurn(
                      groupId,
                      requiredString(body, 'reason'),
                      expectedRevision,
                    )
                  : null;
      if (!updated)
        throw new Error(`Unsupported collaboration command: ${command}`);
      send(res, 200, { group: publicGroup(updated) });
      return;
    }
    if (
      segments[1] === 'turns' &&
      segments[2] === 'current' &&
      req.method === 'GET'
    ) {
      const turn = history.projection.activeTurnId
        ? history.projection.turns[history.projection.activeTurnId]
        : null;
      send(res, 200, {
        turn,
        routes: turn
          ? (history.definition.machine.states[turn.stateId]?.transitions ?? [])
          : [],
        stagedArtifacts: currentAttemptArtifacts(this.runtime, group, turn),
      });
      return;
    }
    if (
      segments[1] === 'turns' &&
      segments[3] === 'start' &&
      req.method === 'POST'
    ) {
      const body = object(await jsonBody(req));
      if (segments[2] !== history.projection.activeTurnId)
        throw new Error('expectedTurnId does not match the active turn');
      await this.runtime.scheduler.startTurn(
        groupId,
        requiredExpectedRevision(body),
      );
      send(res, 200, {
        group: publicGroup(this.runtime.store.getGroup(groupId)!),
      });
      return;
    }
    if (
      segments[1] === 'turns' &&
      segments[3] === 'complete' &&
      req.method === 'POST'
    ) {
      const body = object(await jsonBody(req));
      rejectSystemIdentityOverrides(body);
      if (
        body.targetState !== undefined ||
        body.target_state !== undefined ||
        body.nextState !== undefined
      )
        throw new Error('Clients submit an Outcome, not a target State');
      send(res, 200, {
        group: publicGroup(
          await this.runtime.groups.completeTurn({
            groupId,
            turnId: segments[2]!,
            expectedRevision: requiredExpectedRevision(body),
            outcome: requiredString(body, 'outcome'),
            summary: requiredText(body, 'summary'),
            instruction: optionalString(body, 'instruction') ?? '',
            markers: stringArray(body.markers, 'markers'),
            dataRefs: stringArray(body.dataRefs, 'dataRefs'),
            data:
              body.data &&
              typeof body.data === 'object' &&
              !Array.isArray(body.data)
                ? (body.data as Record<string, unknown>)
                : {},
            artifactIds: stringArray(body.artifactIds, 'artifactIds'),
          }),
        ),
      });
      return;
    }
    if (
      segments[1] === 'turns' &&
      segments[3] === 'artifacts' &&
      segments.length === 4 &&
      req.method === 'POST'
    ) {
      const body = object(await jsonBody(req));
      const encoded = requiredString(body, 'contentBase64');
      const contents = Buffer.from(encoded, 'base64');
      if (
        contents.toString('base64').replace(/=+$/u, '') !==
        encoded.replace(/=+$/u, '')
      )
        throw new Error('contentBase64 is invalid');
      const uploadRoot = path.join(
        path.dirname(this.runtime.databasePath),
        'collaboration-uploads',
        groupId,
        segments[2]!,
      );
      mkdirSync(uploadRoot, { recursive: true, mode: 0o700 });
      const stagedPath = path.join(uploadRoot, `upload-${crypto.randomUUID()}`);
      writeFileSync(stagedPath, contents, { mode: 0o600, flag: 'wx' });
      try {
        const artifact = this.runtime.groups.stageArtifact({
          groupId,
          turnId: segments[2]!,
          originalName: requiredString(body, 'fileName'),
          contentType:
            optionalString(body, 'contentType') ?? 'application/octet-stream',
          stagedPath,
        });
        send(res, 201, { artifact: publicStagedArtifact(artifact) });
      } catch (error) {
        rmSync(stagedPath, { force: true });
        throw error;
      }
      return;
    }
    if (
      segments[1] === 'turns' &&
      segments[3] === 'artifacts' &&
      segments[4] &&
      req.method === 'DELETE'
    ) {
      const artifact = this.runtime.groups.removeStagedArtifact(
        groupId,
        segments[2]!,
        segments[4],
      );
      send(res, 200, { removed: artifact.artifactId });
      return;
    }
    if (
      segments[1] === 'notifications' &&
      segments[3] === 'delivered' &&
      req.method === 'POST'
    ) {
      const scheduler = (
        this.runtime as unknown as {
          scheduler?: CollaborationRuntime['scheduler'];
        }
      ).scheduler;
      const pending =
        scheduler?.listPendingLocalNotifications(groupId, history) ??
        this.runtime.store.listPendingNotifications({
          recipientPrincipalId: group.localPrincipalId,
          recipientAgentId: group.localAgentId,
          groupId,
        });
      const notification = pending.find(
        (candidate) => candidate.notificationId === segments[2],
      );
      if (!notification)
        throw new Error('No current local notification exists');
      send(res, 200, {
        recorded: this.runtime.store.markNotificationDelivered({
          notificationId: notification.notificationId,
          recipientPrincipalId: group.localPrincipalId,
          recipientAgentId: group.localAgentId,
        }),
      });
      return;
    }
    if (segments[1] === 'events' && req.method === 'GET') {
      const limit = Math.min(
        500,
        Math.max(1, Number(url.searchParams.get('limit')) || 200),
      );
      send(res, 200, {
        events: this.runtime.store
          .listEventRecords(groupId, limit)
          .map((record) => ({
            commitHash: record.commitHash,
            event: redactConfig(record.event),
          })),
      });
      return;
    }
    if (segments[1] === 'audit' && req.method === 'GET') {
      const audit = buildCollaborationAudit({
        group,
        history,
        eventRecords: this.runtime.store.listEventRecords(
          groupId,
          history.projection.sequence,
        ),
        executions: this.runtime.store.listExecutions(groupId),
        notifications: this.runtime.store.listNotificationsForAudit(groupId),
        generatedAt: new Date().toISOString(),
      });
      send(res, 200, audit);
      return;
    }
    if (segments[1] === 'executions' && req.method === 'GET') {
      send(res, 200, {
        executions: this.runtime.store
          .listExecutions(groupId)
          .map(publicExecution),
      });
      return;
    }
    if (segments[1] === 'data' && req.method === 'GET') {
      send(res, 200, {
        paths: group.headCommit
          ? await listCollaborationSharedPaths({
              repositoryPath: group.repositoryPath,
              head: group.headCommit,
            })
          : [],
      });
      return;
    }
    if (segments[1] === 'data' && req.method === 'POST') {
      const body = object(await jsonBody(req));
      const turnId = optionalString(body, 'turnId');
      const hasTurnFence =
        turnId !== null ||
        body.attempt !== undefined ||
        body.fencingToken !== undefined;
      if (
        hasTurnFence &&
        (!turnId ||
          !Number.isInteger(body.attempt) ||
          Number(body.attempt) < 1 ||
          !optionalString(body, 'fencingToken'))
      )
        throw new Error(
          'turnId, attempt, and fencingToken must be provided together',
        );
      const result = await this.runtime.groups.updateData({
        groupId,
        path: requiredString(body, 'path'),
        content: requiredText(body, 'content'),
        expectedRevision: requiredExpectedRevision(body),
        mediaType: optionalString(body, 'mediaType'),
        turn: turnId
          ? {
              turnId,
              attempt: Number(body.attempt),
              fencingToken: requiredString(body, 'fencingToken'),
            }
          : null,
      });
      send(res, 200, {
        group: publicGroup(result.group),
        path: result.path,
        contentSha256: result.contentSha256,
        sizeBytes: result.sizeBytes,
      });
      return;
    }
    if (segments[1] === 'diagnostics' && req.method === 'GET') {
      send(res, 200, {
        collaboration: this.publicRuntimeStatus(),
        group: publicGroup(group),
        incidents: this.runtime.store
          .listIntegrityIncidents(groupId)
          .map((incident) =>
            publicIntegrityIncident(incident, group.remoteUrl),
          ),
        syncAttempts: this.runtime.store
          .listSyncAttempts(groupId, 50)
          .map((attempt) => publicSyncAttempt(attempt, group.remoteUrl)),
        validation: this.runtime.groups.getValidationMetrics(groupId),
        stagedArtifacts: currentAttemptArtifacts(
          this.runtime,
          group,
          history.projection.activeTurnId
            ? (history.projection.turns[history.projection.activeTurnId] ??
                null)
            : null,
        ),
      });
      return;
    }
    send(res, 405, { error: 'Method not allowed' });
  }

  private publicRuntimeStatus() {
    const status = this.runtime.status();
    let sensitiveUrls: string[] = [];
    if (status.available) {
      try {
        sensitiveUrls = this.runtime.store
          .listGroups()
          .map((group) => group.remoteUrl);
      } catch {
        sensitiveUrls = [];
      }
    }
    return {
      available: status.available,
      error: redactDiagnostic(status.error, sensitiveUrls),
      scheduler: status.scheduler
        ? {
            ...status.scheduler,
            groupErrors: Object.fromEntries(
              Object.entries(status.scheduler.groupErrors).map(
                ([groupId, message]) => [
                  groupId,
                  redactDiagnostic(message, sensitiveUrls),
                ],
              ),
            ),
          }
        : null,
      database: path.basename(status.databasePath),
    };
  }
}

export const collaborationWebApiTestables = {
  publicGroup,
  publicBinding,
  publicExecution,
  publicStagedArtifact,
  publicIntegrityIncident,
  publicSyncAttempt,
  redactConfig,
  redactDiagnostic,
  redactRemoteUrl,
  readActiveImplementationPrompts,
  rejectSystemIdentityOverrides,
};
